export type Project = {
  id: string;
  title: string;
  date: string;
  oneLiner: string;
  techStack: string[];
  searchTags: string[];
  liveUrl: string;
  liveUrlIsExternal: boolean;
  githubUrl: string | null;
  thumbnail: string;
  thumbnailObjectPosition?: string;
};

export const projects: Project[] = [
  {
    id: "draft-sheet",
    title: "A Draft Board for the Casual Fan - Fantasy Football",
    date: "2026-08-29",
    oneLiner:
      "Expert consensus tiers rebuilt for your exact league settings, with Yahoo, ESPN, Sleeper and mock-draft ADP side by side so you can see who your platform is giving away \u2014 and a one-page sheet to print for draft night.",
    techStack: [
      "TypeScript",
      "Next.js 16",
      "React 19",
      "Inline SVG",
      "CSS print media",
      "localStorage",
      "Python",
      "uv",
      "pandas",
      "nflreadpy",
      "Node type stripping",
      "Tailwind v4",
    ],
    searchTags: [
      "fantasy football",
      "draft",
      "cheat sheet",
      "beersheets",
      "tiers",
      "ADP",
      "average draft position",
      "PPR",
      "half PPR",
      "superflex",
      "keeper league",
      "value over replacement",
      "consensus rankings",
      "expert consensus",
      "ECR",
      "Yahoo",
      "ESPN",
      "Sleeper",
      "arbitrage",
      "market inefficiency",
      "printable",
      "draft board",
      "NFL",
      "offseason",
      "free agency",
    ],
    liveUrl: "/projects/draft-sheet",
    liveUrlIsExternal: false,
    githubUrl: null,
    thumbnail: "/landing/draft-sheet.png",
  },
  {
    id: "playbook",
    title: "Playbook — A Book of Plays for Any Size of Team",
    date: "2026-08-21",
    oneLiner:
      "A searchable, editable book of 367 football plays for flag, seven-on-seven and eleven-man teams \u2014 none of them stored as coordinates, so one authored play resolves onto every field size and prints as a call sheet or a wristband.",
    techStack: [
      "TypeScript",
      "Next.js 16",
      "React 19",
      "Inline SVG",
      "Pointer Events",
      "requestAnimationFrame",
      "DynamoDB",
      "AWS CDK",
      "Route Handlers",
      "Tailwind v4",
      "CSS print media",
      "Node type stripping",
    ],
    searchTags: [
      "football",
      "playbook",
      "play designer",
      "flag football",
      "5v5",
      "7v7",
      "11-man",
      "air raid",
      "mesh",
      "power",
      "inside zone",
      "RPO",
      "wing-t",
      "flexbone",
      "triple option",
      "west coast",
      "route tree",
      "formations",
      "coverage",
      "cover 3",
      "quarters",
      "blitz",
      "call sheet",
      "wristband",
      "coaching",
      "youth sports",
      "SVG editor",
      "animation",
    ],
    liveUrl: "/projects/playbook",
    liveUrlIsExternal: false,
    githubUrl: null,
    thumbnail: "/landing/playbook.png",
  },
  {
    id: "two-minute-drill",
    title: "Two-Minute Drill — Coach the Endgame",
    date: "2026-08-17",
    oneLiner:
      "Three hundred real NFL endgames, picked up with under two minutes left and one score in it \u2014 make the calls yourself, and the moment you diverge from what was actually done, a simulator takes over and you own what follows.",
    techStack: [
      "Monte Carlo simulation",
      "Web Workers",
      "TypeScript",
      "Next.js 16",
      "React 19",
      "Inline SVG",
      "Python",
      "uv",
      "nflreadpy",
      "pandas",
      "scikit-learn",
      "Isotonic calibration",
      "Logistic regression",
      "nflverse play-by-play",
    ],
    searchTags: [
      "NFL",
      "football",
      "two-minute drill",
      "clock management",
      "fourth down",
      "go for it",
      "field goal",
      "onside kick",
      "win probability",
      "Monte Carlo",
      "simulation",
      "nflverse",
      "nflfastR",
      "play-by-play",
      "sports analytics",
      "decision model",
      "calibration",
      "Brier score",
      "K-ball",
      "dynamic kickoff",
      "kicking trend",
      "1999-2025",
    ],
    liveUrl: "/projects/two-minute-drill",
    liveUrlIsExternal: false,
    githubUrl: null,
    thumbnail: "/landing/two-minute-drill.png",
  },
  {
    id: "chess-coach",
    title: "Chess Coach — Play at Your Level",
    date: "2026-08-10",
    oneLiner:
      "A chess app built to be enjoyed rather than survived \u2014 a difficulty that actually fits you, win chances that swing move by move, and a walk back through the game to the moment it turned.",
    techStack: [
      "Stockfish WASM",
      "Web Workers",
      "chess.js",
      "react-chessboard",
      "TypeScript",
      "Next.js 16",
      "React 19",
      "Tailwind v4",
      "Python",
      "uv",
      "python-chess",
      "SciPy",
      "Bradley\u2013Terry MLE",
      "Lichess puzzle database",
    ],
    searchTags: [
      "chess",
      "puzzles",
      "tactics",
      "endgame",
      "strategy",
      "chess engine",
      "Stockfish",
      "WebAssembly",
      "WASM",
      "Web Worker",
      "analysis board",
      "game review",
      "two player",
      "pass and play",
      "win probability",
      "Elo",
      "difficulty calibration",
      "Bradley-Terry",
      "self-play",
      "offline",
      "browser",
    ],
    liveUrl: "/projects/chess-coach",
    liveUrlIsExternal: false,
    githubUrl: "https://github.com/s1m31-63j6/greghlewis.com",
    thumbnail: "/landing/chess-coach.png",
  },
  {
    id: "glass-box-rag",
    title: "Glass Box RAG — Fair Use AI",
    date: "2026-07-20",
    oneLiner:
      "A legal precedent retrieval system that shows its work — ask about AI and copyright fair use, and watch the two searches race, the ranks reshuffle under fusion and again under a cross-encoder, and the agent decide whether to follow a citation.",
    techStack: [
      "AWS Lambda",
      "Function URL response streaming",
      "Amazon Bedrock",
      "Claude Sonnet 4.6",
      "Titan Text Embeddings v2",
      "Cohere Rerank 3.5",
      "BM25 (hand-written)",
      "Reciprocal Rank Fusion",
      "HyDE",
      "Agentic retrieval",
      "AWS CDK",
      "Python",
      "uv",
      "TypeScript",
      "Next.js 16",
      "React 19",
      "Tailwind v4",
      "SSE",
      "scikit-learn",
      "CourtListener API",
      "govinfo API",
    ],
    searchTags: [
      "RAG",
      "retrieval augmented generation",
      "hybrid search",
      "BM25",
      "dense retrieval",
      "vector search",
      "embeddings",
      "cross-encoder",
      "reranking",
      "HyDE",
      "query transformation",
      "agentic",
      "citation graph",
      "evaluation harness",
      "ablation",
      "legal tech",
      "fair use",
      "copyright",
      "AI law",
      "precedent",
      "case law",
      "bedrock",
      "streaming",
      "observability",
      "explainability",
    ],
    liveUrl: "/projects/glass-box-rag",
    liveUrlIsExternal: false,
    githubUrl: "https://github.com/s1m31-63j6/greghlewis.com",
    thumbnail: "/landing/glass-box-rag.png",
  },
  {
    id: "adventureworks-chat",
    title: "AdventureWorks Chat-Based Reporting",
    date: "2026-05-22",
    oneLiner:
      "A reporting engine you talk to — natural-language questions on Microsoft's canonical AdventureWorksDW sales warehouse return T-SQL, sortable tables, interactive Plotly charts, and a senior-analyst narrative.",
    techStack: [
      "Azure SQL Database",
      "Azure Functions",
      "Claude Sonnet 4.6",
      "Anthropic SDK",
      "Managed Identity",
      "Key Vault",
      "Bicep",
      "TypeScript",
      "Next.js 16",
      "React 19",
      "Tailwind v4",
      "node-sql-parser",
      "Plotly.js",
      "react-plotly.js",
      "Azure Table Storage",
      "AdventureWorksDW2022",
      "Cloudflare Turnstile",
      "SSE",
    ],
    searchTags: [
      "text-to-SQL",
      "natural language to SQL",
      "BI",
      "business intelligence",
      "reporting",
      "Microsoft",
      "Azure",
      "Power BI",
      "AdventureWorks",
      "data warehouse",
      "star schema",
      "Azure OpenAI",
      "GPT",
      "Claude",
      "A/B testing",
      "LLM comparison",
      "RAG",
      "structured outputs",
      "JSON mode",
      "prompt engineering",
      "cost engineering",
      "rate limiting",
      "managed identity",
      "zero secrets",
      "enterprise AI",
      "Anthropic",
    ],
    liveUrl: "/projects/adventureworks-chat",
    liveUrlIsExternal: false,
    githubUrl: "https://github.com/s1m31-63j6/greghlewis.com",
    thumbnail: "/landing/adventureworks-chat.png",
  },
  {
    id: "religious-voices",
    title: "Religious Voices",
    date: "2026-05-20",
    oneLiner:
      "Converse with chatbot personas of religious leaders across eight traditions and two centuries — each grounded in the leader's own published writings, with extrapolation tagged when the model strays.",
    techStack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind v4",
      "AWS Bedrock",
      "Claude Sonnet 4.6",
      "Cohere embed-english-v3",
      "prompt caching",
      "in-bundle vectors",
      "cosine similarity",
      "RAG",
      "Cloudflare Turnstile",
      "Python",
      "pydantic",
      "tiktoken",
      "uv",
      "AWS Amplify Hosting",
    ],
    searchTags: [
      "LLM",
      "chatbot",
      "religion",
      "comparative religion",
      "RAG",
      "vector search",
      "embeddings",
      "prompt caching",
      "persona",
      "roleplay",
      "Mormon",
      "Catholic",
      "Methodist",
      "Southern Baptist",
      "Jewish",
      "Buddhist",
      "Islam",
      "Hindu",
      "sermons",
      "encyclicals",
      "General Conference",
      "Journal of Discourses",
      "streaming",
      "SSE",
      "captcha",
      "rate limiting",
      "cost engineering",
      "Anthropic",
      "Sonnet",
    ],
    liveUrl: "/projects/religious-voices",
    liveUrlIsExternal: false,
    githubUrl: "https://github.com/s1m31-63j6/greghlewis.com",
    thumbnail: "/landing/religious-voices.png",
  },
  {
    id: "nfl-prospect-comparables",
    title: "NFL Prospect Comparables",
    date: "2026-04-30",
    oneLiner:
      "A 3D comp engine and conversational scout for the 2026 NFL Draft class — every prospect projected against 1,000+ historical drafted peers.",
    techStack: [
      "AWS Bedrock",
      "Bedrock Knowledge Bases",
      "Claude Sonnet 4.6",
      "Titan Text Embeddings v2",
      "Aurora Serverless v2 (pgvector)",
      "RAG",
      "Hybrid Retrieval",
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind v4",
      "three.js",
      "3d-force-graph",
      "Python",
      "scikit-learn",
      "k-means",
      "S3",
      "AWS Amplify Hosting",
      "AWS CDK",
      "Lambda",
    ],
    searchTags: [
      "LLM",
      "vector search",
      "embeddings",
      "scouting",
      "draft",
      "NFL",
      "comp engine",
      "archetypes",
      "agentic chat",
      "ScoutBot",
      "feature engineering",
      "cohort modeling",
      "validation",
      "Brugler",
      "Walter Football",
      "outcome leakage",
      "grid search",
      "Jaccard",
      "F1",
      "force-directed graph",
      "UMAP",
      "structured outputs",
      "Sonnet",
      "Opus",
      "Anthropic",
    ],
    liveUrl: "/projects/nfl-prospect-comparables",
    liveUrlIsExternal: false,
    githubUrl: "https://github.com/s1m31-63j6/greghlewis.com",
    thumbnail: "/landing/nfl-prospect-comparables.png",
    thumbnailObjectPosition: "top",
  },
  {
    id: "draft-2026-talent-vs-market",
    title: "2026 NFL Draft — Talent vs. Market",
    date: "2026-04-20",
    oneLiner:
      "A pre-draft prospect board that pits a model's talent score against the analyst-consensus market score — the delta is the story.",
    techStack: [
      "Python 3.11",
      "scikit-learn",
      "HistGradientBoostingRegressor",
      "polars",
      "pandas",
      "pyarrow",
      "Anthropic SDK",
      "Claude Opus 4.7",
      "Pydantic",
      "structured outputs",
      "LLM-as-judge",
      "Streamlit",
      "Plotly",
      "httpx",
      "Docker",
      "Hugging Face Spaces",
      "uv",
    ],
    searchTags: [
      "LLM",
      "ML",
      "machine learning",
      "gradient boosting",
      "regression",
      "Spearman",
      "career AV",
      "approximate value",
      "scouting",
      "NFL",
      "draft",
      "mock draft",
      "prospect board",
      "archetypes",
      "validation",
      "permutation importance",
      "scatter",
      "quadrant",
      "consensus board",
      "Wide Left Consensus",
      "CFBD",
      "nflverse",
      "ESPN",
      "Pro Football Network",
      "PFN",
      "Streamlit app",
      "data viz",
    ],
    liveUrl: "https://huggingface.co/spaces/s1m31/2026_nfl_draft_prospects",
    liveUrlIsExternal: true,
    githubUrl: null,
    thumbnail: "/landing/draft-2026-talent-vs-market.png",
  },
  {
    id: "elevator-cv",
    title: "elevator-cv.com",
    date: "2026-04-27",
    oneLiner:
      "Video-resume product — record, transcribe, and share a 30-second pitch instead of a static CV. AWS-native, Stripe-billed, in production.",
    techStack: [
      "Nuxt 3",
      "Vue 3",
      "Pinia",
      "Tailwind",
      "NestJS",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "AWS Amplify",
      "Amazon Cognito",
      "Amazon S3",
      "AWS MediaConvert",
      "Amazon Transcribe",
      "Amazon SES",
      "Amazon SNS",
      "AWS CloudWatch Logs",
      "Stripe",
      "JWT",
      "video.js",
      "hls.js",
      "MediaPipe Selfie Segmentation",
      "RecordRTC",
    ],
    searchTags: [
      "startup",
      "SaaS",
      "production app",
      "full-stack",
      "video processing",
      "speech-to-text",
      "transcription",
      "subscription billing",
      "auth",
      "OAuth",
      "serverless",
      "WebRTC",
      "background segmentation",
      "Postgres",
      "ORM",
      "REST API",
      "i18n",
    ],
    liveUrl: "https://elevator-cv.com",
    liveUrlIsExternal: true,
    githubUrl: null,
    thumbnail: "/landing/elevator-cv.png",
  },
  {
    id: "march-madness-2026",
    title: "March Madness 2026 — Bracket Prediction Engine",
    date: "2026-04-16",
    oneLiner:
      "Four independent bracket models — calibrated logistic, gradient-boosted, an Anthropic-powered Animal Kingdom heuristic, and a Vegas-odds fallback — tracked against the live tournament week by week.",
    techStack: [
      "Python",
      "scikit-learn",
      "xgboost",
      "statsmodels",
      "joblib",
      "isotonic calibration",
      "logistic regression",
      "OLS",
      "VIF",
      "Monte Carlo simulation",
      "Streamlit",
      "Altair",
      "Plotly",
      "Anthropic SDK",
      "rapidfuzz",
      "Docker",
      "Hugging Face Spaces",
    ],
    searchTags: [
      "LLM",
      "ML",
      "machine learning",
      "ROC AUC",
      "calibration",
      "feature engineering",
      "multicollinearity",
      "EDA",
      "univariate",
      "data quality",
      "NCAA",
      "basketball",
      "tournament",
      "bracket",
      "March Madness",
      "Barttorvik",
      "Kaggle",
      "MMLM",
      "Massey Ordinals",
      "EMBA",
      "advanced analytics",
      "retrospective",
      "leakage",
    ],
    liveUrl: "https://huggingface.co/spaces/s1m31/march-madness-2026",
    liveUrlIsExternal: true,
    githubUrl: "https://github.com/s1m31-63j6/march-madness-2026",
    thumbnail: "/landing/march-madness-2026.png",
  },
  {
    id: "scale-or-sell",
    title: "Sell now, or build to sell?",
    date: "2025-12-05",
    oneLiner:
      "An exit-timing scenario model for a founder-led B2B services firm — comparing a sell-now exit, organic compounding, and a build-to-sell path that adds a ramped growth lift from management infrastructure.",
    techStack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind v4",
      "Plotly.js",
      "react-plotly.js",
      "Python",
      "matplotlib",
      "monthly compounding model",
      "scenario analysis",
      "sensitivity analysis",
      "exit valuation",
      "EBITDA multiple",
      "AWS Amplify Hosting",
    ],
    searchTags: [
      "strategy",
      "M&A",
      "exit timing",
      "EBITDA",
      "scenario modeling",
      "founder-led",
      "B2B services",
      "growth-vs-exit",
      "valuation",
      "decision analysis",
      "EMBA",
      "consulting",
      "sensitivity heatmap",
      "interactive",
      "calculator",
      "data viz",
      "editorial",
    ],
    liveUrl: "/projects/scale-or-sell",
    liveUrlIsExternal: false,
    githubUrl: null,
    thumbnail: "/landing/scale-or-sell.png",
  },
  {
    id: "emba-roi-analysis",
    title: "EMBA — Is It Worth It?",
    date: "2024-10-24",
    oneLiner:
      "An interactive scenario calculator for whether a top-tier executive MBA pays back, sweeping cost, salary boost, market returns, and the savings discipline that quietly does most of the work.",
    techStack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind v4",
      "Plotly.js",
      "react-plotly.js",
      "NPV",
      "discounted cashflow",
      "scenario analysis",
      "sensitivity analysis",
      "financial modeling",
      "AWS Amplify Hosting",
    ],
    searchTags: [
      "data analysis",
      "DCF",
      "ROI",
      "education",
      "MBA",
      "EMBA",
      "decision analysis",
      "personal finance",
      "career economics",
      "interactive",
      "calculator",
      "sensitivity heatmap",
      "data viz",
      "editorial",
    ],
    liveUrl: "/projects/emba-roi-analysis",
    liveUrlIsExternal: false,
    githubUrl: null,
    thumbnail: "/landing/emba-roi-analysis.png",
  },
];
