export type Project = {
  id: string;
  title: string;
  date: string;
  oneLiner: string;
  techStack: string[];
  searchTags: string[];
  liveUrl: string;
  liveUrlIsExternal: boolean;
  githubUrl: string | null;
  thumbnail: string;
  thumbnailObjectPosition?: string;
};

export const projects: Project[] = [
  {
    id: "nfl-prospect-comparables",
    title: "NFL Prospect Comparables",
    date: "2026-04-30",
    oneLiner:
      "A 3D comp engine and conversational scout for the 2026 NFL Draft class — every prospect projected against 1,000+ historical drafted peers.",
    techStack: [
      "AWS Bedrock",
      "Bedrock Knowledge Bases",
      "Claude Sonnet 4.6",
      "Titan Text Embeddings v2",
      "Aurora Serverless v2 (pgvector)",
      "RAG",
      "Hybrid Retrieval",
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind v4",
      "three.js",
      "3d-force-graph",
      "Python",
      "scikit-learn",
      "k-means",
      "S3",
      "AWS Amplify Hosting",
      "AWS CDK",
      "Lambda",
    ],
    searchTags: [
      "LLM",
      "vector search",
      "embeddings",
      "scouting",
      "draft",
      "NFL",
      "comp engine",
      "archetypes",
      "agentic chat",
      "ScoutBot",
      "feature engineering",
      "cohort modeling",
      "validation",
      "Brugler",
      "Walter Football",
      "outcome leakage",
      "grid search",
      "Jaccard",
      "F1",
      "force-directed graph",
      "UMAP",
      "structured outputs",
      "Sonnet",
      "Opus",
      "Anthropic",
    ],
    liveUrl: "/projects/nfl-prospect-comparables",
    liveUrlIsExternal: false,
    githubUrl: "https://github.com/s1m31-63j6/greghlewis.com",
    thumbnail: "/landing/nfl-prospect-comparables.png",
    thumbnailObjectPosition: "top",
  },
  {
    id: "draft-2026-talent-vs-market",
    title: "2026 NFL Draft — Talent vs. Market",
    date: "2026-04-20",
    oneLiner:
      "A pre-draft prospect board that pits a model's talent score against the analyst-consensus market score — the delta is the story.",
    techStack: [
      "Python 3.11",
      "scikit-learn",
      "HistGradientBoostingRegressor",
      "polars",
      "pandas",
      "pyarrow",
      "Anthropic SDK",
      "Claude Opus 4.7",
      "Pydantic",
      "structured outputs",
      "LLM-as-judge",
      "Streamlit",
      "Plotly",
      "httpx",
      "Docker",
      "Hugging Face Spaces",
      "uv",
    ],
    searchTags: [
      "LLM",
      "ML",
      "machine learning",
      "gradient boosting",
      "regression",
      "Spearman",
      "career AV",
      "approximate value",
      "scouting",
      "NFL",
      "draft",
      "mock draft",
      "prospect board",
      "archetypes",
      "validation",
      "permutation importance",
      "scatter",
      "quadrant",
      "consensus board",
      "Wide Left Consensus",
      "CFBD",
      "nflverse",
      "ESPN",
      "Pro Football Network",
      "PFN",
      "Streamlit app",
      "data viz",
    ],
    liveUrl: "https://huggingface.co/spaces/s1m31/2026_nfl_draft_prospects",
    liveUrlIsExternal: true,
    githubUrl: null,
    thumbnail: "/landing/draft-2026-talent-vs-market.png",
  },
  {
    id: "elevator-cv",
    title: "elevator-cv.com",
    date: "2026-04-27",
    oneLiner:
      "Video-resume product — record, transcribe, and share a 30-second pitch instead of a static CV. AWS-native, Stripe-billed, in production.",
    techStack: [
      "Nuxt 3",
      "Vue 3",
      "Pinia",
      "Tailwind",
      "NestJS",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "AWS Amplify",
      "Amazon Cognito",
      "Amazon S3",
      "AWS MediaConvert",
      "Amazon Transcribe",
      "Amazon SES",
      "Amazon SNS",
      "AWS CloudWatch Logs",
      "Stripe",
      "JWT",
      "video.js",
      "hls.js",
      "MediaPipe Selfie Segmentation",
      "RecordRTC",
    ],
    searchTags: [
      "startup",
      "SaaS",
      "production app",
      "full-stack",
      "video processing",
      "speech-to-text",
      "transcription",
      "subscription billing",
      "auth",
      "OAuth",
      "serverless",
      "WebRTC",
      "background segmentation",
      "Postgres",
      "ORM",
      "REST API",
      "i18n",
    ],
    liveUrl: "https://elevator-cv.com",
    liveUrlIsExternal: true,
    githubUrl: null,
    thumbnail: "/landing/elevator-cv.png",
  },
  {
    id: "march-madness-2026",
    title: "March Madness 2026 — Bracket Prediction Engine",
    date: "2026-04-16",
    oneLiner:
      "Four independent bracket models — calibrated logistic, gradient-boosted, an Anthropic-powered Animal Kingdom heuristic, and a Vegas-odds fallback — tracked against the live tournament week by week.",
    techStack: [
      "Python",
      "scikit-learn",
      "xgboost",
      "statsmodels",
      "joblib",
      "isotonic calibration",
      "logistic regression",
      "OLS",
      "VIF",
      "Monte Carlo simulation",
      "Streamlit",
      "Altair",
      "Plotly",
      "Anthropic SDK",
      "rapidfuzz",
      "Docker",
      "Hugging Face Spaces",
    ],
    searchTags: [
      "LLM",
      "ML",
      "machine learning",
      "ROC AUC",
      "calibration",
      "feature engineering",
      "multicollinearity",
      "EDA",
      "univariate",
      "data quality",
      "NCAA",
      "basketball",
      "tournament",
      "bracket",
      "March Madness",
      "Barttorvik",
      "Kaggle",
      "MMLM",
      "Massey Ordinals",
      "EMBA",
      "advanced analytics",
      "retrospective",
      "leakage",
    ],
    liveUrl: "https://huggingface.co/spaces/s1m31/march-madness-2026",
    liveUrlIsExternal: true,
    githubUrl: "https://github.com/s1m31-63j6/march-madness-2026",
    thumbnail: "/landing/march-madness-2026.png",
  },
  {
    id: "emba-roi-analysis",
    title: "EMBA — Is It Worth It?",
    date: "2024-10-24",
    oneLiner:
      "A scenario-based NPV analysis on whether a top-tier executive MBA pays back, sweeping cost, salary boost, lost wages, and earning ceilings.",
    techStack: [
      "Python",
      "Jupyter",
      "NumPy",
      "pandas",
      "matplotlib",
      "NPV",
      "discounted cashflow",
      "scenario analysis",
      "Monte Carlo",
      "financial modeling",
    ],
    searchTags: [
      "data analysis",
      "DCF",
      "ROI",
      "education",
      "MBA",
      "EMBA",
      "BYU",
      "Wharton",
      "Stanford",
      "decision analysis",
      "personal finance",
      "career economics",
    ],
    liveUrl:
      "https://github.com/s1m31-63j6/byu_emba_code/blob/main/EMBA%20-%20Is%20it%20Worth%20It.ipynb",
    liveUrlIsExternal: true,
    githubUrl: "https://github.com/s1m31-63j6/byu_emba_code",
    thumbnail: "/landing/emba-roi-analysis.png",
  },
];
