/**
 * Air Raid.
 *
 * A concept-number system: the number names a whole five-man concept, not a
 * single route. Base look is 2x2 out of gun with X and H to one side, Y and Z
 * to the other, and F as the back — note that F is the RUNNING BACK in Air Raid
 * books, which collides with the pro-style fullback and is why the search facet
 * folds both onto FV.
 *
 * Screens carry names rather than numbers, alliterated by side, which is a real
 * convention and not a joke: Randy right, Larry left, Rita right, Lisa left.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, carry, opt, pass, play, route } from "../kit.ts";

const AR = ["11man", "7man"] as const;

export const AIR_RAID: PlaySpec[] = [
  play({
    id: "ar-6-four-verticals",
    name: "6 — Four Verticals",
    aliases: ["Four Verts", "6", "Verts"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "four-verticals",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Y", "H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("go"),
      Z: route("go"),
      Y: route("seam", { landmark: "hash" }, { priorityOrder: 1 }),
      H: route("seam", { landmark: "hash" }, { priorityOrder: 2 }),
      RB: route("checkdown", undefined, { startDelayMs: 300, priorityOrder: 4 }),
    },
    tags: ["verticals", "shot", "seam", "hash-landmark"],
    situations: ["1st-down", "2nd-long", "3rd-long", "vs-cover-3", "vs-cover-1", "two-minute"],
    coaching: {
      keys: "Count the safeties. One high, throw the seam away from the free safety; two high, hunt the hash.",
      vsCoverage: "Cover 3 dies on the seams. Quarters wants the back or a scramble.",
      commentary: "Four receivers running vertical stretches every deep defender at once and asks the quarterback one question.",
    },
  }),

  play({
    id: "ar-618-stick",
    name: "618 — Stick",
    aliases: ["Stick", "618", "Y-Stick"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "stick",
    primary: "Y",
    reads: [
      { order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "RB", "H"] },
    ],
    assignments: {
      QB: pass("gun-quick"),
      X: route("slant", undefined, { priorityOrder: 3 }),
      H: route("slant", undefined, { priorityOrder: 4 }),
      Y: opt("stick", "flat-defender", [
        { when: "expands", route: "stick", mods: { settleYd: 1 } },
        { when: "squeezes", route: "out", mods: { depth: 6 } },
      ], { depth: 6 }),
      Z: route("go"),
      RB: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
    },
    tags: ["stick", "quick-game", "triangle", "high-low"],
    situations: ["3rd-short", "3rd-medium", "1st-down", "red-zone", "vs-zone", "blitz-beater"],
    coaching: {
      keys: "Read the flat defender. He widens with the back, throw the stick; he sits on the stick, throw the flat.",
      commentary: "The most-called play in the system. Two defenders, three receivers, and the quarterback only has to be right about one man.",
    },
  }),

  play({
    id: "ar-617-quick-out",
    name: "617 — Quick Out",
    aliases: ["617", "Speed Out"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "quick-out",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["H", "Z", "Y"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: route("slant", undefined, { priorityOrder: 3 }),
      H: route("out", { depth: 5 }, { priorityOrder: 1 }),
      Y: route("slant", undefined, { priorityOrder: 4 }),
      Z: route("out", { depth: 5 }, { priorityOrder: 2 }),
      RB: route("checkdown", undefined, { startDelayMs: 250 }),
    },
    tags: ["quick-game", "three-step", "outbreaking", "rhythm"],
    situations: ["1st-down", "2nd-short", "3rd-short", "sideline", "vs-zone"],
    coaching: { keys: "Off coverage takes the out. Press takes the slant behind it." },
  }),

  play({
    id: "ar-8-y-corner",
    name: "8 — Y-Corner",
    aliases: ["Y-Corner", "8", "Snag"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-bunch-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "snag",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("hitch", { depth: 6 }, { priorityOrder: 2 }),
      Y: route("corner", { depth: 14 }, { priorityOrder: 1 }),
      H: route("arrow", { toSide: "R" }, { priorityOrder: 3 }),
      X: route("slant"),
      RB: route("checkdown", undefined, { startDelayMs: 280, priorityOrder: 4 }),
    },
    tags: ["snag", "bunch", "triangle", "corner", "rub"],
    situations: ["red-zone", "3rd-medium", "vs-cover-1", "vs-man", "goal-line"],
    coaching: {
      keys: "The corner is first if the safety is late. Otherwise it is a hitch-flat triangle on the corner.",
      commentary: "A bunch makes the rub happen without anybody having to run into anybody.",
    },
  }),

  play({
    id: "ar-66-hitch-seam",
    name: "66 — Hitch Seam",
    aliases: ["66", "Hitch-Seam", "Slot Fade"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "hitch-seam",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "Y", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: route("hitch", { depth: 5 }, { priorityOrder: 3 }),
      Z: route("hitch", { depth: 5 }, { priorityOrder: 1 }),
      Y: route("seam", undefined, { priorityOrder: 2 }),
      H: route("seam", undefined, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 250 }),
    },
    tags: ["quick-game", "hitch", "seam", "press-beater"],
    situations: ["1st-down", "2nd-short", "vs-zone", "vs-cover-3"],
    coaching: { keys: "Off coverage, take the hitch on rhythm. Press or Cover 0, throw the pressed slot vertical." },
  }),

  play({
    id: "ar-91-shallow-cross",
    name: "91 — Shallow Cross",
    aliases: ["91", "Shallow", "Drive"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "half-slide",
    concept: "shallow-cross",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["X", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("shallow", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("dig", { depth: 10 }, { priorityOrder: 2 }),
      H: route("go"),
      Z: route("go"),
      RB: route("flat", { toSide: "L" }, { startDelayMs: 220, priorityOrder: 3 }),
    },
    tags: ["shallow", "crosser", "man-beater", "high-low", "drive"],
    situations: ["3rd-medium", "3rd-long", "1st-down", "vs-man", "vs-cover-1", "blitz-beater"],
    coaching: {
      keys: "Shallow to dig, high-low on the middle linebacker. Against man the shallow keeps running.",
      commentary: "Two in-breaking routes at two depths on one defender. He is wrong either way.",
    },
  }),

  play({
    id: "ar-92-mesh",
    name: "92 — Mesh",
    aliases: ["Mesh", "92"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "slide-right",
    concept: "mesh",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Z", "Y", "H", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("corner", { depth: 10 }, { priorityOrder: 1 }),
      Y: opt("shallow", "man-or-zone", [
        { when: "zone", route: "shallow", mods: { settleYd: 2 } },
        { when: "man", route: "shallow" },
      ], { toSide: "L", meshWith: "H", meshDepthYd: 5, lane: "over" }),
      H: opt("shallow", "man-or-zone", [
        { when: "zone", route: "shallow", mods: { settleYd: 2 } },
        { when: "man", route: "shallow" },
      ], { toSide: "R", meshWith: "Y", meshDepthYd: 5, lane: "under" }),
      X: route("dig", { depth: 12 }, { priorityOrder: 3 }),
      RB: route("swing", { toSide: "R" }, { startDelayMs: 250, priorityOrder: 4 }),
    },
    tags: ["mesh", "rub", "man-beater", "quick-game", "signature"],
    situations: ["1st-down", "3rd-medium", "red-zone", "blitz-beater", "vs-man", "vs-cover-1"],
    coaching: {
      keys: "Corner first against single high. If the flat defender widens, the shallows sit down.",
      vsCoverage: "Cover 1, run through the mesh. Cover 3, sit at five or six between the hooks.",
      commentary: "The whole offense in one play: two shallows rubbing, a corner over the top, a swing to the field.",
    },
  }),

  play({
    id: "ar-93-h-wheel",
    name: "93 — H Wheel",
    aliases: ["93", "Wheel", "H-Wheel"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "wheel",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "SS", progression: ["Z", "X", "H", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("curl", { depth: 15 }, { priorityOrder: 2 }),
      H: route("wheel", undefined, { priorityOrder: 3 }),
      Y: route("hitch", { depth: 6 }, { priorityOrder: 4 }),
      Z: route("post", { depth: 12 }, { priorityOrder: 1 }),
      RB: route("swing", { toSide: "L" }, { startDelayMs: 260 }),
    },
    tags: ["wheel", "post", "man-beater", "shot"],
    situations: ["2nd-long", "3rd-long", "vs-man", "vs-cover-1", "plus-territory"],
    coaching: { keys: "Post first, then the mandatory fifteen-yard curl, then the wheel up the sideline." },
  }),

  play({
    id: "ar-94-deep-out",
    name: "94 — Deep Out",
    aliases: ["94", "Texas", "Deep Out"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "half-slide",
    concept: "deep-out",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "OLB", progression: ["X", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("dig", { depth: 12 }, { priorityOrder: 1 }),
      H: route("whip", undefined, { priorityOrder: 3 }),
      Y: route("out", { depth: 12 }, { priorityOrder: 2 }),
      Z: route("go"),
      RB: route("texas", undefined, { startDelayMs: 240, priorityOrder: 4 }),
    },
    tags: ["deep-out", "texas", "whip", "intermediate"],
    situations: ["3rd-medium", "3rd-long", "sideline", "vs-zone", "blitz-beater"],
    coaching: { keys: "The Texas route by the back is the hot answer against pressure. Everything else is on rhythm." },
  }),

  play({
    id: "ar-95-y-cross",
    name: "95 — Y-Cross",
    aliases: ["95", "Y-Cross", "Cross"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "y-cross",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["Z", "H", "Y", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", undefined, { priorityOrder: 1 }),
      H: route("out", { depth: 8 }, { priorityOrder: 2 }),
      Y: route("drag", { toSide: "R", depthAdj: 6 }, { priorityOrder: 3 }),
      X: route("post", { depth: 12 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["cross", "deep-crosser", "man-beater", "levels"],
    situations: ["2nd-long", "3rd-long", "vs-man", "vs-cover-3", "plus-territory"],
    coaching: {
      keys: "Under the outside backer, over the Mike, under the weak safety. The ball comes out on time, off the drop.",
    },
  }),

  play({
    id: "ar-96-all-curl",
    name: "96 — All Curl",
    aliases: ["96", "Curls", "All Curl"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "curl",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["X", "Z", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("curl", { depth: 15 }, { priorityOrder: 1 }),
      Z: route("curl", { depth: 15 }, { priorityOrder: 2 }),
      Y: route("curl", { depth: 8 }, { priorityOrder: 3 }),
      H: route("bubble", undefined, { priorityOrder: 5 }),
      RB: route("swing", { toSide: "R" }, { startDelayMs: 260, priorityOrder: 4 }),
    },
    tags: ["curl", "zone-beater", "settle", "rhythm"],
    situations: ["3rd-medium", "3rd-long", "vs-cover-2", "vs-zone", "two-minute"],
    coaching: { keys: "Find the window between the corner and the flat defender and sit in it." },
  }),

  play({
    id: "ar-98-double-smash",
    name: "98 — Double Smash",
    aliases: ["98", "Smash", "Double Smash"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "smash",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Y", "Z", "H", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("hitch", { depth: 5 }, { priorityOrder: 4 }),
      Z: route("hitch", { depth: 5 }, { priorityOrder: 2 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 1 }),
      H: route("corner", { depth: 12 }, { priorityOrder: 3 }),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["smash", "high-low", "corner", "hitch", "mirrored"],
    situations: ["red-zone", "3rd-medium", "vs-cover-2", "vs-zone", "sideline"],
    coaching: {
      keys: "High-low the corner on both sides. Pick the softer one before the snap and confirm it after.",
      commentary: "Mirroring the concept means the quarterback never has a wrong side to look at.",
    },
  }),

  play({
    id: "ar-randy-screen",
    name: "Randy — WR Screen",
    aliases: ["Randy", "Now Screen", "Quick Screen"],
    philosophy: "air-raid",
    family: "screen",
    variantScope: [...AR],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "screen-release",
    concept: "wr-screen",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("screen", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("stalk"),
      H: route("stalk"),
      X: route("go"),
      RB: route("checkdown", undefined, { startDelayMs: 200 }),
    },
    tags: ["screen", "perimeter", "numbers", "space"],
    situations: ["1st-down", "2nd-short", "backed-up", "vs-zone"],
    coaching: { keys: "Count the box. If they are light outside, this is a run call that happens to be a throw." },
  }),

  play({
    id: "ar-rita-tunnel",
    name: "Rita — Tunnel Screen",
    aliases: ["Rita", "Tunnel", "Slow Screen"],
    philosophy: "air-raid",
    family: "screen",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "screen-release",
    concept: "tunnel-screen",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("pivot", { toSide: "L", depth: 1 }, { startDelayMs: 200, priorityOrder: 1 }),
      Y: route("wall", { toSide: "R" }),
      H: route("wall", { toSide: "R" }),
      X: route("go"),
      RB: route("checkdown", undefined, { startDelayMs: 260 }),
    },
    tags: ["screen", "tunnel", "delayed", "wall"],
    situations: ["2nd-long", "3rd-long", "vs-man", "blitz-beater"],
    coaching: {
      keys: "Sell the fade for one step, then work back inside behind the wall.",
      commentary: "Against a corner who has been beaten deep twice, this is the third-down answer.",
    },
  }),
  play({
    id: "ar-93-post-wheel",
    name: "93 — Post Wheel",
    aliases: ["Post Wheel", "93 Switch"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-stack-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "post-wheel",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("post", { depth: 10 }, { priorityOrder: 2 }),
      H: route("wheel", undefined, { priorityOrder: 1 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      Y: route("shallow", { toSide: "R" }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 280 }),
    },
    tags: ["post-wheel", "switch", "stack", "man-beater", "shot"],
    situations: ["2nd-long", "3rd-long", "vs-man", "vs-cover-1", "plus-territory"],
    coaching: {
      keys: "The stack forces the corner to choose. He takes the post, the wheel runs behind him.",
      commentary: "A stack means neither defender can jam anybody, so the switch happens clean.",
    },
  }),

  play({
    id: "ar-99-four-verts-tag",
    name: "99 — Verts Bender",
    aliases: ["Bender", "99", "Divide"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-empty-trey",
    personnelId: "11",
    protection: "big-on-big",
    concept: "four-verticals",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Y", "Z", "F"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("go"),
      Z: route("go"),
      H: route("glance", { depth: 16 }, { priorityOrder: 1 }),
      Y: route("seam", { landmark: "hash" }, { priorityOrder: 2 }),
      F: route("checkdown", undefined, { startDelayMs: 260, priorityOrder: 3 }),
    },
    tags: ["verticals", "bender", "empty", "single-high-beater"],
    situations: ["2nd-long", "3rd-long", "must-score", "vs-cover-3", "vs-cover-1"],
    coaching: {
      keys: "Against one high safety the inside receiver bends across his face instead of running past him.",
    },
  }),

  play({
    id: "ar-96-shakes",
    name: "96 — Shakes",
    aliases: ["Shakes", "Double Move Curl"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "max-protect",
    concept: "shakes",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "X", "Y"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("sluggo", undefined, { priorityOrder: 1 }),
      X: route("sluggo", undefined, { priorityOrder: 2 }),
      Y: route("over", { toSide: "L" }, { priorityOrder: 3 }),
      H: route("checkdown"),
      RB: block({ block: "pass-set" }),
    },
    tags: ["shakes", "double-move", "shot", "max-protect"],
    situations: ["2nd-long", "plus-territory", "vs-cover-2", "vs-zone"],
    coaching: {
      keys: "Sell the stop for three steps, then climb into the grass between the safeties.",
      commentary: "The answer to a corner who has been jumping the curl all afternoon.",
    },
  }),

  play({
    id: "ar-92-snake",
    name: "92 Snake",
    aliases: ["Snake", "Mesh Snake"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-trey-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "mesh",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Y", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("post", { depth: 12 }, { priorityOrder: 1 }),
      Y: route("shallow", { toSide: "L", meshWith: "X", meshDepthYd: 5, lane: "over" }, { priorityOrder: 2 }),
      X: route("shallow", { toSide: "R", meshWith: "Y", meshDepthYd: 5, lane: "under" }, { priorityOrder: 3 }),
      Z: route("go"),
      RB: route("swing", { toSide: "R" }, { startDelayMs: 250, priorityOrder: 4 }),
    },
    tags: ["mesh", "snake", "post", "vs-cover-3", "rub"],
    situations: ["3rd-medium", "1st-down", "vs-cover-3", "vs-zone"],
    coaching: {
      keys: "The mesh occupies the underneath, and the post runs through where the middle safety used to be.",
      commentary: "Mesh with a post on top is how the concept attacks three-deep instead of man.",
    },
  }),

  play({
    id: "ar-620-spacing",
    name: "620 — Spacing",
    aliases: ["620", "Spacing", "Spot"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-quads-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "spacing",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "H", "F", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("go"),
      H: route("spot", { depth: 6 }, { priorityOrder: 2 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      F: route("hitch", { depth: 6 }, { priorityOrder: 3 }),
      X: route("slant", undefined, { priorityOrder: 4 }),
    },
    tags: ["spacing", "quads", "quick-game", "horizontal", "zone-beater"],
    situations: ["3rd-short", "two-minute", "backed-up", "vs-zone"],
    coaching: { keys: "Four receivers in one band. Throw to whichever window nobody is standing in." },
  }),

  play({
    id: "ar-y-sail",
    name: "Y-Sail",
    aliases: ["Sail", "Flood Right"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-trey-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["Z", "Y", "H"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", undefined, { priorityOrder: 1 }),
      Y: route("sail", undefined, { priorityOrder: 2 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      X: route("dig", { depth: 14 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 280 }),
    },
    tags: ["flood", "three-level", "sail", "trey", "sideline"],
    situations: ["3rd-medium", "3rd-long", "sideline", "vs-cover-3", "two-minute"],
    coaching: { keys: "Three levels to the trips side. The corner and the flat defender cannot cover all of it." },
  }),

  play({
    id: "ar-y-corner-scissors",
    name: "8 Scissors",
    aliases: ["Scissors", "Y-Corner Scissors"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "scissors",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "SS", keySide: "playside", progression: ["H", "Y", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go"),
      Y: route("corner", { depth: 12 }, { priorityOrder: 2 }),
      H: route("post", { depth: 12 }, { priorityOrder: 1 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      RB: route("bubble", { toSide: "R" }, { priorityOrder: 4 }),
    },
    tags: ["scissors", "crossing-verticals", "trips", "man-beater"],
    situations: ["2nd-long", "3rd-long", "vs-man", "vs-cover-1", "red-zone"],
    coaching: {
      keys: "The two inside receivers cross deep. In man that is a legal rub fifteen yards downfield.",
    },
  }),

  play({
    id: "ar-f-shovel",
    name: "F-Shovel",
    aliases: ["Shovel", "F-5 Shovel"],
    philosophy: "air-raid",
    family: "screen",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "screen-release",
    concept: "shovel",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "DE", progression: ["RB"] }],
    assignments: {
      QB: pass("gun-quick"),
      RB: route("shovel", { toSide: "R" }, { startDelayMs: 200, priorityOrder: 1 }),
      X: route("go"),
      Z: route("go"),
      Y: route("stalk"),
      H: route("stalk"),
    },
    tags: ["shovel", "screen", "influence", "quick"],
    situations: ["3rd-short", "goal-line", "blitz-beater", "short-yardage"],
    coaching: {
      keys: "The receivers clear out vertically and the back sits down underneath the rush.",
      commentary: "A shovel is a run that starts as a pass, which is why it beats an aggressive front.",
    },
  }),

  play({
    id: "ar-90-corner-post",
    name: "90 — Corner Post",
    aliases: ["Corner Post", "Sluggo Post", "90"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "half-slide",
    concept: "corner-post",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Z", "H", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("post-corner", { depth: 14 }, { priorityOrder: 1 }),
      H: route("dig", { depth: 12 }, { priorityOrder: 2 }),
      X: route("go", { depth: 18 }, { priorityOrder: 3 }),
      Y: route("shallow", { toSide: "R" }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["double-move", "shot", "single-high-beater"],
    situations: ["2nd-long", "plus-territory", "vs-cover-1", "vs-cover-3"],
    coaching: { keys: "Break to the corner at fourteen and come back across the safety's face at eighteen." },
  }),

  play({
    id: "ar-64-levels",
    name: "64 — Levels",
    aliases: ["Levels", "Double In", "64"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-trips-right",
    personnelId: "10",
    protection: "half-slide",
    concept: "levels",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Y", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("dig", { depth: 12 }, { priorityOrder: 1 }),
      Y: route("under", { depth: 5 }, { priorityOrder: 2 }),
      Z: route("go", { depth: 18 }, { priorityOrder: 3 }),
      X: route("post", { depth: 16 }, { priorityOrder: 4 }),
      RB: route("swing", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["levels", "in-breaking", "high-low", "zone-beater"],
    situations: ["2nd-long", "3rd-medium", "vs-zone", "vs-cover-2"],
    coaching: { keys: "Two in-cuts seven yards apart on the same linebacker." },
  }),

  play({
    id: "ar-63-drive",
    name: "63 — Drive",
    aliases: ["Drive", "Shallow Dig", "63"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "half-slide",
    concept: "drive",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["Y", "H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Y: route("shallow", { toSide: "R" }, { priorityOrder: 1 }),
      H: route("dig", { depth: 11 }, { priorityOrder: 2, startDelayMs: 180 }),
      Z: route("go", { depth: 18 }, { priorityOrder: 3 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["drive", "shallow", "man-beater", "rub"],
    situations: ["3rd-medium", "1st-down", "vs-man", "blitz-beater"],
    coaching: { keys: "The shallow runs until somebody carries it. The dig replaces him at eleven." },
  }),

  play({
    id: "ar-97-choice",
    name: "97 — Choice",
    aliases: ["Choice", "Iso Option", "97"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-empty-quads",
    personnelId: "10",
    protection: "big-on-big",
    concept: "choice",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "backside", progression: ["X", "H", "Y"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: opt("stick", "leverage", [
        { when: "inside leverage", route: "out", mods: { depth: 8 } },
        { when: "outside leverage", route: "dig", mods: { depth: 8 } },
        { when: "off coverage", route: "hitch", mods: { depth: 7 } },
      ], { depth: 8 }),
      Z: route("go", { depth: 16 }, { priorityOrder: 2 }),
      H: route("out", { depth: 10 }, { priorityOrder: 3 }),
      Y: route("spot", { depth: 6 }, { priorityOrder: 4 }),
      F: route("flat", { toSide: "R" }, { priorityOrder: 5 }),
    },
    tags: ["choice", "option-route", "isolation", "empty"],
    situations: ["3rd-medium", "vs-man", "2nd-long", "must-score"],
    coaching: {
      install: "Isolate the best receiver away from four others and let him win on leverage.",
      keys: "Everyone else is a decoy who has to be covered anyway.",
    },
  }),

  play({
    id: "ar-quads-flood",
    name: "Quads Flood",
    aliases: ["Quads Flood", "Four Strong"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-empty-quads",
    personnelId: "10",
    protection: "half-slide",
    concept: "flood",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["F", "H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      F: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      H: route("sail", { depth: 12 }, { priorityOrder: 2 }),
      Z: route("go", { depth: 18 }, { priorityOrder: 3 }),
      Y: route("spot", { depth: 6 }, { priorityOrder: 4 }),
      X: route("dig", { depth: 14 }, { priorityOrder: 5 }),
    },
    tags: ["flood", "quads", "overload", "three-level"],
    situations: ["3rd-medium", "2nd-long", "vs-zone", "vs-cover-3"],
    coaching: { commentary: "Four receivers to one side against three defenders is arithmetic the defence cannot fix after the snap." },
  }),

  play({
    id: "ar-4-verts-nub",
    name: "6 — Verts Nub",
    aliases: ["Nub Verts", "Solo Verts"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-nub-trips",
    personnelId: "11",
    protection: "half-slide",
    concept: "four-verticals",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "X", "Z", "Y"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", { depth: 18 }, { priorityOrder: 3 }),
      H: route("seam", { depth: 16 }, { priorityOrder: 1 }),
      X: route("seam", { depth: 16 }, { priorityOrder: 2 }),
      Y: route("seam", { depth: 14 }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "R" }, { priorityOrder: 5 }),
    },
    tags: ["four-verts", "nub", "seam", "single-high-beater"],
    situations: ["2nd-long", "3rd-long", "vs-cover-3", "must-score"],
    coaching: { keys: "Three receivers to one side and a tight end alone on the other stretch a single-high safety past what he can cover." },
  }),

  play({
    id: "ar-92-mesh-return",
    name: "92 — Mesh Return",
    aliases: ["Mesh Return", "Return Mesh"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "half-slide",
    concept: "mesh",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Y", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("shallow", { toSide: "L", meshWith: "Y", meshDepthYd: 5, lane: "over" }, { priorityOrder: 1 }),
      Y: route("jerk", { depth: 6 }, { priorityOrder: 2 }),
      Z: route("corner", { depth: 12 }, { priorityOrder: 3 }),
      X: route("go", { depth: 18 }, { priorityOrder: 4 }),
      RB: route("swing", { toSide: "R" }, { priorityOrder: 5 }),
    },
    tags: ["mesh", "jerk", "man-beater", "double-move"],
    situations: ["3rd-medium", "vs-man", "vs-cover-1", "red-zone"],
    coaching: { commentary: "The same mesh the defence has practised all week, with the second crosser breaking back the other way." },
  }),

  play({
    id: "ar-smash-divide",
    name: "98 — Smash Divide",
    aliases: ["Smash Divide", "Smash Seam"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-trey-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "smash",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "Y", "H", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("hitch", { depth: 6 }, { priorityOrder: 2 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 1 }),
      H: route("seam", { depth: 16 }, { priorityOrder: 3 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["smash", "divide", "high-low", "two-high-beater"],
    situations: ["3rd-medium", "red-zone", "vs-cover-2", "vs-zone"],
    coaching: { keys: "The seam route splits the two safeties so neither can help on the corner." },
  }),

  play({
    id: "ar-slot-fade",
    name: "Slot Fade",
    aliases: ["Seam Fade", "Slot Go"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-stack-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "fade",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "$", progression: ["H", "Z", "Y"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: route("fade", { depth: 10 }, { priorityOrder: 1 }),
      Z: route("slant", { depth: 6 }, { priorityOrder: 2 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      X: route("go", { depth: 16 }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["fade", "stack", "red-zone", "man-beater"],
    situations: ["red-zone", "goal-line", "vs-man", "3rd-short"],
    coaching: { keys: "A stacked slot gets a free release. Inside the ten that is all the separation the throw needs." },
  }),

  play({
    id: "ar-dagger",
    name: "62 — Dagger",
    aliases: ["Dagger", "Seam Dig", "62"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "dagger",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["Z", "H", "X", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("seam", { depth: 18 }, { priorityOrder: 2 }),
      Z: route("dig", { depth: 14 }, { priorityOrder: 1, startDelayMs: 150 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      Y: route("checkdown", { toSide: "R" }, { priorityOrder: 4 }),
      RB: route("swing", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["dagger", "dig", "seam-clear", "zone-beater"],
    situations: ["2nd-long", "3rd-long", "vs-cover-3", "vs-zone"],
    coaching: { keys: "The vertical clears the hook defender out and the dig runs into the space he left." },
  }),

  play({
    id: "ar-stick-draw",
    name: "Stick Draw",
    aliases: ["Draw", "QB Draw", "Delay"],
    philosophy: "air-raid",
    family: "run",
    variantScope: ["11man"],
    formationId: "gun-empty",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "QB", aim: "playside-A" },
    primary: "QB",
    assignments: {
      QB: carry("playside-A", "downhill"),
      Z: route("stalk"),
      X: route("stalk"),
      H: route("stalk"),
      Y: route("stalk"),
      F: route("stalk"),
    },
    tags: ["draw", "qb-run", "empty", "answer"],
    situations: ["2nd-long", "3rd-medium", "vs-cover-0", "blitz-beater"],
    coaching: {
      keys: "Empty with five receivers usually means light boxes. Take the yards on the ground when they hand them to you.",
    },
  }),

  play({
    id: "ar-mid-screen",
    name: "Middle Screen",
    aliases: ["Mid Screen", "Delay Screen"],
    philosophy: "air-raid",
    family: "screen",
    variantScope: ["11man"],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "screen-release",
    concept: "middle-screen",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["RB"] }],
    assignments: {
      QB: pass("gun-3"),
      RB: route("checkdown", { toSide: "R" }, { priorityOrder: 1, startDelayMs: 500 }),
      Z: route("go", { depth: 18 }, { priorityOrder: 2 }),
      X: route("go", { depth: 18 }, { priorityOrder: 3 }),
      H: route("go", { depth: 16 }, { priorityOrder: 4 }),
      Y: route("go", { depth: 16 }, { priorityOrder: 5 }),
    },
    tags: ["screen", "middle", "rush-beater", "answer"],
    situations: ["2nd-long", "3rd-long", "blitz-beater", "vs-cover-0"],
    coaching: { keys: "Four vertical routes empty the middle of the field, then the ball goes there." },
  }),

  play({
    id: "ar-y-stick-nod",
    name: "618 — Stick Nod",
    aliases: ["Stick Nod", "Stick Seam"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "stick-nod",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "S", progression: ["Y", "H", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      Y: route("sluggo", { depth: 14 }, { priorityOrder: 1 }),
      H: route("out", { depth: 8 }, { priorityOrder: 2 }),
      Z: route("go", { depth: 18 }, { priorityOrder: 3 }),
      X: route("dig", { depth: 12 }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["stick-nod", "double-move", "seam", "setup"],
    situations: ["2nd-long", "plus-territory", "vs-zone", "red-zone"],
    coaching: { commentary: "Throw Stick four times. The fifth one the linebacker jumps and the seam is behind him." },
  }),

  play({
    id: "ar-tunnel-post",
    name: "Rita Post",
    aliases: ["Tunnel Post", "Screen and Shot"],
    philosophy: "air-raid",
    family: "screen",
    variantScope: [...AR],
    formationId: "gun-stack-right",
    personnelId: "11",
    protection: "screen-release",
    concept: "tunnel-screen",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("screen", { toSide: "R" }, { priorityOrder: 1, startDelayMs: 200 }),
      H: route("crack"),
      X: route("post", { depth: 16 }, { priorityOrder: 2 }),
      Y: route("stalk"),
      RB: route("swing", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["screen", "tunnel", "perimeter", "shot-tag"],
    situations: ["1st-down", "2nd-long", "vs-zone", "opening-script"],
    coaching: { keys: "If the corner has started squatting on the tunnel, the post behind it is the whole reason to keep calling it." },
  }),

  play({
    id: "ar-989-double-post",
    name: "989 — Double Post",
    aliases: ["Double Post", "Switch Post", "989"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "max-protect",
    concept: "double-post",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "H", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("post", { depth: 18 }, { priorityOrder: 1 }),
      H: route("post", { depth: 14 }, { priorityOrder: 2 }),
      Z: route("go", { depth: 18 }, { priorityOrder: 3 }),
      Y: route("checkdown", { toSide: "R" }, { priorityOrder: 4 }),
      RB: block({ block: "pass-set" }),
    },
    tags: ["double-post", "shot", "max-protect", "single-high-beater"],
    situations: ["2nd-long", "plus-territory", "must-score", "vs-cover-3"],
    coaching: {
      keys: "The short post holds the safety and the deep post runs past him. Seven blockers means the quarterback gets to wait.",
    },
  }),

  play({
    id: "ar-empty-spacing",
    name: "620 — Empty Spacing",
    aliases: ["Empty Spacing", "Five Spacing"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-empty-trey",
    personnelId: "11",
    protection: "big-on-big",
    concept: "spacing",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["Y", "H", "F", "Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      Y: route("spot", { depth: 6 }, { priorityOrder: 1 }),
      H: route("hitch", { depth: 6 }, { priorityOrder: 2 }),
      F: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      Z: route("hitch", { depth: 8 }, { priorityOrder: 4 }),
      X: route("hitch", { depth: 8 }, { priorityOrder: 5 }),
    },
    tags: ["spacing", "empty", "quick", "zone-beater", "rush-beater"],
    situations: ["3rd-short", "blitz-beater", "backed-up", "two-minute"],
    coaching: {
      install: "Five receivers spread evenly across the width, all at five to eight yards. Throw to whichever one is uncovered.",
      keys: "The ball comes out on the third step every time.",
    },
  }),
];
