/**
 * Air Raid.
 *
 * A concept-number system: the number names a whole five-man concept, not a
 * single route. Base look is 2x2 out of gun with X and H to one side, Y and Z
 * to the other, and F as the back — note that F is the RUNNING BACK in Air Raid
 * books, which collides with the pro-style fullback and is why the search facet
 * folds both onto FV.
 *
 * Screens carry names rather than numbers, alliterated by side, which is a real
 * convention and not a joke: Randy right, Larry left, Rita right, Lisa left.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { opt, pass, play, route } from "../kit.ts";

const AR = ["11man", "7man"] as const;

export const AIR_RAID: PlaySpec[] = [
  play({
    id: "ar-6-four-verticals",
    name: "6 — Four Verticals",
    aliases: ["Four Verts", "6", "Verts"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "four-verticals",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Y", "H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("go"),
      Z: route("go"),
      Y: route("seam", { landmark: "hash" }, { priorityOrder: 1 }),
      H: route("seam", { landmark: "hash" }, { priorityOrder: 2 }),
      RB: route("checkdown", undefined, { startDelayMs: 300, priorityOrder: 4 }),
    },
    tags: ["verticals", "shot", "seam", "hash-landmark"],
    situations: ["1st-down", "2nd-long", "3rd-long", "vs-cover-3", "vs-cover-1", "two-minute"],
    coaching: {
      keys: "Count the safeties. One high, throw the seam away from the free safety; two high, hunt the hash.",
      vsCoverage: "Cover 3 dies on the seams. Quarters wants the back or a scramble.",
      commentary: "Four receivers running vertical stretches every deep defender at once and asks the quarterback one question.",
    },
  }),

  play({
    id: "ar-618-stick",
    name: "618 — Stick",
    aliases: ["Stick", "618", "Y-Stick"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "stick",
    primary: "Y",
    reads: [
      { order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "RB", "H"] },
    ],
    assignments: {
      QB: pass("gun-quick"),
      X: route("slant", undefined, { priorityOrder: 3 }),
      H: route("slant", undefined, { priorityOrder: 4 }),
      Y: opt("stick", "flat-defender", [
        { when: "expands", route: "stick", mods: { settleYd: 1 } },
        { when: "squeezes", route: "out", mods: { depth: 6 } },
      ], { depth: 6 }),
      Z: route("go"),
      RB: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
    },
    tags: ["stick", "quick-game", "triangle", "high-low"],
    situations: ["3rd-short", "3rd-medium", "1st-down", "red-zone", "vs-zone", "blitz-beater"],
    coaching: {
      keys: "Read the flat defender. He widens with the back, throw the stick; he sits on the stick, throw the flat.",
      commentary: "The most-called play in the system. Two defenders, three receivers, and the quarterback only has to be right about one man.",
    },
  }),

  play({
    id: "ar-617-quick-out",
    name: "617 — Quick Out",
    aliases: ["617", "Speed Out"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "quick-out",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["H", "Z", "Y"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: route("slant", undefined, { priorityOrder: 3 }),
      H: route("out", { depth: 5 }, { priorityOrder: 1 }),
      Y: route("slant", undefined, { priorityOrder: 4 }),
      Z: route("out", { depth: 5 }, { priorityOrder: 2 }),
      RB: route("checkdown", undefined, { startDelayMs: 250 }),
    },
    tags: ["quick-game", "three-step", "outbreaking", "rhythm"],
    situations: ["1st-down", "2nd-short", "3rd-short", "sideline", "vs-zone"],
    coaching: { keys: "Off coverage takes the out. Press takes the slant behind it." },
  }),

  play({
    id: "ar-8-y-corner",
    name: "8 — Y-Corner",
    aliases: ["Y-Corner", "8", "Snag"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-bunch-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "snag",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("hitch", { depth: 6 }, { priorityOrder: 2 }),
      Y: route("corner", { depth: 14 }, { priorityOrder: 1 }),
      H: route("arrow", { toSide: "R" }, { priorityOrder: 3 }),
      X: route("slant"),
      RB: route("checkdown", undefined, { startDelayMs: 280, priorityOrder: 4 }),
    },
    tags: ["snag", "bunch", "triangle", "corner", "rub"],
    situations: ["red-zone", "3rd-medium", "vs-cover-1", "vs-man", "goal-line"],
    coaching: {
      keys: "The corner is first if the safety is late. Otherwise it is a hitch-flat triangle on the corner.",
      commentary: "A bunch makes the rub happen without anybody having to run into anybody.",
    },
  }),

  play({
    id: "ar-66-hitch-seam",
    name: "66 — Hitch Seam",
    aliases: ["66", "Hitch-Seam", "Slot Fade"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "hitch-seam",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "Y", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: route("hitch", { depth: 5 }, { priorityOrder: 3 }),
      Z: route("hitch", { depth: 5 }, { priorityOrder: 1 }),
      Y: route("seam", undefined, { priorityOrder: 2 }),
      H: route("seam", undefined, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 250 }),
    },
    tags: ["quick-game", "hitch", "seam", "press-beater"],
    situations: ["1st-down", "2nd-short", "vs-zone", "vs-cover-3"],
    coaching: { keys: "Off coverage, take the hitch on rhythm. Press or Cover 0, throw the pressed slot vertical." },
  }),

  play({
    id: "ar-91-shallow-cross",
    name: "91 — Shallow Cross",
    aliases: ["91", "Shallow", "Drive"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "half-slide",
    concept: "shallow-cross",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["X", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("shallow", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("dig", { depth: 10 }, { priorityOrder: 2 }),
      H: route("go"),
      Z: route("go"),
      RB: route("flat", { toSide: "L" }, { startDelayMs: 220, priorityOrder: 3 }),
    },
    tags: ["shallow", "crosser", "man-beater", "high-low", "drive"],
    situations: ["3rd-medium", "3rd-long", "1st-down", "vs-man", "vs-cover-1", "blitz-beater"],
    coaching: {
      keys: "Shallow to dig, high-low on the middle linebacker. Against man the shallow keeps running.",
      commentary: "Two in-breaking routes at two depths on one defender. He is wrong either way.",
    },
  }),

  play({
    id: "ar-92-mesh",
    name: "92 — Mesh",
    aliases: ["Mesh", "92"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "slide-right",
    concept: "mesh",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Z", "Y", "H", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("corner", { depth: 10 }, { priorityOrder: 1 }),
      Y: opt("shallow", "man-or-zone", [
        { when: "zone", route: "shallow", mods: { settleYd: 2 } },
        { when: "man", route: "shallow" },
      ], { toSide: "L", meshWith: "H", meshDepthYd: 5, lane: "over" }),
      H: opt("shallow", "man-or-zone", [
        { when: "zone", route: "shallow", mods: { settleYd: 2 } },
        { when: "man", route: "shallow" },
      ], { toSide: "R", meshWith: "Y", meshDepthYd: 5, lane: "under" }),
      X: route("dig", { depth: 12 }, { priorityOrder: 3 }),
      RB: route("swing", { toSide: "R" }, { startDelayMs: 250, priorityOrder: 4 }),
    },
    tags: ["mesh", "rub", "man-beater", "quick-game", "signature"],
    situations: ["1st-down", "3rd-medium", "red-zone", "blitz-beater", "vs-man", "vs-cover-1"],
    coaching: {
      keys: "Corner first against single high. If the flat defender widens, the shallows sit down.",
      vsCoverage: "Cover 1, run through the mesh. Cover 3, sit at five or six between the hooks.",
      commentary: "The whole offense in one play: two shallows rubbing, a corner over the top, a swing to the field.",
    },
  }),

  play({
    id: "ar-93-h-wheel",
    name: "93 — H Wheel",
    aliases: ["93", "Wheel", "H-Wheel"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "wheel",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "SS", progression: ["Z", "X", "H", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("curl", { depth: 15 }, { priorityOrder: 2 }),
      H: route("wheel", undefined, { priorityOrder: 3 }),
      Y: route("hitch", { depth: 6 }, { priorityOrder: 4 }),
      Z: route("post", { depth: 12 }, { priorityOrder: 1 }),
      RB: route("swing", { toSide: "L" }, { startDelayMs: 260 }),
    },
    tags: ["wheel", "post", "man-beater", "shot"],
    situations: ["2nd-long", "3rd-long", "vs-man", "vs-cover-1", "plus-territory"],
    coaching: { keys: "Post first, then the mandatory fifteen-yard curl, then the wheel up the sideline." },
  }),

  play({
    id: "ar-94-deep-out",
    name: "94 — Deep Out",
    aliases: ["94", "Texas", "Deep Out"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "half-slide",
    concept: "deep-out",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "OLB", progression: ["X", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("dig", { depth: 12 }, { priorityOrder: 1 }),
      H: route("whip", undefined, { priorityOrder: 3 }),
      Y: route("out", { depth: 12 }, { priorityOrder: 2 }),
      Z: route("go"),
      RB: route("texas", undefined, { startDelayMs: 240, priorityOrder: 4 }),
    },
    tags: ["deep-out", "texas", "whip", "intermediate"],
    situations: ["3rd-medium", "3rd-long", "sideline", "vs-zone", "blitz-beater"],
    coaching: { keys: "The Texas route by the back is the hot answer against pressure. Everything else is on rhythm." },
  }),

  play({
    id: "ar-95-y-cross",
    name: "95 — Y-Cross",
    aliases: ["95", "Y-Cross", "Cross"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "y-cross",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["Z", "H", "Y", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", undefined, { priorityOrder: 1 }),
      H: route("out", { depth: 8 }, { priorityOrder: 2 }),
      Y: route("drag", { toSide: "R", depthAdj: 6 }, { priorityOrder: 3 }),
      X: route("post", { depth: 12 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["cross", "deep-crosser", "man-beater", "levels"],
    situations: ["2nd-long", "3rd-long", "vs-man", "vs-cover-3", "plus-territory"],
    coaching: {
      keys: "Under the outside backer, over the Mike, under the weak safety. The ball comes out on time, off the drop.",
    },
  }),

  play({
    id: "ar-96-all-curl",
    name: "96 — All Curl",
    aliases: ["96", "Curls", "All Curl"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "curl",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["X", "Z", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("curl", { depth: 15 }, { priorityOrder: 1 }),
      Z: route("curl", { depth: 15 }, { priorityOrder: 2 }),
      Y: route("curl", { depth: 8 }, { priorityOrder: 3 }),
      H: route("bubble", undefined, { priorityOrder: 5 }),
      RB: route("swing", { toSide: "R" }, { startDelayMs: 260, priorityOrder: 4 }),
    },
    tags: ["curl", "zone-beater", "settle", "rhythm"],
    situations: ["3rd-medium", "3rd-long", "vs-cover-2", "vs-zone", "two-minute"],
    coaching: { keys: "Find the window between the corner and the flat defender and sit in it." },
  }),

  play({
    id: "ar-98-double-smash",
    name: "98 — Double Smash",
    aliases: ["98", "Smash", "Double Smash"],
    philosophy: "air-raid",
    family: "pass",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "big-on-big",
    concept: "smash",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Y", "Z", "H", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("hitch", { depth: 5 }, { priorityOrder: 4 }),
      Z: route("hitch", { depth: 5 }, { priorityOrder: 2 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 1 }),
      H: route("corner", { depth: 12 }, { priorityOrder: 3 }),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["smash", "high-low", "corner", "hitch", "mirrored"],
    situations: ["red-zone", "3rd-medium", "vs-cover-2", "vs-zone", "sideline"],
    coaching: {
      keys: "High-low the corner on both sides. Pick the softer one before the snap and confirm it after.",
      commentary: "Mirroring the concept means the quarterback never has a wrong side to look at.",
    },
  }),

  play({
    id: "ar-randy-screen",
    name: "Randy — WR Screen",
    aliases: ["Randy", "Now Screen", "Quick Screen"],
    philosophy: "air-raid",
    family: "screen",
    variantScope: [...AR],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "screen-release",
    concept: "wr-screen",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("screen", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("stalk"),
      H: route("stalk"),
      X: route("go"),
      RB: route("checkdown", undefined, { startDelayMs: 200 }),
    },
    tags: ["screen", "perimeter", "numbers", "space"],
    situations: ["1st-down", "2nd-short", "backed-up", "vs-zone"],
    coaching: { keys: "Count the box. If they are light outside, this is a run call that happens to be a throw." },
  }),

  play({
    id: "ar-rita-tunnel",
    name: "Rita — Tunnel Screen",
    aliases: ["Rita", "Tunnel", "Slow Screen"],
    philosophy: "air-raid",
    family: "screen",
    variantScope: [...AR],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "screen-release",
    concept: "tunnel-screen",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("pivot", { toSide: "L", depth: 1 }, { startDelayMs: 200, priorityOrder: 1 }),
      Y: route("wall", { toSide: "R" }),
      H: route("wall", { toSide: "R" }),
      X: route("go"),
      RB: route("checkdown", undefined, { startDelayMs: 260 }),
    },
    tags: ["screen", "tunnel", "delayed", "wall"],
    situations: ["2nd-long", "3rd-long", "vs-man", "blitz-beater"],
    coaching: {
      keys: "Sell the fade for one step, then work back inside behind the wall.",
      commentary: "Against a corner who has been beaten deep twice, this is the third-down answer.",
    },
  }),
];
