/**
 * Defense — a peer library, not an overlay.
 *
 * A defensive play names a front, a coverage, and optionally a pressure. All
 * three are objects in their own right, so a coach can put Cover 3 behind four
 * different fronts without redrawing anything, which is exactly how a defensive
 * staff actually installs.
 *
 * Two things worth stating because the diagrams depend on them: the number in
 * "Cover N" is the count of defenders with deep responsibility, and receivers
 * are numbered from the sideline in, because coverage rules are written that
 * way ("carry number two vertical", "expand to number one").
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { play } from "../kit.ts";

/** A defensive play carries no per-slot assignments — the front, the coverage
 *  and the pressure supply every path it needs. */
const def = (p: Omit<Parameters<typeof play>[0], "assignments" | "side">): PlaySpec =>
  play({ ...p, side: "defense", assignments: {} });

export const DEFENSE: PlaySpec[] = [
  // ── four-down base ───────────────────────────────────────────────────────
  def({
    id: "d-over-cover-3",
    name: "Over Cover 3",
    aliases: ["Base 3", "Over Sky", "4-3 Cover 3"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "cover-3",
    tags: ["base", "single-high", "run-support", "four-down"],
    situations: ["1st-down", "2nd-short", "short-yardage", "four-minute"],
    coaching: {
      install: "Three deep, four under. The extra man in the box shows up in the run fit, which is the whole reason to play it.",
      keys: "Corners bail to the deep third at the snap. The curl-flat defenders expand with number two.",
      commentary: "Vulnerable to four verticals on the seams and to a well-timed flood.",
    },
  }),
  def({
    id: "d-over-cover-1",
    name: "Over Cover 1",
    aliases: ["Man Free", "Over Man", "1 Robber"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "cover-1",
    tags: ["man", "single-high", "match", "four-down"],
    situations: ["3rd-medium", "3rd-long", "red-zone", "must-score"],
    coaching: {
      keys: "Man across the board with a free safety in the deep middle and a rat in the hole.",
      commentary: "Loses to a mesh and to any crossing concept that generates a legal rub.",
    },
  }),
  def({
    id: "d-over-cover-2",
    name: "Over Cover 2",
    aliases: ["Two Deep", "Over Two"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "cover-2",
    tags: ["zone", "two-high", "squat-corners", "four-down"],
    situations: ["2nd-long", "3rd-long", "sideline", "two-minute"],
    coaching: {
      keys: "Corners squat and re-route number one. Safeties split the field in half.",
      commentary: "The seam and the deep middle hole are where it dies, which is what Tampa 2 exists to fix.",
    },
  }),
  def({
    id: "d-over-tampa-2",
    name: "Tampa 2",
    aliases: ["Tampa", "2 Runner"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "tampa-2",
    tags: ["zone", "two-high", "seam-answer", "four-down"],
    situations: ["2nd-long", "3rd-long", "two-minute", "must-score"],
    coaching: {
      keys: "The Mike runs the deep middle to about twenty and takes the seam away.",
      commentary: "Costs you a run defender in the box to buy the middle of the field.",
    },
  }),
  def({
    id: "d-over-cover-4",
    name: "Over Quarters",
    aliases: ["Quarters", "Cover 4", "Match Quarters"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "cover-4",
    tags: ["zone", "match", "two-high", "pattern-read"],
    situations: ["1st-down", "2nd-long", "vs-zone", "plus-territory"],
    coaching: {
      keys: "Played as a pattern match. Safeties become run defenders the moment number two goes flat.",
      commentary: "Nine in the box against a run and two-high against a pass, if the safeties read it right.",
    },
  }),

  // ── nickel ───────────────────────────────────────────────────────────────
  def({
    id: "d-nickel-cover-3",
    name: "Nickel Cover 3",
    aliases: ["Nickel 3", "4-2-5 Sky"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-3",
    tags: ["nickel", "single-high", "spread-answer"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: { keys: "Five defensive backs against eleven personnel. The nickel plays the curl-flat to the field." },
  }),
  def({
    id: "d-nickel-cover-4",
    name: "Nickel Quarters",
    aliases: ["Nickel 4", "4-2-5 Quarters"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-4",
    tags: ["nickel", "match", "two-high", "spread-answer"],
    situations: ["1st-down", "2nd-long", "plus-territory"],
    coaching: { keys: "The base call against a spread offense on early downs." },
  }),
  def({
    id: "d-nickel-cover-2-man",
    name: "Nickel 2 Man",
    aliases: ["2 Man Under", "Cover 5"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-2-man",
    tags: ["man", "two-high", "trail-technique", "nickel"],
    situations: ["3rd-long", "2nd-long", "must-score"],
    coaching: {
      keys: "Trail technique underneath with two-deep help over the top.",
      commentary: "The safest man call, and the one that gives up the most underneath.",
    },
  }),
  def({
    id: "d-nickel-cover-6",
    name: "Nickel Cover 6",
    aliases: ["Cover 6", "Quarter Quarter Half"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-6",
    tags: ["split-field", "boundary", "zone", "nickel"],
    situations: ["1st-down", "2nd-long", "backed-up", "sideline"],
    coaching: {
      keys: "Quarters to the field, Cover 2 to the boundary. Four plus two is six.",
      commentary: "A hash-dependent call. It stops being clever when the ball is in the middle of the field.",
    },
  }),

  // ── odd fronts ───────────────────────────────────────────────────────────
  def({
    id: "d-odd-cover-3",
    name: "3-4 Cover 3",
    aliases: ["Okie 3", "Odd 3"],
    philosophy: "defense-front",
    family: "front",
    variantScope: ["11man"],
    formationId: "",
    frontId: "odd-3-4",
    coverageId: "cover-3",
    tags: ["three-down", "odd", "two-gap", "single-high"],
    situations: ["1st-down", "short-yardage", "four-minute"],
    coaching: { install: "Three down linemen two-gapping so four linebackers can play free." },
  }),
  def({
    id: "d-stack-cover-3",
    name: "3-3-5 Cover 3",
    aliases: ["Stack 3", "Double Eagle"],
    philosophy: "defense-front",
    family: "front",
    variantScope: ["11man"],
    formationId: "",
    frontId: "odd-3-3-5",
    coverageId: "cover-3",
    tags: ["three-down", "stack", "multiple", "disguise"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: {
      install: "Stacked linebackers make the front unreadable before the snap.",
      commentary: "The whole point is that the offense cannot count the box until the ball moves.",
    },
  }),
  def({
    id: "d-goal-line",
    name: "Goal Line 6-2",
    aliases: ["Goal Line", "Bear", "6-2"],
    philosophy: "defense-front",
    family: "front",
    variantScope: ["11man"],
    formationId: "",
    frontId: "goal-line-6-2",
    coverageId: "cover-1",
    tags: ["goal-line", "heavy", "short-yardage", "man"],
    situations: ["goal-line", "short-yardage", "4th-short", "red-zone"],
    coaching: {
      install: "Six on the line, everybody in a gap, man behind it.",
      commentary: "One play-action away from a walk-in touchdown, which is the trade you accept on the two-yard line.",
    },
  }),

  // ── pressures ────────────────────────────────────────────────────────────
  def({
    id: "d-fire-zone-sam",
    name: "Fire Zone Sam",
    aliases: ["Sam Fire", "Zone Blitz Strong"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "cover-3",
    pressureId: "fire-zone-sam",
    tags: ["five-man", "zone-blitz", "three-under-three-deep", "pressure"],
    situations: ["3rd-medium", "3rd-long", "2nd-long"],
    coaching: {
      keys: "Five rush, three under, three deep. The end drops into the vacated curl.",
      commentary: "Pressure without gambling the deep part of the field.",
    },
  }),
  def({
    id: "d-double-a-mug",
    name: "Double A Mug",
    aliases: ["Double A", "Mugged A Gaps"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-1",
    pressureId: "double-a-mug",
    tags: ["six-man", "interior", "man-free", "pressure", "disguise"],
    situations: ["3rd-medium", "3rd-long", "red-zone"],
    coaching: {
      keys: "Both linebackers walk up into the A gaps. Whether they come is decided after the centre declares.",
      commentary: "Half the value is that the offense has to slide protection before it knows anything.",
    },
  }),
  def({
    id: "d-nickel-fire",
    name: "Nickel Fire",
    aliases: ["Star Blitz", "Slot Pressure"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-1",
    pressureId: "nickel-fire",
    tags: ["five-man", "edge", "slot-pressure", "pressure"],
    situations: ["3rd-medium", "2nd-long", "vs-zone"],
    coaching: { keys: "The nickel comes off the slot's outside shoulder, which nobody in the protection is assigned to." },
  }),
  def({
    id: "d-safety-green-dog",
    name: "Safety Green Dog",
    aliases: ["SS Fire", "Safety Blitz"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "cover-3",
    pressureId: "safety-green-dog",
    tags: ["five-man", "delayed", "disguise", "pressure"],
    situations: ["3rd-medium", "1st-down", "red-zone"],
    coaching: { keys: "Two-high shell before the snap, one-high after it, and the strong safety arrives late." },
  }),
  def({
    id: "d-cover-0-max",
    name: "Cover 0 Max",
    aliases: ["Zero Blitz", "All Out"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-0",
    pressureId: "cover-0-max",
    tags: ["seven-man", "all-out", "no-help", "pressure"],
    situations: ["4th-short", "goal-line", "must-score", "short-yardage"],
    coaching: {
      keys: "Everybody not covering somebody is coming. There is no help anywhere.",
      commentary: "A hot route or a slant beats it every time, so call it when the offense has no time to find one.",
    },
  }),

  // ── 7-on-7 ───────────────────────────────────────────────────────────────
  def({
    id: "d-7v7-cover-3",
    name: "7v7 Cover 3",
    aliases: ["Base 3", "Three Deep"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["7man"],
    formationId: "",
    frontId: "seven-3-2-2",
    coverageId: "cover-3",
    tags: ["7v7", "single-high", "zone"],
    situations: ["1st-down", "2nd-short"],
    coaching: { keys: "Three deep, everyone else underneath. The base call in most passing leagues." },
  }),
  def({
    id: "d-7v7-cover-2",
    name: "7v7 Cover 2",
    aliases: ["Two Deep", "7v7 Two"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["7man"],
    formationId: "",
    frontId: "seven-3-2-2",
    coverageId: "cover-2",
    tags: ["7v7", "two-high", "zone"],
    situations: ["2nd-long", "3rd-long", "sideline"],
    coaching: { keys: "Two halves over the top. Corners take the flat and re-route the outside receiver." },
  }),
  def({
    id: "d-7v7-cover-1",
    name: "7v7 Man Free",
    aliases: ["Cover 1", "Man Free"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["7man"],
    formationId: "",
    frontId: "seven-3-2-2",
    coverageId: "cover-1",
    tags: ["7v7", "man", "single-high"],
    situations: ["3rd-medium", "red-zone", "must-score"],
    coaching: { commentary: "With no rush, man coverage in 7v7 is a test of how long a defender can run." },
  }),

  // ── flag ─────────────────────────────────────────────────────────────────
  def({
    id: "d-flag-cover-3",
    name: "Flag Cover 3",
    aliases: ["Three Deep", "Base"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["5flag"],
    formationId: "",
    frontId: "flag-1-rush",
    coverageId: "cover-3",
    tags: ["flag", "zone", "single-high", "one-rusher"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: {
      keys: "One rusher from seven yards, three underneath, one deep.",
      commentary: "The safest call in flag, and the reason curls and sticks exist.",
    },
  }),
  def({
    id: "d-flag-cover-1",
    name: "Flag Man Free",
    aliases: ["Cover 1", "Man"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["5flag"],
    formationId: "",
    frontId: "flag-1-rush",
    coverageId: "cover-1",
    tags: ["flag", "man", "single-high", "one-rusher"],
    situations: ["3rd-medium", "red-zone", "goal-line"],
    coaching: {
      keys: "Everyone has a man, one safety helps deep. Watch the crossers.",
      commentary: "Mesh and Quick Cross are designed specifically to beat this.",
    },
  }),
  def({
    id: "d-flag-cover-0",
    name: "Flag Zero",
    aliases: ["Cover 0", "All Man"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["5flag"],
    formationId: "",
    frontId: "flag-1-rush",
    coverageId: "cover-0",
    pressureId: "flag-corner-fire",
    tags: ["flag", "man", "blitz", "no-help"],
    situations: ["4th-short", "goal-line", "must-score", "short-yardage"],
    coaching: {
      keys: "Two rushers, everyone else in man with no safety.",
      commentary: "Quick slants beat it. Call it when the offense has to go deep anyway.",
    },
  }),
  def({
    id: "d-flag-drop-four",
    name: "Flag Zero Rush",
    aliases: ["Drop Everyone", "No Rush"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["5flag"],
    formationId: "",
    frontId: "flag-0-rush",
    coverageId: "cover-2",
    tags: ["flag", "zone", "no-rush", "two-high", "prevent"],
    situations: ["two-minute", "2nd-long", "3rd-long", "backed-up"],
    coaching: {
      keys: "Nobody rushes. Five defenders cover three receivers and wait for the seven-second clock.",
      commentary: "The clock is the pass rush. Against a quarterback who holds it, this is a sack every time.",
    },
  }),
  // ── under and bear ───────────────────────────────────────────────────────
  def({
    id: "d-under-cover-3",
    name: "Under Cover 3",
    aliases: ["Under Sky", "Base Under"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "under-4-3",
    coverageId: "cover-3",
    tags: ["base", "single-high", "run-front", "four-down"],
    situations: ["1st-down", "2nd-short", "short-yardage"],
    coaching: {
      install: "The line shifts away from the tight end and the Sam walks up on him. Every gap is accounted for without a safety in the box.",
      keys: "Sam sets the edge to the tight end. Will is free to run to the ball.",
    },
  }),
  def({
    id: "d-under-cover-1",
    name: "Under Cover 1",
    aliases: ["Under Man", "Eagle Man"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "under-4-3",
    coverageId: "cover-1",
    tags: ["man", "single-high", "four-down", "tight-end-answer"],
    situations: ["3rd-medium", "red-zone", "goal-line"],
    coaching: {
      keys: "Sam takes the tight end from a head-up alignment. Everyone else plays man with a free safety over the top.",
      commentary: "The best call in the book against a heavy set that wants to throw to the tight end.",
    },
  }),
  def({
    id: "d-under-palms",
    name: "Under Palms",
    aliases: ["Under 2 Read", "Under Trap"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "under-4-3",
    coverageId: "palms",
    tags: ["zone", "match", "two-high", "quick-game-answer"],
    situations: ["1st-down", "2nd-long", "vs-zone"],
    coaching: {
      install: "Quarters rules until number two breaks to the flat. Then the corner comes off number one and traps him.",
      keys: "The safety takes number one vertical the moment the corner triggers.",
      commentary: "This is the answer to a team living on bubbles and quick outs.",
    },
  }),
  def({
    id: "d-bear-cover-1",
    name: "Bear Cover 1",
    aliases: ["46 Man", "Bear Man"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "bear-46",
    coverageId: "cover-1",
    tags: ["man", "bear-front", "run-stopper", "short-yardage"],
    situations: ["3rd-short", "4th-short", "goal-line", "short-yardage"],
    coaching: {
      install: "Three interior linemen covering both guards and the centre. Nobody inside gets a free release to the second level.",
      commentary: "Built for a team that wants to run inside zone at you all afternoon.",
    },
  }),
  def({
    id: "d-bear-mug",
    name: "Bear Mug",
    aliases: ["46 Mug", "Bear Pressure"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "bear-46",
    coverageId: "cover-1",
    pressureId: "bear-mug",
    tags: ["six-man", "bear-front", "interior", "man-free"],
    situations: ["3rd-short", "goal-line", "short-yardage", "blitz-beater"],
    coaching: {
      keys: "Six rushers against five blockers. One of them comes free and the ball has to be out before he arrives.",
      commentary: "The quarterback's hot answer has to be built in, because the protection cannot hold this.",
    },
  }),

  // ── eight in the box ─────────────────────────────────────────────────────
  def({
    id: "d-44-cover-3",
    name: "4-4 Cover 3",
    aliases: ["44 Sky", "Eight Man Box"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "even-4-4",
    coverageId: "cover-3",
    tags: ["base", "eight-in-the-box", "run-support", "youth"],
    situations: ["1st-down", "short-yardage", "four-minute", "goal-line"],
    coaching: {
      install: "Four down, four linebackers, three deep. Every gap has a defender before the ball is snapped.",
      commentary: "Common at the youth and small-school level for a reason: it stops the run without asking anybody to think.",
    },
  }),
  def({
    id: "d-44-cover-1",
    name: "4-4 Cover 1",
    aliases: ["44 Man", "Eight Man Man"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "even-4-4",
    coverageId: "cover-1",
    tags: ["man", "eight-in-the-box", "single-high"],
    situations: ["3rd-short", "goal-line", "red-zone", "vs-man"],
    coaching: { keys: "Outside linebackers carry the backs. Everything else is man with a free safety in the middle." },
  }),
  def({
    id: "d-44-double-edge",
    name: "4-4 Double Edge",
    aliases: ["44 Fire", "Both Edges"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "even-4-4",
    coverageId: "cover-3",
    pressureId: "double-edge-fire",
    tags: ["six-man", "edge", "contain", "run-blitz"],
    situations: ["2nd-short", "3rd-short", "short-yardage"],
    coaching: {
      keys: "Both outside linebackers come off the edge and squeeze everything back inside to the pursuit.",
      commentary: "Vulnerable to anything that gets outside them, which is why it is a down-and-distance call.",
    },
  }),

  // ── dime and wide nine ───────────────────────────────────────────────────
  def({
    id: "d-dime-cover-2-man",
    name: "Dime 2 Man",
    aliases: ["Dime Two Man", "Six DB Man"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "dime-4-1-6",
    coverageId: "cover-2-man",
    tags: ["man", "dime", "two-high", "obvious-pass"],
    situations: ["3rd-long", "2nd-long", "two-minute", "must-score"],
    coaching: {
      keys: "Trail technique underneath with two safeties over the top. Nothing goes over anybody's head.",
      commentary: "Concedes the check-down and takes away everything past ten yards.",
    },
  }),
  def({
    id: "d-dime-tampa-2",
    name: "Dime Tampa 2",
    aliases: ["Dime Tampa", "Six DB Tampa"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "dime-4-1-6",
    coverageId: "tampa-2",
    tags: ["zone", "dime", "two-high", "seam-answer"],
    situations: ["3rd-long", "two-minute", "must-score", "vs-zone"],
    coaching: { keys: "The Mike runs the deep middle to twenty. The two safeties play true halves behind him." },
  }),
  def({
    id: "d-dime-cover-1-bracket",
    name: "Dime Bracket",
    aliases: ["Double the Best", "Bracket X"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "dime-4-1-6",
    coverageId: "cover-1-bracket",
    tags: ["man", "bracket", "take-away-one", "dime"],
    situations: ["3rd-long", "must-score", "two-minute", "vs-man"],
    coaching: {
      install: "Two defenders on their best receiver, one under and one over. Everyone else is on an island.",
      commentary: "The call for a team with one player who beats you and four who do not.",
    },
  }),
  def({
    id: "d-wide-9-cover-4",
    name: "Wide 9 Quarters",
    aliases: ["Nascar Quarters", "Speed Front Four"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "wide-9",
    coverageId: "cover-4",
    tags: ["zone", "pass-rush", "two-high", "third-down"],
    situations: ["2nd-long", "3rd-long", "vs-zone"],
    coaching: {
      keys: "Both ends rush from outside the tight end, so the quarterback's edge disappears before his third step.",
      commentary: "Wide alignment gives up the inside run, which is the trade you accept on an obvious passing down.",
    },
  }),
  def({
    id: "d-wide-9-robber",
    name: "Wide 9 Robber",
    aliases: ["Nascar Robber", "Rat Coverage"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "wide-9",
    coverageId: "cover-4-robber",
    tags: ["zone", "robber", "dig-answer", "match"],
    situations: ["3rd-medium", "2nd-long", "vs-cover-1", "vs-zone"],
    coaching: { keys: "The robber sits at ten in the middle of the field and takes the first crosser he sees." },
  }),
  def({
    id: "d-nickel-cross-dog",
    name: "Nickel Cross Dog",
    aliases: ["X Blitz", "Cross Fire"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-1",
    pressureId: "cross-dog",
    tags: ["six-man", "interior", "man-free", "crossing-rushers"],
    situations: ["3rd-medium", "3rd-long", "blitz-beater"],
    coaching: {
      install: "Both linebackers mug the A gaps and cross on the snap, so the centre has to pick one and guess.",
      keys: "The second rusher through is the one who gets home.",
    },
  }),
  def({
    id: "d-nickel-double",
    name: "Nickel Double",
    aliases: ["Star Mike", "Double Nickel"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-0",
    pressureId: "nickel-double",
    tags: ["six-man", "slot-pressure", "no-help", "third-down"],
    situations: ["3rd-long", "must-score", "vs-cover-0", "blitz-beater"],
    coaching: {
      commentary: "Six rushers with no safety help. It ends the drive or it ends the game.",
    },
  }),
  def({
    id: "d-corner-cat",
    name: "Corner Cat",
    aliases: ["Corner Blitz", "Boundary Fire"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "nickel-4-2-5",
    coverageId: "cover-3-cloud",
    pressureId: "corner-cat",
    tags: ["five-man", "corner", "disguise", "boundary"],
    situations: ["2nd-short", "3rd-short", "sideline", "backed-up"],
    coaching: {
      keys: "The corner comes off the boundary edge and the safety rotates over the top to replace him.",
      commentary: "Time it to a formation into the boundary and the back has nobody to pick up.",
    },
  }),
  def({
    id: "d-weak-fire-zone",
    name: "Fire Zone Will",
    aliases: ["Will Fire", "Zone Blitz Weak"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "cover-3",
    pressureId: "weak-fire-zone",
    tags: ["five-man", "zone-blitz", "backside", "three-under-three-deep"],
    situations: ["2nd-long", "3rd-medium", "vs-zone"],
    coaching: {
      install: "Five rush, three under, three deep. The end who drops is the one the protection counted on rushing.",
      keys: "Pressure from the backside meets a quarterback who is looking the other way.",
    },
  }),
  def({
    id: "d-over-cover-3-buzz",
    name: "Over Cover 3 Buzz",
    aliases: ["Buzz", "Late Rotation"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "over-4-3",
    coverageId: "cover-3-buzz",
    tags: ["zone", "single-high", "disguise", "run-support"],
    situations: ["1st-down", "2nd-short", "vs-cover-2", "opening-script"],
    coaching: {
      install: "Show two high, roll late. The strong safety buzzes to a hook and the free safety takes the middle third.",
      commentary: "The picture the quarterback saw pre-snap is gone by the time he finishes his drop.",
    },
  }),
  def({
    id: "d-odd-palms",
    name: "Odd Palms",
    aliases: ["3-4 Read", "Odd Trap"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "odd-3-4",
    coverageId: "palms",
    tags: ["zone", "match", "three-down", "quick-game-answer"],
    situations: ["1st-down", "2nd-long", "vs-zone"],
    coaching: { keys: "Three down linemen two-gap while the corners trap anything that shows in the flat." },
  }),
  def({
    id: "d-stack-cover-4-robber",
    name: "Stack Robber",
    aliases: ["3-3-5 Robber", "Stack Rat"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["11man"],
    formationId: "",
    frontId: "odd-3-3-5",
    coverageId: "cover-4-robber",
    tags: ["zone", "robber", "three-down", "spread-answer"],
    situations: ["2nd-long", "3rd-medium", "vs-zone", "vs-cover-1"],
    coaching: {
      commentary: "Built for spread teams: five defensive backs, a robber in the middle, and enough bodies to still fit the run.",
    },
  }),

  // ── seven on seven ───────────────────────────────────────────────────────
  def({
    id: "d-7v7-palms",
    name: "7v7 Palms",
    aliases: ["7v7 2 Read", "Trap Coverage"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["7man"],
    formationId: "",
    frontId: "seven-2-2-3",
    coverageId: "palms",
    tags: ["7v7", "zone", "match", "quick-game-answer"],
    situations: ["1st-down", "3rd-medium", "vs-zone"],
    coaching: { keys: "Corners trap number two in the flat. Safeties take number one whenever that happens." },
  }),
  def({
    id: "d-7v7-cover-3-cloud",
    name: "7v7 Cloud",
    aliases: ["7v7 Corner Roll", "Cloud"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["7man"],
    formationId: "",
    frontId: "seven-2-2-3",
    coverageId: "cover-3-cloud",
    tags: ["7v7", "zone", "single-high", "flat-support"],
    situations: ["3rd-short", "sideline", "vs-zone"],
    coaching: { keys: "The corner squats on the flat and the safety takes his third." },
  }),
  def({
    id: "d-7v7-bracket",
    name: "7v7 Bracket",
    aliases: ["Double Their Best", "7v7 Double"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["7man"],
    formationId: "",
    frontId: "seven-3-2-2",
    coverageId: "cover-1-bracket",
    tags: ["7v7", "man", "bracket", "take-away-one"],
    situations: ["3rd-long", "must-score", "vs-man"],
    coaching: {
      commentary: "Seven-on-seven is where one receiver can decide a whole tournament. Put two on him.",
    },
  }),

  // ── flag ─────────────────────────────────────────────────────────────────
  def({
    id: "d-flag-cover-2",
    name: "Flag Cover 2",
    aliases: ["Two Deep", "Split Safety"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["5flag"],
    formationId: "",
    frontId: "flag-1-rush",
    coverageId: "flag-cover-2",
    tags: ["flag", "zone", "two-high", "deep-ball-answer"],
    situations: ["2nd-long", "must-score", "two-minute", "vs-man"],
    coaching: {
      install: "Two deep halves and one underneath. Nothing gets over the top and everything short is open.",
      commentary: "Call it when they only need a big play, which in flag is most of the fourth quarter.",
    },
  }),
  def({
    id: "d-flag-press-man",
    name: "Flag Press Man",
    aliases: ["Press Bail", "Bump and Run"],
    philosophy: "defense-coverage",
    family: "coverage",
    variantScope: ["5flag"],
    formationId: "",
    frontId: "flag-press",
    coverageId: "cover-1",
    tags: ["flag", "man", "press", "timing-disruption"],
    situations: ["3rd-short", "goal-line", "red-zone", "vs-man"],
    coaching: {
      keys: "Line up on them at the line. With a seven-second clock, a route that starts late never gets thrown.",
      commentary: "Check your league's contact rules before installing this one.",
    },
  }),
  def({
    id: "d-flag-double-rush",
    name: "Flag Double Rush",
    aliases: ["Two Rush", "Double Fire"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["5flag"],
    formationId: "",
    frontId: "flag-2-rush",
    coverageId: "cover-0",
    pressureId: "flag-double-rush",
    tags: ["flag", "two-rushers", "no-help", "gamble"],
    situations: ["3rd-long", "must-score", "backed-up", "blitz-beater"],
    coaching: {
      keys: "Two rushers from seven yards leaves three defenders on three receivers with nobody deep.",
      commentary: "A gamble that wins the down or gives up the game. Save it.",
    },
  }),
  def({
    id: "d-flag-safety-fire",
    name: "Flag Safety Fire",
    aliases: ["Safety Rush", "Delayed Blitz"],
    philosophy: "defense-pressure",
    family: "pressure",
    variantScope: ["5flag"],
    formationId: "",
    frontId: "flag-1-rush",
    coverageId: "cover-3",
    pressureId: "flag-safety-fire",
    tags: ["flag", "delayed", "disguise", "one-rusher"],
    situations: ["3rd-medium", "2nd-long", "vs-zone"],
    coaching: {
      keys: "The safety starts deep and comes late, so the quarterback never counts him as a rusher.",
    },
  }),
];
