/**
 * 5-on-5 flag.
 *
 * Not a shrunken version of the eleven-man game. There is no blocking at all,
 * so there is no protection to draw and every non-quarterback is running a
 * route. The center is a fully eligible receiver the moment he snaps it. The
 * quarterback may not run, so a run play needs a genuine exchange. The rusher
 * starts seven yards back, which is why the pocket holds long enough for a
 * fifteen-yard route to exist at all — and the seven-second clock is why it
 * barely does.
 *
 * NFL FLAG's own playbook warns, repeatedly, to decide which receiver moves
 * first when two paths cross. With five players in a thirty-yard width they
 * cross constantly, which is why every route here carries a priorityOrder and
 * why the animation timeline is the feature rather than the decoration.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { carry, motion, opt, pass, play, route } from "../kit.ts";

const FLAG = ["5flag"] as const;

export const FLAG_PLAYS: PlaySpec[] = [
  play({
    id: "flag-curls",
    name: "Curls",
    aliases: ["All Curls", "Sit"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "curl",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "X", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("curl", { depth: 10 }, { priorityOrder: 1 }),
      X: route("curl", { depth: 10 }, { priorityOrder: 2 }),
      H: route("hitch", { depth: 6 }, { priorityOrder: 3 }),
    },
    tags: ["curl", "zone-beater", "settle", "beginner-friendly"],
    situations: ["1st-down", "3rd-medium", "vs-zone"],
    coaching: { keys: "Find the soft spot and sit. Do not drift — the quarterback is throwing to where you stopped." },
  }),

  play({
    id: "flag-quick-slants",
    name: "Quick Slants",
    aliases: ["Slants", "Double Slant"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "slant",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: route("slant", undefined, { priorityOrder: 1 }),
      Z: route("slant", undefined, { priorityOrder: 2 }),
      X: route("slant", undefined, { priorityOrder: 3 }),
    },
    tags: ["slant", "quick", "rush-beater", "timing"],
    situations: ["3rd-short", "blitz-beater", "backed-up", "vs-man"],
    coaching: {
      keys: "Ball out on the second step. This is the answer when the rusher is getting home.",
      commentary: "The single most useful play in a beginner flag playbook.",
    },
  }),

  play({
    id: "flag-mesh",
    name: "Mesh",
    aliases: ["Cross", "Rub"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "mesh",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: route("shallow", { toSide: "L", meshWith: "X", meshDepthYd: 4, lane: "over" }, { priorityOrder: 1 }),
      X: route("shallow", { toSide: "R", meshWith: "H", meshDepthYd: 4, lane: "under" }, { priorityOrder: 2 }),
      Z: route("corner", { depth: 8 }, { priorityOrder: 3 }),
    },
    tags: ["mesh", "rub", "man-beater", "crossers"],
    situations: ["1st-down", "3rd-medium", "vs-man", "red-zone"],
    coaching: {
      keys: "The over runner goes first. Settle that in practice so nobody hesitates at the mesh point.",
      commentary: "In a thirty-yard width two crossers are almost impossible to cover in man.",
    },
  }),

  play({
    id: "flag-smash",
    name: "Smash",
    aliases: ["Hi-Lo", "Corner Hitch"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-twins",
    concept: "smash",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("hitch", { depth: 5 }, { priorityOrder: 2 }),
      H: route("corner", { depth: 9 }, { priorityOrder: 1 }),
      RB: route("flat", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["smash", "high-low", "corner", "red-zone"],
    situations: ["red-zone", "3rd-medium", "goal-line", "vs-zone"],
    coaching: { keys: "One defender, two receivers, two depths. Throw to whichever one he is not covering." },
  }),

  play({
    id: "flag-triple-verticals",
    name: "Triple Verticals",
    aliases: ["Verts", "Three Go"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "four-verticals",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", { depth: 14 }, { priorityOrder: 2 }),
      X: route("go", { depth: 14 }, { priorityOrder: 3 }),
      H: route("seam", { depth: 14 }, { priorityOrder: 1 }),
    },
    tags: ["verticals", "shot", "seam"],
    situations: ["2nd-long", "must-score", "two-minute", "vs-cover-1"],
    coaching: {
      keys: "Three verticals against three deep defenders is a footrace, and it takes the whole clock.",
      commentary: "Only call it with time on the play clock and a quarterback who can get it there.",
    },
  }),

  play({
    id: "flag-flood",
    name: "Flood",
    aliases: ["Three Level", "Sail"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips",
    concept: "flood",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["Z", "H", "Y"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("go", { depth: 13 }, { priorityOrder: 1 }),
      H: route("out", { depth: 8 }, { priorityOrder: 2 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
    },
    tags: ["flood", "three-level", "trips", "zone-beater"],
    situations: ["3rd-medium", "sideline", "vs-zone", "1st-down"],
    coaching: { keys: "Deep, intermediate, shallow, all to one side. Take the open one and get out of bounds." },
  }),

  play({
    id: "flag-high-low",
    name: "High Low",
    aliases: ["Levels", "Stack High Low"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-stack",
    concept: "levels",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("go", { depth: 12 }, { priorityOrder: 2 }),
      H: route("out", { depth: 6 }, { priorityOrder: 1 }),
      X: route("dig", { depth: 9 }, { priorityOrder: 3 }),
    },
    tags: ["high-low", "stack", "press-beater", "two-level"],
    situations: ["3rd-medium", "vs-man", "vs-zone"],
    coaching: { keys: "A stack means nobody can press. The two receivers split one defender vertically." },
  }),

  play({
    id: "flag-quick-cross",
    name: "Quick Cross",
    aliases: ["Cross", "Double Cross"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-twins",
    concept: "crossers",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("drag", { toSide: "L" }, { priorityOrder: 2 }),
      H: route("drag", { toSide: "L", depthAdj: 2 }, { priorityOrder: 1 }),
      RB: route("swing", { toSide: "R" }, { startDelayMs: 200, priorityOrder: 3 }),
    },
    tags: ["crossers", "rub", "man-beater", "natural-pick"],
    situations: ["3rd-short", "vs-man", "red-zone", "blitz-beater"],
    coaching: {
      keys: "The two crossers create a natural rub. Order matters: the deeper one clears first.",
    },
  }),

  play({
    id: "flag-corner-post",
    name: "Corner Post",
    aliases: ["Double Move", "Corner-Post"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-twins",
    concept: "double-move",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Z", "H", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("chair", { depth: 12 }, { priorityOrder: 1 }),
      H: route("out", { depth: 6 }, { priorityOrder: 2 }),
      RB: route("checkdown", undefined, { startDelayMs: 250, priorityOrder: 3 }),
    },
    tags: ["double-move", "shot", "man-beater"],
    situations: ["2nd-long", "plus-territory", "vs-man", "must-score"],
    coaching: { keys: "Sell the corner hard. The safety has to commit before the post breaks back." },
  }),

  play({
    id: "flag-bunch-rub",
    name: "Bunch Rub",
    aliases: ["Bunch", "Triangle", "Pick"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-bunch",
    concept: "snag",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "Z", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("corner", { depth: 9 }, { priorityOrder: 2 }),
      H: route("hitch", { depth: 5 }, { priorityOrder: 3 }),
      Y: route("arrow", { toSide: "R" }, { priorityOrder: 1 }),
    },
    tags: ["bunch", "rub", "triangle", "man-beater"],
    situations: ["red-zone", "goal-line", "3rd-short", "vs-man"],
    coaching: {
      keys: "Three receivers in a triangle. Against man somebody gets picked without anybody committing one.",
    },
  }),

  play({
    id: "flag-center-screen",
    name: "Center Screen",
    aliases: ["Snapper Screen", "Center Sneak"],
    philosophy: "flag",
    family: "screen",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "center-release",
    primary: "C",
    reads: [{ order: 1, type: "progression", key: "R", progression: ["C"] }],
    assignments: {
      QB: pass("gun-quick"),
      C: route("checkdown", { toSide: "R" }, { startDelayMs: 350, priorityOrder: 1 }),
      Z: route("go", { depth: 12 }, { priorityOrder: 2 }),
      X: route("go", { depth: 12 }, { priorityOrder: 3 }),
    },
    tags: ["screen", "center", "eligible-snapper", "surprise"],
    situations: ["3rd-short", "blitz-beater", "goal-line"],
    coaching: {
      keys: "The center is eligible the instant he snaps it. Nobody covers him until you have run this once.",
      commentary: "Free yards in most youth leagues, and it stays free longer than it should.",
    },
  }),

  play({
    id: "flag-hitch-and-go",
    name: "Hitch and Go",
    aliases: ["Sluggo", "Stop and Go"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "double-move",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "H", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", { depth: 13 }, { priorityOrder: 1 }),
      H: route("hitch", { depth: 5 }, { priorityOrder: 2 }),
      X: route("dig", { depth: 8 }, { priorityOrder: 3 }),
    },
    tags: ["double-move", "shot", "sluggo"],
    situations: ["2nd-long", "plus-territory", "vs-man", "must-score"],
    coaching: { commentary: "Run the hitch three times first. The fourth one is a touchdown." },
  }),

  play({
    id: "flag-handoff-sweep",
    name: "Handoff Sweep",
    aliases: ["Sweep", "Jet", "End Around"],
    philosophy: "flag",
    family: "run",
    variantScope: [...FLAG],
    formationId: "flag-twins",
    run: { scheme: "outside-zone", carrier: "H", aim: "playside-D" },
    primary: "H",
    assignments: {
      QB: pass("gun-quick", "H"),
      H: motion("jet", carry("playside-D", "stretch"), 1100, "L"),
      Z: route("stalk"),
      RB: route("flat", { toSide: "R" }),
    },
    tags: ["run", "sweep", "motion", "exchange", "perimeter"],
    situations: ["1st-down", "short-yardage", "opening-script"],
    coaching: {
      keys: "The quarterback cannot run it, so the exchange has to be clean and it has to be behind the line.",
      commentary: "Illegal inside either no-run zone, so check where the ball is spotted before you call it.",
    },
  }),

  play({
    id: "flag-option-stick",
    name: "Option Stick",
    aliases: ["Stick", "Choice"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips",
    concept: "stick",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["H", "Y", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: opt("stick", "leverage", [
        { when: "inside leverage", route: "out", mods: { depth: 6 } },
        { when: "outside leverage", route: "dig", mods: { depth: 6 } },
      ], { depth: 6 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("go", { depth: 12 }, { priorityOrder: 3 }),
    },
    tags: ["stick", "option-route", "leverage", "quick"],
    situations: ["3rd-short", "3rd-medium", "vs-man", "vs-zone"],
    coaching: {
      keys: "The receiver reads leverage and breaks away from it. Quarterback and receiver have to see the same thing.",
    },
  }),

  play({
    id: "flag-wheel",
    name: "Wheel",
    aliases: ["Wheel", "Swing Up"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-i",
    concept: "wheel",
    primary: "FB",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["FB", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      FB: route("wheel", { depth: 12 }, { priorityOrder: 1 }),
      Z: route("post", { depth: 10 }, { priorityOrder: 2 }),
      RB: route("flat", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["wheel", "man-beater", "backfield-release"],
    situations: ["2nd-long", "vs-man", "plus-territory"],
    coaching: { keys: "A defender who has covered a back all game does not expect him to run vertical." },
  }),

  play({
    id: "flag-goal-line-fade",
    name: "Goal Line Fade",
    aliases: ["Fade", "Back Shoulder"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-bunch",
    concept: "fade",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "Y", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("go", { depth: 6 }, { priorityOrder: 1 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      H: route("slant", undefined, { priorityOrder: 3 }),
    },
    tags: ["fade", "goal-line", "red-zone", "no-run-zone-answer"],
    situations: ["goal-line", "red-zone", "no-run-zone", "vs-man"],
    coaching: {
      keys: "Inside the five you have to throw it anyway. Put it where only your receiver can get it.",
      commentary: "The no-run zone makes the goal line a passing situation by rule, so have three of these.",
    },
  }),

  play({
    id: "flag-spot",
    name: "Spot",
    aliases: ["Snag", "Triangle"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips-tight",
    concept: "snag",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["H", "Y", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: route("spot", { depth: 6 }, { priorityOrder: 1 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("corner", { depth: 10 }, { priorityOrder: 3 }),
    },
    tags: ["snag", "spot", "triangle", "zone-beater", "beginner-friendly"],
    situations: ["3rd-short", "3rd-medium", "vs-zone", "red-zone"],
    coaching: {
      install: "Three receivers surround one defender at three depths. Throw to whichever one he leaves.",
      keys: "The spot sits down in front of him. The flat runs under him. The corner goes over him.",
    },
  }),

  play({
    id: "flag-levels",
    name: "Levels",
    aliases: ["In Route Levels", "Double In"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-wide",
    concept: "levels",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "X", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("dig", { depth: 10 }, { priorityOrder: 1 }),
      X: route("under", { depth: 5 }, { priorityOrder: 2 }),
      Z: route("post", { depth: 14 }, { priorityOrder: 3 }),
    },
    tags: ["levels", "in-breaking", "zone-beater", "high-low"],
    situations: ["2nd-long", "3rd-medium", "vs-zone", "vs-cover-2"],
    coaching: { keys: "Two in-breaking routes five yards apart. The middle defender can only carry one of them." },
  }),

  play({
    id: "flag-post-wheel",
    name: "Post Wheel",
    aliases: ["Stack Wheel", "Switch"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-double-stack",
    concept: "switch",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "backside", progression: ["H", "X", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("post", { depth: 12 }, { priorityOrder: 2 }),
      H: route("wheel", { depth: 14 }, { priorityOrder: 1, startDelayMs: 150 }),
      Z: route("comeback", { depth: 10 }, { priorityOrder: 3 }),
    },
    tags: ["switch", "wheel", "man-beater", "stack", "shot"],
    situations: ["2nd-long", "vs-man", "plus-territory", "must-score"],
    coaching: {
      keys: "The stacked pair crosses at three yards. Whoever is chasing has to run through the other one.",
      commentary: "The wheel is the throw. The post is there to take the safety out of the picture.",
    },
  }),

  play({
    id: "flag-dagger",
    name: "Dagger",
    aliases: ["Seam Dig", "Clear Dig"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-twins",
    concept: "dagger",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("seam", { depth: 14 }, { priorityOrder: 2 }),
      H: route("dig", { depth: 11 }, { priorityOrder: 1, startDelayMs: 150 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["dagger", "dig", "seam-clear", "zone-beater"],
    situations: ["2nd-long", "3rd-medium", "vs-zone", "vs-cover-3"],
    coaching: { keys: "The vertical route pulls the middle defender up. The dig replaces him at eleven yards." },
  }),

  play({
    id: "flag-shallow-cross",
    name: "Shallow Cross",
    aliases: ["Drive", "Follow"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-wide",
    concept: "drive",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["X", "H", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("shallow", { toSide: "R" }, { priorityOrder: 1 }),
      H: route("dig", { depth: 9 }, { priorityOrder: 2, startDelayMs: 200 }),
      Z: route("go", { depth: 14 }, { priorityOrder: 3 }),
    },
    tags: ["drive", "shallow", "man-beater", "crossers"],
    situations: ["3rd-medium", "1st-down", "vs-man", "blitz-beater"],
    coaching: { keys: "The shallow keeps running until somebody stops it. Against man that is usually nobody." },
  }),

  play({
    id: "flag-double-out",
    name: "Double Out",
    aliases: ["Sticks", "Sideline"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-double-stack",
    concept: "out",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["X", "H", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: route("out", { depth: 10 }, { priorityOrder: 1 }),
      H: route("out", { depth: 5 }, { priorityOrder: 2 }),
      Z: route("comeback", { depth: 12 }, { priorityOrder: 3 }),
    },
    tags: ["out", "sideline", "clock", "high-low"],
    situations: ["two-minute", "3rd-medium", "sideline", "vs-cover-3"],
    coaching: {
      keys: "Both routes finish out of bounds. With the clock running that is the whole point of the call.",
    },
  }),

  play({
    id: "flag-scissors",
    name: "Scissors",
    aliases: ["Cross Fire", "Post Corner Cross"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-tight",
    concept: "scissors",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Z", "H", "Y"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("corner", { depth: 12 }, { priorityOrder: 1 }),
      H: route("post", { depth: 12 }, { priorityOrder: 2 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
    },
    tags: ["scissors", "crossing", "man-beater", "shot", "condensed"],
    situations: ["2nd-long", "plus-territory", "vs-man", "vs-cover-1"],
    coaching: { keys: "The two deep routes cross at twelve yards. Man defenders run into each other there." },
  }),

  play({
    id: "flag-pick-slant",
    name: "Pick Slant",
    aliases: ["Rub Slant", "Pick"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-tight",
    concept: "rub",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["Y", "Z", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("arrow", { toSide: "R" }, { priorityOrder: 2 }),
      Y: route("slant", { depth: 8 }, { priorityOrder: 1, startDelayMs: 120 }),
      H: route("go", { depth: 12 }, { priorityOrder: 3 }),
    },
    tags: ["rub", "pick", "slant", "man-beater", "quick"],
    situations: ["3rd-short", "red-zone", "goal-line", "vs-man"],
    coaching: {
      keys: "The outside receiver clears flat and shallow. The inside receiver comes off his hip.",
      commentary: "Check your league rules on contact. A legal rub in flag is a route that gets in the way on its own.",
    },
  }),

  play({
    id: "flag-jerk",
    name: "Jerk",
    aliases: ["Whip", "Shake"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "jerk",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("jerk", { depth: 7 }, { priorityOrder: 1 }),
      Z: route("go", { depth: 14 }, { priorityOrder: 2 }),
      X: route("curl", { depth: 9 }, { priorityOrder: 3 }),
    },
    tags: ["jerk", "double-move", "man-beater", "separation"],
    situations: ["3rd-medium", "vs-man", "vs-cover-1", "must-score"],
    coaching: { keys: "Sell the inside break hard enough that the defender plants, then come back outside." },
  }),

  play({
    id: "flag-out-and-up",
    name: "Out and Up",
    aliases: ["Sluggo Out", "Double Move Out"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips",
    concept: "double-move",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "H", "Y"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("sluggo", { depth: 14 }, { priorityOrder: 1 }),
      H: route("out", { depth: 6 }, { priorityOrder: 2 }),
      Y: route("shallow", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["double-move", "shot", "sideline", "setup"],
    situations: ["2nd-long", "plus-territory", "vs-man", "must-score"],
    coaching: { commentary: "Throw the six-yard out twice. The third time the corner jumps it and this is behind him." },
  }),

  play({
    id: "flag-swing-screen",
    name: "Swing Screen",
    aliases: ["Back Screen", "Now Swing"],
    philosophy: "flag",
    family: "screen",
    variantScope: [...FLAG],
    formationId: "flag-back-set",
    concept: "swing-screen",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "R", progression: ["RB", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      RB: route("swing", { toSide: "R" }, { priorityOrder: 1 }),
      Z: route("stalk", undefined, { priorityOrder: 2 }),
      X: route("go", { depth: 12 }, { priorityOrder: 3 }),
    },
    tags: ["screen", "swing", "perimeter", "rush-beater", "beginner-friendly"],
    situations: ["1st-down", "blitz-beater", "backed-up", "2nd-long"],
    coaching: {
      keys: "Ball out before the rusher arrives. Everything after the catch is the back against one defender in space.",
    },
  }),

  play({
    id: "flag-back-flood",
    name: "Back Flood",
    aliases: ["Flood Right", "Three Level"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-back-set",
    concept: "flood",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["RB", "Z", "X"] }],
    assignments: {
      QB: pass("sprint"),
      RB: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      Z: route("sail", { depth: 11 }, { priorityOrder: 2 }),
      X: route("post", { depth: 14 }, { priorityOrder: 3, startDelayMs: 150 }),
    },
    tags: ["flood", "three-level", "sprint-out", "zone-beater"],
    situations: ["3rd-medium", "2nd-long", "vs-zone", "sideline"],
    coaching: { keys: "Move the quarterback toward the routes. The rusher has further to travel every step." },
  }),

  play({
    id: "flag-four-verticals",
    name: "Four Verticals",
    aliases: ["Verts", "Streaks"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-wide",
    concept: "four-verts",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Z", "X", "C"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", { depth: 16 }, { priorityOrder: 2 }),
      X: route("go", { depth: 16 }, { priorityOrder: 3 }),
      H: route("seam", { depth: 14 }, { priorityOrder: 1 }),
      C: route("checkdown", { toSide: "R" }, { priorityOrder: 4, startDelayMs: 400 }),
    },
    tags: ["four-verts", "vertical", "shot", "eligible-snapper", "must-score"],
    situations: ["must-score", "two-minute", "plus-territory", "vs-cover-2"],
    coaching: {
      install: "Three vertical routes and the snapper underneath as the outlet.",
      keys: "With a seven-second clock this is the deepest call in the book. It needs a clean snap and a decision.",
    },
  }),

  play({
    id: "flag-center-seam",
    name: "Center Seam",
    aliases: ["Snapper Seam", "Delay Seam"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-tight",
    concept: "center-release",
    primary: "C",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["C", "Z", "H"] }],
    assignments: {
      QB: pass("gun-3"),
      C: route("seam", { depth: 10 }, { priorityOrder: 1, startDelayMs: 400 }),
      Z: route("out", { depth: 8 }, { priorityOrder: 2 }),
      H: route("out", { depth: 8 }, { priorityOrder: 3 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 4 }),
    },
    tags: ["center", "eligible-snapper", "seam", "delay", "surprise"],
    situations: ["3rd-medium", "red-zone", "vs-zone", "goal-line"],
    coaching: {
      keys: "Both outside routes break out and take the coverage with them. The snapper walks up the middle.",
    },
  }),

  play({
    id: "flag-dive-handoff",
    name: "Dive Handoff",
    aliases: ["Dive", "Inside Give"],
    philosophy: "flag",
    family: "run",
    variantScope: [...FLAG],
    formationId: "flag-i",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      FB: route("arrow", { toSide: "R" }),
      Z: route("stalk"),
    },
    tags: ["run", "dive", "short-yardage", "exchange"],
    situations: ["3rd-short", "4th-short", "short-yardage", "four-minute"],
    coaching: {
      keys: "The exchange happens behind the line and the quarterback stays put. Two yards is a good outcome here.",
      commentary: "Illegal inside either no-run zone, so check the spot before you send it in.",
    },
  }),

  play({
    id: "flag-counter-handoff",
    name: "Counter Handoff",
    aliases: ["Counter", "Misdirection Give"],
    philosophy: "flag",
    family: "run",
    variantScope: [...FLAG],
    formationId: "flag-back-set",
    run: { scheme: "counter", carrier: "RB", aim: "backside-C" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("backside-C", "counter-step"),
      Z: motion("across", route("stalk"), 900, "L"),
      X: route("crack"),
    },
    tags: ["run", "counter", "motion", "misdirection", "exchange"],
    situations: ["1st-down", "2nd-short", "opening-script"],
    coaching: { keys: "Motion sets the defense running one way and the handoff goes the other." },
  }),

  play({
    id: "flag-reverse-pass",
    name: "Reverse Pass",
    aliases: ["Trick", "Double Pass", "Halfback Pass"],
    philosophy: "flag",
    family: "trick",
    variantScope: [...FLAG],
    formationId: "flag-twins",
    concept: "halfback-pass",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Z", "H"] }],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: pass("sprint"),
      Z: route("post", { depth: 16 }, { priorityOrder: 1, startDelayMs: 400 }),
      H: route("shallow", { toSide: "L" }, { priorityOrder: 2 }),
    },
    tags: ["trick", "double-pass", "shot", "misdirection"],
    situations: ["plus-territory", "opening-script", "must-score", "vs-cover-1"],
    coaching: {
      keys: "The handoff has to be behind the line and the second passer has to stay behind it too.",
      commentary: "One of these a game. The safety who has bitten on the sweep twice is the target.",
    },
  }),

  play({
    id: "flag-fade-stop",
    name: "Fade Stop",
    aliases: ["Back Shoulder", "Stop Fade"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips-tight",
    concept: "fade",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "Y", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("fade", { depth: 8 }, { priorityOrder: 1 }),
      H: route("pivot", { depth: 4 }, { priorityOrder: 2 }),
      Y: route("angle", { depth: 5 }, { priorityOrder: 3 }),
    },
    tags: ["fade", "red-zone", "no-run-zone-answer", "condensed", "man-beater"],
    situations: ["goal-line", "red-zone", "no-run-zone", "vs-man"],
    coaching: {
      keys: "The receiver stops at eight and comes back for it. A defender running to the corner cannot stop with him.",
    },
  }),

  // ── red zone package ─────────────────────────────────────────────────────
  play({
    id: "flag-rz-slant-flat",
    name: "Slant Flat",
    aliases: ["Snag Lite", "Slant Arrow"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-divide",
    concept: "slant-flat",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Z", "Y", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("slant", { depth: 5 }, { priorityOrder: 1 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      X: route("fade", { depth: 8 }, { priorityOrder: 3 }),
    },
    tags: ["slant-flat", "red-zone", "two-man", "quick"],
    situations: ["red-zone", "3rd-short", "goal-line", "vs-zone"],
    coaching: { keys: "Two routes on one defender at two depths. He declares and you throw the other one." },
  }),

  play({
    id: "flag-rz-double-slant",
    name: "Double Slant",
    aliases: ["Stack Slants", "Twin Slants"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-double-stack",
    concept: "slant",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "backside", progression: ["H", "X", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: route("slant", { depth: 4 }, { priorityOrder: 2 }),
      H: route("slant", { depth: 7 }, { priorityOrder: 1, startDelayMs: 120 }),
      Z: route("fade", { depth: 8 }, { priorityOrder: 3 }),
    },
    tags: ["slant", "stack", "red-zone", "rub", "man-beater"],
    situations: ["red-zone", "goal-line", "3rd-short", "vs-man"],
    coaching: { keys: "The front man of the stack slants first and takes the coverage with him." },
  }),

  play({
    id: "flag-rz-corner-flat",
    name: "Corner Flat",
    aliases: ["Smash Red", "Flag Corner"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips-tight",
    concept: "smash",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "Y", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("corner", { depth: 9 }, { priorityOrder: 1 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      H: route("hitch", { depth: 5 }, { priorityOrder: 3 }),
    },
    tags: ["smash", "corner", "red-zone", "high-low", "zone-beater"],
    situations: ["red-zone", "goal-line", "vs-cover-2", "vs-zone"],
    coaching: { keys: "The corner route breaks at nine and finishes at the pylon. Throw it where he is going." },
  }),

  play({
    id: "flag-rz-pick-fade",
    name: "Pick Fade",
    aliases: ["Rub Fade", "Bunch Fade"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-bunch",
    concept: "rub",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Y", "Z", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("shallow", { toSide: "L" }, { priorityOrder: 2 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      Y: route("fade", { depth: 7 }, { priorityOrder: 1, startDelayMs: 150 }),
    },
    tags: ["rub", "fade", "red-zone", "bunch", "man-beater"],
    situations: ["goal-line", "red-zone", "vs-man", "no-run-zone"],
    coaching: {
      keys: "Two receivers cross underneath and the third runs the fade off the traffic they leave.",
    },
  }),

  play({
    id: "flag-rz-shovel-arrow",
    name: "Arrow Now",
    aliases: ["Quick Arrow", "Now"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-tight",
    concept: "arrow",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["Y", "Z", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Y: route("arrow", { toSide: "R" }, { priorityOrder: 1 }),
      Z: route("go", { depth: 8 }, { priorityOrder: 2 }),
      H: route("slant", { depth: 5 }, { priorityOrder: 3 }),
    },
    tags: ["arrow", "quick", "red-zone", "rush-beater"],
    situations: ["goal-line", "3rd-short", "blitz-beater", "no-run-zone"],
    coaching: { keys: "First read, first step. Inside the five this is the fastest ball in the book." },
  }),

  // ── two-minute package ───────────────────────────────────────────────────
  play({
    id: "flag-2min-all-outs",
    name: "All Outs",
    aliases: ["Sticks Out", "Sideline Now"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "out",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "X", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("out", { depth: 9 }, { priorityOrder: 1 }),
      X: route("out", { depth: 9 }, { priorityOrder: 2 }),
      H: route("out", { depth: 5 }, { priorityOrder: 3 }),
    },
    tags: ["out", "sideline", "clock", "two-minute"],
    situations: ["two-minute", "sideline", "3rd-medium", "must-score"],
    coaching: { keys: "Every route finishes out of bounds. Catch it and get your feet outside." },
  }),

  play({
    id: "flag-2min-comeback",
    name: "Comebacks",
    aliases: ["Stop Routes", "Comeback"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-wide",
    concept: "comeback",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "X", "H"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("comeback", { depth: 13 }, { priorityOrder: 1 }),
      X: route("comeback", { depth: 13 }, { priorityOrder: 2 }),
      H: route("curl", { depth: 8 }, { priorityOrder: 3 }),
    },
    tags: ["comeback", "sideline", "clock", "chunk"],
    situations: ["two-minute", "2nd-long", "sideline", "vs-man"],
    coaching: {
      keys: "Thirteen yards, snap the head back to the sideline. Against a corner who is bailing it is uncoverable.",
    },
  }),

  play({
    id: "flag-2min-seam-shot",
    name: "Seam Shot",
    aliases: ["Two Minute Shot", "Deep Seam"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-stack",
    concept: "verticals",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", { depth: 18 }, { priorityOrder: 2 }),
      H: route("seam", { depth: 16 }, { priorityOrder: 1, startDelayMs: 120 }),
      X: route("post", { depth: 16 }, { priorityOrder: 3 }),
    },
    tags: ["verticals", "shot", "must-score", "stack"],
    situations: ["must-score", "two-minute", "2nd-long", "vs-cover-2"],
    coaching: { commentary: "One throw, one chance. Take it while there is still time for another snap after it." },
  }),

  play({
    id: "flag-2min-hitch-sideline",
    name: "Hitch Sideline",
    aliases: ["Quick Stop", "Clock Hitch"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-divide",
    concept: "hitch",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["X", "Z", "Y"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: route("hitch", { depth: 7 }, { priorityOrder: 1 }),
      Z: route("hitch", { depth: 7 }, { priorityOrder: 2 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
    },
    tags: ["hitch", "clock", "sideline", "beginner-friendly"],
    situations: ["two-minute", "sideline", "3rd-short", "vs-zone"],
    coaching: { keys: "Catch it, turn, and get out. Seven yards and a stopped clock is a good outcome." },
  }),

  // ── rush-count answers ───────────────────────────────────────────────────
  play({
    id: "flag-hot-now",
    name: "Hot Now",
    aliases: ["Blitz Now", "Sight Adjust"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-double-stack",
    concept: "hot",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "R", progression: ["X", "H", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      X: route("hitch", { depth: 4 }, { priorityOrder: 1 }),
      H: route("arrow", { toSide: "L" }, { priorityOrder: 2 }),
      Z: route("slant", { depth: 6 }, { priorityOrder: 3 }),
    },
    tags: ["hot", "rush-beater", "quick", "answer"],
    situations: ["blitz-beater", "3rd-short", "backed-up", "vs-cover-0"],
    coaching: {
      install: "Against two rushers every route shortens by three yards. This is the version of the play that assumes they are coming.",
    },
  }),

  play({
    id: "flag-double-rush-screen",
    name: "Rush Screen",
    aliases: ["Double Rush Answer", "Middle Screen"],
    philosophy: "flag",
    family: "screen",
    variantScope: [...FLAG],
    formationId: "flag-split-backs",
    concept: "middle-screen",
    primary: "FB",
    reads: [{ order: 1, type: "progression", key: "R", progression: ["FB", "RB", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      FB: route("checkdown", { toSide: "L" }, { priorityOrder: 1, startDelayMs: 400 }),
      RB: route("swing", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("go", { depth: 14 }, { priorityOrder: 3 }),
    },
    tags: ["screen", "rush-beater", "two-back", "answer"],
    situations: ["blitz-beater", "2nd-long", "3rd-long", "vs-cover-0"],
    coaching: {
      keys: "Let them come, then throw behind them. Two rushers who miss are two defenders out of the play.",
    },
  }),

  play({
    id: "flag-max-protect-shot",
    name: "Keeper Shot",
    aliases: ["Two Back Shot", "Protected Deep"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-split-backs",
    concept: "shot",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Z", "RB", "FB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("post", { depth: 18 }, { priorityOrder: 1 }),
      RB: route("wheel", { depth: 12 }, { priorityOrder: 2, startDelayMs: 200 }),
      FB: route("checkdown", { toSide: "L" }, { priorityOrder: 3, startDelayMs: 350 }),
    },
    tags: ["shot", "two-back", "deep", "outlet"],
    situations: ["2nd-long", "must-score", "plus-territory", "vs-man"],
    coaching: {
      keys: "One deep route, one wheel, one outlet. If the deep ball is not there the checkdown always is.",
    },
  }),

  // ── concept depth ────────────────────────────────────────────────────────
  play({
    id: "flag-y-cross",
    name: "Y Cross",
    aliases: ["Deep Cross", "Over"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips",
    concept: "y-cross",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Z", "Y"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", { depth: 16 }, { priorityOrder: 2 }),
      H: route("over", { depth: 12 }, { priorityOrder: 1, startDelayMs: 150 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
    },
    tags: ["y-cross", "crosser", "man-beater", "chunk"],
    situations: ["2nd-long", "3rd-medium", "vs-man", "vs-cover-1"],
    coaching: { keys: "The crosser starts inside and finishes at twelve on the far hash. It takes time, so it needs a clean pocket." },
  }),

  play({
    id: "flag-mesh-sit",
    name: "Mesh Sit",
    aliases: ["Mesh Settle", "Zone Mesh"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-wide",
    concept: "mesh",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "X", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: route("shallow", { toSide: "R", meshWith: "X", meshDepthYd: 4, lane: "over" }, { priorityOrder: 1 }),
      X: route("shallow", { toSide: "L", meshWith: "H", meshDepthYd: 4, lane: "under" }, { priorityOrder: 2 }),
      Z: route("curl", { depth: 10 }, { priorityOrder: 3 }),
    },
    tags: ["mesh", "sit", "zone-beater", "crossers"],
    situations: ["1st-down", "3rd-medium", "vs-zone", "vs-cover-3"],
    coaching: {
      install: "The same mesh, with both crossers settling in the first open grass instead of running through.",
      keys: "Against zone they sit down in the first window. Against man they keep running. The receivers decide.",
    },
  }),

  play({
    id: "flag-choice",
    name: "Choice",
    aliases: ["Option Route", "Read Route"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-back-set",
    concept: "choice",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["RB", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      RB: opt("stick", "leverage", [
        { when: "defender inside", route: "out", mods: { depth: 7 } },
        { when: "defender outside", route: "dig", mods: { depth: 7 } },
        { when: "defender deep", route: "hitch", mods: { depth: 6 } },
      ], { depth: 7 }),
      Z: route("go", { depth: 14 }, { priorityOrder: 2 }),
      X: route("post", { depth: 12 }, { priorityOrder: 3 }),
    },
    tags: ["choice", "option-route", "leverage", "man-beater"],
    situations: ["3rd-medium", "vs-man", "2nd-long", "vs-cover-1"],
    coaching: {
      keys: "Isolate your best route runner and let him break off whatever the defender gives him.",
      commentary: "It only works if the quarterback and the receiver watch the same defender.",
    },
  }),

  play({
    id: "flag-follow",
    name: "Follow",
    aliases: ["Chase", "Double Shallow"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-twins",
    concept: "follow",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("shallow", { toSide: "L" }, { priorityOrder: 2 }),
      H: route("drag", { depth: 6 }, { priorityOrder: 1, startDelayMs: 200 }),
      RB: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
    },
    tags: ["follow", "crossers", "man-beater", "traffic"],
    situations: ["3rd-medium", "vs-man", "1st-down", "red-zone"],
    coaching: { keys: "Two crossers on the same track. The trailing defender has to fight through the first one." },
  }),

  play({
    id: "flag-china",
    name: "China",
    aliases: ["Slant Out", "China Concept"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-twins",
    concept: "china",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("slant", { depth: 6 }, { priorityOrder: 2 }),
      H: route("out", { depth: 6 }, { priorityOrder: 1 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["china", "slant-out", "quick", "rub"],
    situations: ["3rd-short", "1st-down", "vs-man", "sideline"],
    coaching: { keys: "The outside receiver slants in and the inside receiver breaks out behind him." },
  }),

  play({
    id: "flag-post-dig",
    name: "Post Dig",
    aliases: ["Deep Middle", "Post Over"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-divide",
    concept: "post-dig",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Z", "Y"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("post", { depth: 16 }, { priorityOrder: 2 }),
      X: route("dig", { depth: 12 }, { priorityOrder: 1, startDelayMs: 120 }),
      Y: route("under", { depth: 4 }, { priorityOrder: 3 }),
    },
    tags: ["post-dig", "high-low", "middle", "zone-beater"],
    situations: ["2nd-long", "3rd-medium", "vs-cover-3", "vs-zone"],
    coaching: { keys: "The post occupies the deep middle defender and the dig runs underneath him." },
  }),

  play({
    id: "flag-wheel-post",
    name: "Wheel Post",
    aliases: ["Switch Wheel", "Back Wheel"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-split-backs",
    concept: "switch",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["RB", "Z", "FB"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("post", { depth: 14 }, { priorityOrder: 2 }),
      RB: route("wheel", { depth: 13 }, { priorityOrder: 1, startDelayMs: 200 }),
      FB: route("flat", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["wheel", "switch", "man-beater", "backfield-release"],
    situations: ["2nd-long", "vs-man", "plus-territory", "vs-cover-1"],
    coaching: { keys: "A linebacker who has covered this back all game is not running with him up the sideline." },
  }),

  play({
    id: "flag-stick-nod",
    name: "Stick Nod",
    aliases: ["Stick Seam", "Nod"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips-tight",
    concept: "stick-nod",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Z", "Y"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("sluggo", { depth: 12 }, { priorityOrder: 1 }),
      Z: route("out", { depth: 8 }, { priorityOrder: 2 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
    },
    tags: ["stick-nod", "double-move", "seam", "setup"],
    situations: ["2nd-long", "plus-territory", "vs-zone", "must-score"],
    coaching: { commentary: "Run Stick twice. The third time the hook defender jumps it and the seam is wide open." },
  }),

  // ── movement and trickery ────────────────────────────────────────────────
  play({
    id: "flag-jet-slant",
    name: "Jet Slant",
    aliases: ["Motion Slant", "Fly Slant"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-wide",
    concept: "motion-slant",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: motion("jet", route("slant", { depth: 6 }, { priorityOrder: 1 }), 1000, "R"),
      Z: route("go", { depth: 12 }, { priorityOrder: 2 }),
      X: route("hitch", { depth: 6 }, { priorityOrder: 3 }),
    },
    tags: ["motion", "slant", "leverage", "man-beater"],
    situations: ["1st-down", "3rd-short", "vs-man", "opening-script"],
    coaching: {
      keys: "Motion tells you man or zone before the snap. If a defender travels with him, throw it away from the traffic.",
    },
  }),

  play({
    id: "flag-orbit-flood",
    name: "Orbit Flood",
    aliases: ["Orbit Motion", "Return Flood"],
    philosophy: "flag",
    family: "pass",
    variantScope: [...FLAG],
    formationId: "flag-trips",
    concept: "flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "H", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      Y: motion("orbit", route("flat", { toSide: "L" }, { priorityOrder: 1 }), 1200, "L"),
      H: route("sail", { depth: 10 }, { priorityOrder: 2 }),
      Z: route("go", { depth: 15 }, { priorityOrder: 3 }),
    },
    tags: ["flood", "orbit", "motion", "three-level"],
    situations: ["3rd-medium", "2nd-long", "vs-zone", "sideline"],
    coaching: { keys: "Motion the flat route across so the defense has to re-fit while the ball is coming out." },
  }),

  play({
    id: "flag-double-pass",
    name: "Double Pass",
    aliases: ["Throwback Trick", "Hook and Throw"],
    philosophy: "flag",
    family: "trick",
    variantScope: [...FLAG],
    formationId: "flag-spread",
    concept: "double-pass",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: pass("sprint"),
      X: route("go", { depth: 16 }, { priorityOrder: 1, startDelayMs: 500 }),
      Z: route("post", { depth: 14 }, { priorityOrder: 2, startDelayMs: 500 }),
    },
    tags: ["trick", "double-pass", "shot", "backwards-throw"],
    situations: ["plus-territory", "opening-script", "must-score", "vs-man"],
    coaching: {
      keys: "The first throw goes backwards, which keeps it a legal forward pass for the second one.",
      commentary: "Everybody on that sideline turns to watch the first catch. That is the whole play.",
    },
  }),

  play({
    id: "flag-center-sneak-screen",
    name: "Center Delay",
    aliases: ["Snapper Delay", "Center Leak"],
    philosophy: "flag",
    family: "screen",
    variantScope: [...FLAG],
    formationId: "flag-trips",
    concept: "center-release",
    primary: "C",
    reads: [{ order: 1, type: "progression", key: "R", progression: ["C", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      C: route("flat", { toSide: "L" }, { priorityOrder: 1, startDelayMs: 500 }),
      Z: route("go", { depth: 14 }, { priorityOrder: 2 }),
      H: route("out", { depth: 8 }, { priorityOrder: 3 }),
      Y: route("shallow", { toSide: "R" }, { priorityOrder: 4 }),
    },
    tags: ["center", "eligible-snapper", "delay", "backside", "surprise"],
    situations: ["3rd-medium", "blitz-beater", "red-zone", "2nd-long"],
    coaching: {
      keys: "Three receivers to one side and the snapper leaking out the back door on the other.",
    },
  }),

  play({
    id: "flag-qb-draw-handoff",
    name: "Delay Handoff",
    aliases: ["Draw", "Delay Give"],
    philosophy: "flag",
    family: "run",
    variantScope: [...FLAG],
    formationId: "flag-back-set",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("gun-3", "RB"),
      RB: carry("playside-B", "downhill"),
      Z: route("go", { depth: 12 }),
      X: route("go", { depth: 12 }),
    },
    tags: ["run", "draw", "delay", "rush-beater", "exchange"],
    situations: ["2nd-long", "3rd-long", "blitz-beater", "vs-cover-0"],
    coaching: {
      keys: "Show the drop, let the rusher run past, then hand it off behind him.",
      commentary: "Illegal inside either no-run zone, so check the spot first.",
    },
  }),

  play({
    id: "flag-reverse-handoff",
    name: "Reverse",
    aliases: ["End Around Reverse", "Double Handoff"],
    philosophy: "flag",
    family: "trick",
    variantScope: [...FLAG],
    formationId: "flag-wide",
    run: { scheme: "counter", carrier: "X", aim: "backside-D" },
    primary: "X",
    assignments: {
      QB: pass("gun-quick", "H"),
      H: motion("jet", carry("playside-D", "stretch"), 1000, "R"),
      X: carry("backside-D", "stretch"),
      Z: route("stalk"),
    },
    tags: ["trick", "reverse", "motion", "misdirection", "exchange"],
    situations: ["1st-down", "plus-territory", "opening-script"],
    coaching: {
      keys: "Two exchanges, both behind the line. Run the jet sweep first so they chase it.",
      commentary: "Illegal inside either no-run zone.",
    },
  }),
];
