/**
 * Flexbone triple option and Wing-T.
 *
 * Both are SERIES offenses, which is the thing a flat library gets wrong: the
 * sweep pulls defenders wide, the trap punishes them for chasing, and the
 * waggle burns them for crashing. Each play is tagged with its series so the
 * library can present them as a family rather than as twelve unrelated cards.
 *
 * The triple option is stored as two ordered reads on one play — dive then
 * pitch — which is exactly the same mechanism an RPO uses.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, carry, motion, pass, pitch, play, route } from "../kit.ts";

const TACKLE = ["11man"] as const;

export const FLEXBONE: PlaySpec[] = [
  play({
    id: "fb-inside-veer",
    name: "Inside Veer",
    aliases: ["Triple Option", "Veer", "Inside Veer"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["triple-option", "veer", "dive", "pitch", "two-reads", "series"],
    situations: ["1st-down", "short-yardage", "4th-short", "four-minute", "goal-line"],
    coaching: {
      install: "Read the first man outside the playside tackle for the give. Read the next one for the pitch.",
      commentary: "Two defenders blocked with two decisions instead of two blockers. That is the whole offense.",
    },
  }),

  play({
    id: "fb-midline-triple",
    name: "Midline Triple",
    aliases: ["Midline", "Midline Triple"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["triple-option", "midline", "dive", "interior", "series"],
    situations: ["short-yardage", "1st-down", "goal-line", "4th-short"],
    coaching: { install: "The read moves inside to the playside tackle. Answer to a defense widening for the veer." },
  }),

  play({
    id: "fb-midline-double",
    name: "Midline Double",
    aliases: ["Midline Double", "Double Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "midline", "double", "two-way"],
    situations: ["short-yardage", "1st-down", "3rd-short"],
    coaching: { install: "One read, no pitch. Simpler when the pitch key is unreadable." },
  }),

  play({
    id: "fb-outside-veer",
    name: "Outside Veer",
    aliases: ["Load Option", "Outside Veer"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "FB", aim: "playside-C" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "EMLOS", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-C", "stretch"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "outside-veer", "load", "edge"],
    situations: ["1st-down", "plus-territory"],
    coaching: { install: "The dive track moves outside the tackle and the slot loads the support defender." },
  }),

  play({
    id: "fb-rocket-toss",
    name: "Rocket Toss",
    aliases: ["Rocket", "Rocket Toss", "Fast Toss"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "A1", aim: "playside-D" },
    primary: "A1",
    assignments: {
      QB: pitch("A1"),
      A1: motion("jet", carry("playside-D", "stretch"), 1100, "R"),
      FB: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("crack"),
      X: route("stalk"),
    },
    tags: ["toss", "motion", "perimeter", "speed", "series"],
    situations: ["1st-down", "opening-script", "plus-territory"],
    coaching: {
      keys: "Pre-snap motion, immediate pitch. The fastest way a flexbone gets to the edge.",
      commentary: "It exists so the defense cannot sit inside waiting for the veer.",
    },
  }),

  play({
    id: "fb-counter-option",
    name: "Counter Option",
    aliases: ["Counter Option", "Reverse Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "counter", carrier: "QB", aim: "backside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "backside", ifTake: { pitch: "A2" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("backside-C", "counter-step"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      A2: route("arrow", { toSide: "L" }, { startDelayMs: 200 }),
      A1: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "counter", "misdirection", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: { install: "Veer action one way, option the other. Punishes a defense that has started to flow." },
  }),

  play({
    id: "fb-fb-trap",
    name: "FB Trap",
    aliases: ["Fullback Trap", "Trap"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "trap", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["trap", "fullback", "quick-hitting", "series"],
    situations: ["short-yardage", "1st-down", "3rd-short"],
    coaching: { install: "Answer to a tackle who has learned to crash the dive." },
  }),

  play({
    id: "fb-qb-follow",
    name: "QB Follow",
    aliases: ["Follow", "QB Follow", "Q Iso"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "power", carrier: "QB", aim: "playside-A" },
    primary: "QB",
    assignments: {
      QB: carry("playside-A", "downhill"),
      FB: carry("playside-B", "dive"),
      A1: block({ block: "arc" }),
      A2: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["qb-run", "follow", "short-yardage", "series"],
    situations: ["short-yardage", "goal-line", "4th-short"],
    coaching: { install: "The fullback carries out the dive fake and the quarterback follows him into the same gap." },
  }),

  play({
    id: "fb-veer-pass",
    name: "Veer Pass",
    aliases: ["Play Action Veer", "Veer Pass"],
    philosophy: "flexbone",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    protection: "half-slide",
    concept: "option-play-action",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Z", "A1", "X"] }],
    assignments: {
      QB: pass("boot", "FB"),
      Z: route("post", { depth: 12 }, { priorityOrder: 1 }),
      A1: route("wheel", undefined, { priorityOrder: 2 }),
      X: route("go", undefined, { priorityOrder: 3 }),
      A2: route("flat", { toSide: "L" }, { startDelayMs: 300 }),
    },
    tags: ["play-action", "option-action", "shot", "post-wheel"],
    situations: ["1st-down", "plus-territory", "vs-cover-1", "opening-script"],
    coaching: {
      keys: "Two throws all game, and this is one of them. The safeties have been in the run fit for three quarters.",
    },
  }),

  play({
    id: "fb-toss-sweep",
    name: "Toss Sweep",
    aliases: ["Sweep", "Toss Sweep"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "A1", aim: "playside-D" },
    primary: "A1",
    assignments: {
      QB: pitch("A1"),
      A1: carry("playside-D", "stretch"),
      FB: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["toss", "sweep", "perimeter"],
    situations: ["1st-down", "plus-territory"],
    coaching: { install: "Straight pitch to the slot without motion. Slower than Rocket, better angles." },
  }),

  play({
    id: "fb-halfback-pass",
    name: "Halfback Pass",
    aliases: ["Trick", "HB Pass", "Throwback"],
    philosophy: "flexbone",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    concept: "halfback-pass",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["X", "Z"] }],
    assignments: {
      QB: pitch("A1"),
      A1: pass("sprint"),
      X: route("go", undefined, { priorityOrder: 1 }),
      Z: route("post", { depth: 14 }, { priorityOrder: 2 }),
      FB: block({ block: "arc" }),
      A2: block({ block: "hinge" }),
    },
    tags: ["trick", "halfback-pass", "shot", "sweep-action"],
    situations: ["plus-territory", "1st-down", "opening-script", "vs-cover-1"],
    coaching: { commentary: "Once a game, off the look that has already gained forty yards on the ground." },
  }),

  play({
    id: "fb-veer-reverse",
    name: "Veer Reverse",
    aliases: ["Reverse", "Slot Reverse"],
    philosophy: "flexbone",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "counter", carrier: "A2", aim: "backside-D" },
    primary: "A2",
    assignments: {
      QB: pass("1step", "A1"),
      A1: route("arrow", { toSide: "R" }),
      A2: carry("backside-D", "stretch"),
      FB: carry("playside-B", "dive"),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["trick", "reverse", "misdirection", "series"],
    situations: ["1st-down", "plus-territory", "opening-script"],
    coaching: { commentary: "Three fakes before the ball ever goes anywhere. It works because the first two are real plays." },
  }),

  play({
    id: "fb-speed-option",
    name: "Speed Option",
    aliases: ["Load Option", "Speed", "Quick Pitch Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "QB", aim: "playside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-C", "stretch"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 120 }),
      FB: block({ block: "arc", target: "EMLOS" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "speed-option", "two-way", "perimeter", "no-dive"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: {
      install: "One read instead of two. The quarterback attacks the outside shoulder of the pitch key immediately.",
      keys: "Pitch relationship is four yards behind and four wide. Keep it the whole way.",
    },
  }),

  play({
    id: "fb-load-option",
    name: "Load Option",
    aliases: ["Load", "Blocked Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "QB", aim: "playside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: block({ block: "kickout", target: "EMLOS" }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "load", "blocked-pitch-key", "answer"],
    situations: ["3rd-short", "goal-line", "vs-cover-0", "short-yardage"],
    coaching: {
      keys: "When a team is fast-flowing the pitch key, block him and run downhill off his tail.",
    },
  }),

  play({
    id: "fb-wishbone-triple",
    name: "Wishbone Triple",
    aliases: ["Bone Triple", "Full House Veer"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "full-house-t",
    personnelId: "23",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "RB" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      RB: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A1: block({ block: "arc" }),
      Y: block({ block: "down" }),
      H: block({ block: "base" }),
    },
    tags: ["option", "wishbone", "triple", "heavy", "three-back"],
    situations: ["3rd-short", "goal-line", "short-yardage", "four-minute"],
    coaching: {
      install: "The same read as Inside Veer with a tight end and a third back instead of two split ends.",
      commentary: "Bring this out when the game is a possession game and the sideline wants the clock to keep moving.",
    },
  }),

  play({
    id: "fb-belly-keep",
    name: "Belly Keep",
    aliases: ["Belly Option", "Belly G"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "full-house-t",
    personnelId: "23",
    run: { scheme: "power", carrier: "QB", aim: "playside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "RB" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-C", "downhill"),
      FB: carry("playside-A", "dive"),
      RB: route("arrow", { toSide: "R" }, { startDelayMs: 200 }),
      A1: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      H: block({ block: "hinge" }),
    },
    tags: ["option", "belly", "gap-scheme", "keep"],
    situations: ["1st-down", "2nd-short", "red-zone"],
    coaching: { keys: "Fullback belly action first, then the quarterback presses off the kickout." },
  }),

  play({
    id: "fb-rocket-pass",
    name: "Rocket Pass",
    aliases: ["Rocket Play Action", "Toss Pass"],
    philosophy: "flexbone",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    protection: "sprint-right",
    concept: "rocket-action",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "A2", "X"] }],
    assignments: {
      QB: pass("sprint", "A1"),
      A1: motion("jet", block({ block: "arc" }), 1100, "R"),
      Z: route("post-corner", { depth: 14 }, { priorityOrder: 1 }),
      A2: route("wheel", undefined, { priorityOrder: 2, startDelayMs: 250 }),
      X: route("over", { depth: 14 }, { priorityOrder: 3 }),
      FB: block({ block: "hinge" }),
    },
    tags: ["play-action", "rocket", "shot", "sprint-out", "sideline"],
    situations: ["1st-down", "plus-territory", "vs-cover-3", "opening-script"],
    coaching: {
      keys: "The corner has squatted on Rocket for two quarters. This is the throw over the top of him.",
    },
  }),

  play({
    id: "fb-slot-screen",
    name: "Slot Screen",
    aliases: ["A-Back Screen", "Veer Screen"],
    philosophy: "flexbone",
    family: "screen",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    protection: "screen-release",
    concept: "slot-screen",
    primary: "A2",
    reads: [{ order: 1, type: "progression", key: "OLB", progression: ["A2"] }],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A2: route("screen", { toSide: "L" }, { priorityOrder: 1, startDelayMs: 250 }),
      A1: block({ block: "arc" }),
      X: block({ block: "stalk" }),
      Z: route("stalk"),
    },
    tags: ["screen", "slot-screen", "backside", "option-action", "answer"],
    situations: ["2nd-long", "3rd-medium", "vs-cover-0", "blitz-beater"],
    coaching: {
      install: "Full dive fake, then throw behind the linebackers who filled it.",
      keys: "Against a team that walks both safeties down, this is the softest yardage on the call sheet.",
    },
  }),

  play({
    id: "fb-triple-tag-arrow",
    name: "Triple / Arrow",
    aliases: ["Veer Arrow", "Triple Tag"],
    philosophy: "flexbone",
    family: "rpo",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
      { order: 2, type: "rpo-post", key: "OLB", keySide: "backside", ifTake: { keep: "QB" }, ifNot: { throw: "A2" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: route("arrow", { toSide: "L" }, { priorityOrder: 1 }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "rpo", "arrow", "backside-throw"],
    situations: ["1st-down", "2nd-short", "vs-cover-3"],
    coaching: { keys: "Triple option with a throw attached backside, so a fast-flowing linebacker costs them yards." },
  }),

  play({
    id: "fb-midline-lead",
    name: "Midline Lead",
    aliases: ["Lead Midline", "Midline G"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "trap", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DT", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: block({ block: "wrap", target: "PSLB" }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["midline", "option", "interior", "lead"],
    situations: ["3rd-short", "short-yardage", "goal-line", "four-minute"],
    coaching: { keys: "Read the first defender inside, and put a blocker in front of the keep." },
  }),

  play({
    id: "fb-rocket-option",
    name: "Rocket Option",
    aliases: ["Rocket Pitch", "Fast Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "QB", aim: "playside-D" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-D", "stretch"),
      A1: motion("jet", route("arrow", { toSide: "R" }), 1000, "R"),
      A2: block({ block: "seal" }),
      FB: block({ block: "arc", target: "EMLOS" }),
      Z: route("crack"),
      X: route("stalk"),
    },
    tags: ["option", "rocket", "motion", "perimeter", "speed"],
    situations: ["1st-down", "plus-territory", "sideline"],
    coaching: { keys: "Full-speed motion means the pitch man is already at the edge when the quarterback gets there." },
  }),

  play({
    id: "fb-diamond-veer",
    name: "Diamond Veer",
    aliases: ["Pistol Veer", "Diamond Triple"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "pistol-diamond",
    personnelId: "21",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "dive"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "triple", "diamond", "pistol"],
    situations: ["1st-down", "short-yardage", "goal-line"],
    coaching: { keys: "The same triple read from a pistol depth, which gives the dive back a downhill start." },
  }),

  play({
    id: "fb-double-option-weak",
    name: "Weak Option",
    aliases: ["Backside Option", "Weak Speed"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "QB", aim: "backside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "backside", ifTake: { pitch: "A2" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("backside-C", "stretch"),
      A2: route("arrow", { toSide: "L" }, { startDelayMs: 120 }),
      A1: block({ block: "seal" }),
      FB: carry("playside-B", "dive"),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "weak-side", "misdirection", "two-way"],
    situations: ["1st-down", "2nd-short", "vs-cover-3"],
    coaching: { keys: "Dive fake to the strength, then option the other way against a defence that has already flowed." },
  }),

  play({
    id: "fb-counter-trey-option",
    name: "Counter Option",
    aliases: ["Counter Speed", "GT Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "counter", carrier: "QB", aim: "backside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "backside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("backside-C", "counter-step"),
      A1: motion("across", route("arrow", { toSide: "L" }), 1000, "L"),
      A2: block({ block: "kickout", target: "EMLOS" }),
      FB: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "counter", "motion", "misdirection"],
    situations: ["1st-down", "plus-territory", "opening-script"],
    coaching: { keys: "Motion one way, run the other, and still have a pitch phase on the back end." },
  }),

  play({
    id: "fb-fb-follow-wedge",
    name: "FB Wedge",
    aliases: ["Wedge", "Fullback Wedge"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "full-house-t",
    personnelId: "23",
    run: { scheme: "duo", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      RB: block({ block: "base", target: "second-level" }),
      A1: block({ block: "base", target: "second-level" }),
      Y: block({ block: "down" }),
      H: block({ block: "down" }),
    },
    tags: ["wedge", "short-yardage", "interior", "clock"],
    situations: ["4th-short", "3rd-short", "goal-line", "four-minute"],
    coaching: { commentary: "Three backs and two tight ends on fourth and one. Everyone in the stadium knows and it works anyway." },
  }),

  play({
    id: "fb-trap-option",
    name: "Trap Option",
    aliases: ["Trap Pitch", "G Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "trap", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 180 }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["trap", "option", "interior", "answer"],
    situations: ["2nd-short", "3rd-short", "short-yardage"],
    coaching: { keys: "Trap the tackle who has been squeezing the dive and keep the pitch phase behind it." },
  }),

  play({
    id: "fb-throwback-post",
    name: "Throwback Post",
    aliases: ["Backside Post", "Option Throwback"],
    philosophy: "flexbone",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    protection: "max-protect",
    concept: "throwback",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "A2"] }],
    assignments: {
      QB: pass("boot", "FB"),
      X: route("post", { depth: 18 }, { priorityOrder: 1 }),
      A2: route("wheel", { depth: 14 }, { priorityOrder: 2, startDelayMs: 200 }),
      Z: route("go", { depth: 16 }, { priorityOrder: 3 }),
      A1: block({ block: "hinge" }),
      FB: block({ block: "pass-set" }),
    },
    tags: ["play-action", "throwback", "shot", "option-action"],
    situations: ["plus-territory", "1st-down", "vs-cover-1", "opening-script"],
    coaching: { commentary: "Two throws a game, and the safeties have been in the run fit since the opening drive." },
  }),

  play({
    id: "fb-fullback-pass",
    name: "Fullback Pass",
    aliases: ["FB Pop", "Dive Pass"],
    philosophy: "flexbone",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    concept: "pop",
    primary: "FB",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["FB", "Z", "X"] }],
    assignments: {
      QB: pass("1step"),
      FB: route("pop", undefined, { priorityOrder: 1 }),
      A1: route("wheel", { depth: 12 }, { priorityOrder: 2 }),
      Z: route("go", { depth: 16 }, { priorityOrder: 3 }),
      X: route("post", { depth: 16 }, { priorityOrder: 4 }),
      A2: block({ block: "hinge" }),
    },
    tags: ["pop", "play-action", "seam", "surprise"],
    situations: ["red-zone", "3rd-short", "goal-line", "1st-down"],
    coaching: { keys: "The linebackers step up on the dive every single snap. This is the ball over their heads." },
  }),

  play({
    id: "fb-option-screen",
    name: "Option Screen",
    aliases: ["Slot Now", "Veer Now"],
    philosophy: "flexbone",
    family: "screen",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    protection: "screen-release",
    concept: "now-screen",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z"] }],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      Z: route("screen", { toSide: "R" }, { priorityOrder: 1, startDelayMs: 200 }),
      A1: block({ block: "stalk" }),
      A2: block({ block: "hinge" }),
      X: route("stalk"),
    },
    tags: ["screen", "now", "perimeter", "answer"],
    situations: ["2nd-long", "1st-down", "vs-cover-0", "blitz-beater"],
    coaching: { keys: "When the corners start crashing on the pitch, throw it out there before they arrive." },
  }),

  play({
    id: "fb-qb-draw-option",
    name: "QB Draw",
    aliases: ["Option Draw", "Quarterback Draw"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "QB", aim: "playside-A" },
    primary: "QB",
    assignments: {
      QB: carry("playside-A", "downhill"),
      FB: block({ block: "base", target: "PSLB" }),
      A1: route("arrow", { toSide: "R" }),
      A2: route("arrow", { toSide: "L" }),
      Z: route("go", { depth: 12 }),
      X: route("go", { depth: 12 }),
    },
    tags: ["draw", "qb-run", "answer", "surprise"],
    situations: ["2nd-long", "3rd-medium", "blitz-beater"],
    coaching: { keys: "Show the option pitch phase, then run straight through where the linebackers were standing." },
  }),

  play({
    id: "fb-double-a-back-motion",
    name: "Twirl Veer",
    aliases: ["Twirl Motion", "Return Veer"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A2" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A2: motion("return", route("arrow", { toSide: "R" }), 1400, "R"),
      A1: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "motion", "twirl", "disguise"],
    situations: ["1st-down", "2nd-short", "opening-script"],
    coaching: { keys: "Motion out and back so the defence has to re-declare its edge twice before the snap." },
  }),

  play({
    id: "fb-goal-line-veer",
    name: "Goal Line Veer",
    aliases: ["Heavy Veer", "Short Yardage Triple"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "goal-line-heavy",
    personnelId: "22",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
    ],
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "dive"),
      FB: block({ block: "arc", target: "EMLOS" }),
      Y: block({ block: "down" }),
      H: block({ block: "down" }),
      V: block({ block: "down" }),
    },
    tags: ["option", "goal-line", "heavy", "short-yardage"],
    situations: ["goal-line", "4th-short", "3rd-short", "red-zone"],
    coaching: { keys: "Inside the five the read shortens to one man and the give is usually right." },
  }),

  play({
    id: "fb-toss-crack-option",
    name: "Crack Toss",
    aliases: ["Toss Crack", "Perimeter Toss"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "A1", aim: "playside-D" },
    primary: "A1",
    assignments: {
      QB: pitch("A1"),
      A1: carry("playside-D", "stretch"),
      Z: route("crack"),
      FB: block({ block: "arc", target: "EMLOS" }),
      A2: block({ block: "seal" }),
      X: route("stalk"),
    },
    tags: ["toss", "crack", "perimeter", "speed"],
    situations: ["1st-down", "plus-territory", "sideline"],
    coaching: { keys: "The receiver cracks the force player and the pitch gets outside of it." },
  }),

  play({
    id: "fb-lead-dive",
    name: "Lead Dive",
    aliases: ["Belly Dive", "Lead Belly"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "duo", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: block({ block: "wrap", target: "PSLB" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["dive", "lead", "interior", "short-yardage"],
    situations: ["2nd-short", "3rd-short", "short-yardage", "four-minute"],
    coaching: { keys: "No read at all. Straight downhill with a lead blocker, which keeps the dive honest for the option." },
  }),

  play({
    id: "fb-flood-sprint",
    name: "Sprint Flood",
    aliases: ["Sprint Out", "Roll Flood"],
    philosophy: "flexbone",
    family: "pass",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    protection: "sprint-right",
    concept: "flood",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["A1", "Z", "X"] }],
    assignments: {
      QB: pass("sprint"),
      A1: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      Z: route("sail", { depth: 12 }, { priorityOrder: 2 }),
      X: route("over", { depth: 16 }, { priorityOrder: 3, startDelayMs: 200 }),
      FB: block({ block: "hinge" }),
      A2: block({ block: "pass-set" }),
    },
    tags: ["sprint-out", "flood", "three-level", "sideline"],
    situations: ["3rd-medium", "2nd-long", "vs-zone", "sideline"],
    coaching: { keys: "Move the launch point. An option quarterback throwing on the run is a harder problem than one in a pocket." },
  }),

  play({
    id: "fb-shovel-triple",
    name: "Shovel Triple",
    aliases: ["Shovel Option", "Inside Shovel"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "power", carrier: "A2", aim: "playside-B" },
    primary: "A2",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { give: "A2" }, ifNot: { keep: "QB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-D", "stretch"),
      A2: route("shovel", { toSide: "R" }, { priorityOrder: 1 }),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 200 }),
      FB: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["shovel", "option", "triple", "red-zone"],
    situations: ["red-zone", "3rd-short", "goal-line", "plus-territory"],
    coaching: { keys: "Three ways to get the ball to three different players on the same snap, all inside twelve yards." },
  }),
];

export const WING_T: PlaySpec[] = [
  play({
    id: "wt-buck-sweep",
    name: "Buck Sweep",
    aliases: ["Sweep", "Buck Sweep", "Buck"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "A1", aim: "playside-C" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "A1"),
      A1: carry("playside-C", "stretch"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["buck-series", "sweep", "both-guards-pull", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory", "opening-script"],
    coaching: {
      install: "Both guards pull. The wingback takes it wide behind them and the fullback fakes the trap.",
      commentary: "Everything else in the Buck series is a lie told about this play.",
    },
  }),

  play({
    id: "wt-fb-trap",
    name: "Buck Trap",
    aliases: ["FB Trap", "Buck Trap", "Trap"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "trap", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: route("arrow", { toSide: "R" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["buck-series", "trap", "quick-hitting", "series"],
    situations: ["short-yardage", "1st-down", "3rd-short"],
    coaching: { install: "Identical backfield action to the sweep. The fullback keeps it and runs through the trap." },
  }),

  play({
    id: "wt-waggle",
    name: "Waggle",
    aliases: ["Buck Waggle", "Boot", "Waggle"],
    philosophy: "wing-t",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "half-slide",
    concept: "boot-flood",
    primary: "A1",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "backside", progression: ["A1", "Y", "X"] }],
    assignments: {
      QB: pass("boot", "FB"),
      A1: route("flat", { toSide: "L" }, { priorityOrder: 1 }),
      Y: route("drag", { toSide: "L", depthAdj: 6 }, { priorityOrder: 2 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      RB: block({ block: "hinge" }),
    },
    tags: ["buck-series", "waggle", "boot", "flood", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-cover-3"],
    coaching: {
      keys: "Three levels away from the sweep flow. The linebackers have already left.",
      commentary: "The third play of the series, and the one that scores.",
    },
  }),

  play({
    id: "wt-down",
    name: "Down",
    aliases: ["Off Tackle", "Down", "Belly"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "downhill"),
      FB: block({ block: "climb", target: "PSLB" }),
      A1: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["down-series", "off-tackle", "series"],
    situations: ["1st-down", "short-yardage", "red-zone"],
    coaching: { install: "Down blocks inside with the wing sealing the edge." },
  }),

  play({
    id: "wt-belly",
    name: "Belly",
    aliases: ["Belly", "Belly Option"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "downhill"),
      A1: block({ block: "arc" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "base" }),
      X: route("stalk"),
    },
    tags: ["down-series", "belly", "fullback", "series"],
    situations: ["short-yardage", "1st-down", "four-minute"],
    coaching: { install: "Fullback downhill off the belly fake. The complement to Down." },
  }),

  play({
    id: "wt-belly-pass",
    name: "Belly Pass",
    aliases: ["Belly Pass", "Down Pass"],
    philosophy: "wing-t",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "big-on-big",
    concept: "pa-post",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Y", "A1"] }],
    assignments: {
      QB: pass("5step", "FB"),
      X: route("post", { depth: 12 }, { priorityOrder: 1 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 2 }),
      A1: route("flat", { toSide: "R" }, { startDelayMs: 260, priorityOrder: 3 }),
      RB: block({ block: "hinge" }),
    },
    tags: ["down-series", "play-action", "post-corner", "series"],
    situations: ["1st-down", "plus-territory", "vs-cover-1"],
    coaching: { keys: "Belly fake, then a post-corner combination on a safety who is already downhill." },
  }),

  play({
    id: "wt-jet-sweep",
    name: "Jet Sweep",
    aliases: ["Jet", "Fly", "Jet Sweep"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "outside-zone", carrier: "A1", aim: "playside-D" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "A1"),
      A1: motion("jet", carry("playside-D", "stretch"), 1200, "L"),
      FB: block({ block: "arc" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "reach" }),
      X: route("crack"),
    },
    tags: ["jet-series", "jet", "motion", "perimeter", "series"],
    situations: ["1st-down", "opening-script", "plus-territory"],
    coaching: { keys: "Full speed at the snap. The motion is the play." },
  }),

  play({
    id: "wt-jet-trap",
    name: "Jet Trap",
    aliases: ["Jet Counter", "Jet Trap"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "trap", carrier: "FB", aim: "backside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      A1: motion("jet", route("arrow", { toSide: "L" }), 1200, "L"),
      FB: carry("backside-B", "dive"),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["jet-series", "trap", "misdirection", "series"],
    situations: ["1st-down", "short-yardage", "3rd-short"],
    coaching: { install: "Jet motion pulls the front sideways, the fullback traps back against it." },
  }),

  play({
    id: "wt-counter-criss-cross",
    name: "Counter Criss-Cross",
    aliases: ["Criss Cross", "Double Reverse"],
    philosophy: "wing-t",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "counter", carrier: "A1", aim: "backside-D" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "stretch"),
      A1: motion("across", carry("backside-D", "stretch"), 900, "L"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      X: route("crack"),
    },
    tags: ["trick", "criss-cross", "reverse", "misdirection"],
    situations: ["1st-down", "plus-territory", "opening-script"],
    coaching: { commentary: "Only works after Buck Sweep has gained ground twice." },
  }),

  play({
    id: "wt-tackle-trap",
    name: "Tackle Trap",
    aliases: ["Tackle Trap", "T Trap"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "counter", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "counter-step"),
      FB: block({ block: "climb", target: "PSLB" }),
      A1: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["trap", "tackle-pull", "counter"],
    situations: ["1st-down", "short-yardage"],
    coaching: { install: "The tackle pulls and traps, which nobody scouts for." },
  }),

  play({
    id: "wt-rollout",
    name: "Rollout Pass",
    aliases: ["Roll", "Sprint Out", "Rollout"],
    philosophy: "wing-t",
    family: "pass",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "half-slide",
    concept: "sprint-flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["A1", "Y", "X"] }],
    assignments: {
      QB: pass("sprint"),
      A1: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("sail", undefined, { priorityOrder: 2 }),
      X: route("post", { depth: 14 }, { priorityOrder: 3 }),
      FB: block({ block: "arc" }),
      RB: block({ block: "hinge" }),
    },
    tags: ["sprint-out", "flood", "three-level", "run-pass"],
    situations: ["3rd-medium", "sideline", "red-zone", "vs-cover-3"],
    coaching: { keys: "Half the field, three levels, and the quarterback can always run it." },
  }),

  play({
    id: "wt-power-wing",
    name: "Power Wing",
    aliases: ["Wing Power", "Down G"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "downhill"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      A1: block({ block: "down" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["power", "gap-scheme", "wingback", "downhill"],
    situations: ["1st-down", "3rd-short", "red-zone", "short-yardage"],
    coaching: {
      keys: "The wing blocks down and the fullback kicks. Everything inside is angles.",
    },
  }),

  play({
    id: "wt-quick-pitch",
    name: "Quick Pitch",
    aliases: ["Pitch Sweep", "Fast Pitch"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pitch("RB"),
      RB: carry("playside-D", "stretch"),
      A1: block({ block: "arc" }),
      FB: block({ block: "seal" }),
      Y: block({ block: "reach" }),
      X: route("crack"),
    },
    tags: ["pitch", "sweep", "perimeter", "speed"],
    situations: ["1st-down", "plus-territory", "sideline"],
    coaching: { install: "No pulls and no fakes. This one beats the defence to the edge with pure width." },
  }),

  play({
    id: "wt-buck-sweep-pass",
    name: "Buck Sweep Pass",
    aliases: ["Sweep Pass", "Wingback Pass"],
    philosophy: "wing-t",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    concept: "halfback-pass",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Y"] }],
    assignments: {
      QB: pitch("A1"),
      A1: pass("sprint"),
      X: route("post", { depth: 16 }, { priorityOrder: 1 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 2, startDelayMs: 200 }),
      FB: block({ block: "arc" }),
      RB: block({ block: "hinge" }),
    },
    tags: ["trick", "halfback-pass", "sweep-action", "shot"],
    situations: ["plus-territory", "1st-down", "opening-script", "vs-cover-3"],
    coaching: {
      commentary: "The safety has come downhill on Buck Sweep all night. He gets one chance to be right.",
    },
  }),

  play({
    id: "wt-jet-reverse",
    name: "Jet Reverse",
    aliases: ["Fly Reverse", "Jet Counter"],
    philosophy: "wing-t",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "counter", carrier: "X", aim: "backside-D" },
    primary: "X",
    assignments: {
      QB: pass("1step", "A1"),
      A1: motion("jet", carry("playside-D", "stretch"), 1000, "R"),
      X: carry("backside-D", "stretch"),
      FB: block({ block: "arc" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "reach" }),
    },
    tags: ["trick", "reverse", "jet", "misdirection", "series"],
    situations: ["1st-down", "plus-territory", "opening-script"],
    coaching: { keys: "Run Jet Sweep four times first. Save this one until the backside corner starts chasing." },
  }),

  play({
    id: "wt-fb-wedge",
    name: "Fullback Wedge",
    aliases: ["Wedge", "Quarterback Sneak Wedge"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "duo", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      RB: block({ block: "base", target: "second-level" }),
      A1: block({ block: "down" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["wedge", "short-yardage", "interior", "clock"],
    situations: ["3rd-short", "4th-short", "goal-line", "four-minute"],
    coaching: {
      install: "Everyone squeezes to the ball and drives as one surface. The back follows the pile.",
    },
  }),

  play({
    id: "wt-throwback-screen",
    name: "Throwback Screen",
    aliases: ["Sweep Screen", "Backside Screen"],
    philosophy: "wing-t",
    family: "screen",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "screen-release",
    concept: "throwback-screen",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "BSLB", progression: ["RB"] }],
    assignments: {
      QB: pass("boot", "A1"),
      A1: route("arrow", { toSide: "R" }),
      RB: route("screen", { toSide: "L" }, { priorityOrder: 1, startDelayMs: 400 }),
      FB: block({ block: "arc" }),
      Y: block({ block: "hinge" }),
      X: block({ block: "stalk" }),
    },
    tags: ["screen", "throwback", "sweep-action", "answer", "backside"],
    situations: ["2nd-long", "3rd-medium", "blitz-beater", "vs-man"],
    coaching: { keys: "Sweep flow takes the second level with it. The screen goes where they left." },
  }),

  play({
    id: "wt-sprint-flood",
    name: "Sprint Flood",
    aliases: ["Sprint Out", "Roll Flood"],
    philosophy: "wing-t",
    family: "pass",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "sprint-right",
    concept: "flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", progression: ["A1", "Y", "X"] }],
    assignments: {
      QB: pass("sprint"),
      A1: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("sail", { depth: 12 }, { priorityOrder: 2 }),
      X: route("over", { depth: 16 }, { priorityOrder: 3, startDelayMs: 200 }),
      FB: block({ block: "hinge" }),
      RB: block({ block: "pass-set" }),
    },
    tags: ["sprint-out", "flood", "three-level", "sideline"],
    situations: ["3rd-medium", "2nd-long", "vs-zone", "vs-cover-3"],
    coaching: {
      keys: "Three receivers on one side at three depths. The flat defender covers one of them.",
    },
  }),

  play({
    id: "wt-double-wing-sweep",
    name: "Double Wing Sweep",
    aliases: ["DW Sweep", "Wing Sweep"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "double-wing-right",
    personnelId: "22",
    run: { scheme: "pin-pull", carrier: "A1", aim: "playside-D" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "A1"),
      A1: carry("playside-D", "stretch"),
      A2: block({ block: "wrap", target: "PSLB" }),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      H: block({ block: "down" }),
    },
    tags: ["sweep", "double-wing", "pullers", "series"],
    situations: ["1st-down", "short-yardage", "four-minute"],
    coaching: { keys: "Two pullers and two wings mean four blockers arrive at the edge before the defence can widen." },
  }),

  play({
    id: "wt-double-wing-trap",
    name: "Double Wing Trap",
    aliases: ["DW Trap", "Wedge Trap"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "double-wing-right",
    personnelId: "22",
    run: { scheme: "trap", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: block({ block: "seal" }),
      A2: block({ block: "seal" }),
      Y: block({ block: "down" }),
      H: block({ block: "down" }),
    },
    tags: ["trap", "double-wing", "interior", "series"],
    situations: ["2nd-short", "3rd-short", "short-yardage", "goal-line"],
    coaching: { keys: "The tackle chasing the sweep gets trapped from the inside on the very next snap." },
  }),

  play({
    id: "wt-double-wing-waggle",
    name: "Double Wing Waggle",
    aliases: ["DW Waggle", "Wing Boot"],
    philosophy: "wing-t",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "double-wing-right",
    personnelId: "22",
    protection: "sprint-right",
    concept: "waggle",
    primary: "A2",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "backside", progression: ["A2", "H", "Y"] }],
    assignments: {
      QB: pass("boot", "A1"),
      A1: route("arrow", { toSide: "R" }),
      A2: route("flat", { toSide: "L" }, { priorityOrder: 1 }),
      H: route("sail", { depth: 12 }, { priorityOrder: 2 }),
      Y: route("over", { depth: 14 }, { priorityOrder: 3, startDelayMs: 200 }),
      FB: block({ block: "hinge" }),
    },
    tags: ["waggle", "play-action", "boot", "three-level", "series"],
    situations: ["1st-down", "3rd-medium", "vs-cover-3", "plus-territory"],
    coaching: { commentary: "The third play of the series, and the one that scores after the first two have done their work." },
  }),

  play({
    id: "wt-buck-counter",
    name: "Buck Counter",
    aliases: ["Counter Buck", "Sweep Counter"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "counter", carrier: "FB", aim: "backside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("backside-B", "counter-step"),
      A1: block({ block: "arc" }),
      RB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["counter", "buck-series", "misdirection", "series"],
    situations: ["1st-down", "2nd-short", "short-yardage"],
    coaching: { keys: "Identical backfield action to Buck Sweep with the ball going back inside." },
  }),

  play({
    id: "wt-guard-trap-pass",
    name: "Trap Pass",
    aliases: ["Trap Play Action", "Guard Trap Pass"],
    philosophy: "wing-t",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "max-protect",
    concept: "trap-action",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "SS", progression: ["Y", "X", "A1"] }],
    assignments: {
      QB: pass("5step", "FB"),
      Y: route("corner", { depth: 12 }, { priorityOrder: 1 }),
      X: route("post", { depth: 16 }, { priorityOrder: 2 }),
      A1: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      RB: block({ block: "pass-set" }),
      FB: block({ block: "pass-set" }),
    },
    tags: ["play-action", "trap-action", "shot", "series"],
    situations: ["1st-down", "plus-territory", "vs-cover-1", "red-zone"],
    coaching: { keys: "The linebackers have filled the trap all game. The corner route replaces where they were." },
  }),

  play({
    id: "wt-belly-keep",
    name: "Belly Keep",
    aliases: ["Belly Option", "Keep Pass"],
    philosophy: "wing-t",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "QB", aim: "playside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-C", "downhill"),
      FB: carry("playside-A", "dive"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 200 }),
      RB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["belly", "option", "keep", "series"],
    situations: ["1st-down", "2nd-short", "red-zone"],
    coaching: { keys: "Belly fake to the fullback, then attack the edge with a pitch phase behind it." },
  }),

  play({
    id: "wt-jet-wham",
    name: "Jet Wham",
    aliases: ["Wham", "Jet Trap Wham"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "trap", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: motion("jet", block({ block: "trap", target: "first-level" }), 1000, "L"),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["wham", "jet", "motion", "trap", "series"],
    situations: ["2nd-short", "1st-down", "short-yardage"],
    coaching: { keys: "The motion man traps the tackle who has started chasing jet sweep." },
  }),

  play({
    id: "wt-unbalanced-sweep",
    name: "Unbalanced Sweep",
    aliases: ["Tackle Over Sweep", "Heavy Sweep"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "unbalanced-heavy-right",
    personnelId: "13",
    run: { scheme: "pin-pull", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-D", "stretch"),
      H: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      V: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["sweep", "unbalanced", "pullers", "formation-stress"],
    situations: ["1st-down", "short-yardage", "plus-territory"],
    coaching: { keys: "An extra lineman on the sweep side means one more blocker than the defence has aligned to handle." },
  }),

  play({
    id: "wt-fb-belly-weak",
    name: "Weak Belly",
    aliases: ["Belly Weak", "Backside Belly"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "inside-zone", carrier: "FB", aim: "backside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("backside-B", "downhill"),
      RB: block({ block: "seal" }),
      A1: block({ block: "arc" }),
      Y: block({ block: "hinge" }),
      X: route("stalk"),
    },
    tags: ["belly", "weak-side", "interior", "series"],
    situations: ["1st-down", "2nd-short", "short-yardage"],
    coaching: { keys: "Run away from the wing after two quarters of running toward him." },
  }),

  play({
    id: "wt-waggle-throwback",
    name: "Waggle Throwback",
    aliases: ["Throwback Waggle", "Boot Return"],
    philosophy: "wing-t",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "sprint-right",
    concept: "throwback",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["X", "A1"] }],
    assignments: {
      QB: pass("boot", "A1"),
      A1: route("wheel", { depth: 12 }, { priorityOrder: 2 }),
      X: route("post", { depth: 18 }, { priorityOrder: 1 }),
      Y: route("over", { depth: 14 }, { priorityOrder: 3 }),
      FB: block({ block: "hinge" }),
      RB: block({ block: "pass-set" }),
    },
    tags: ["trick", "throwback", "waggle", "shot"],
    situations: ["plus-territory", "1st-down", "opening-script", "vs-cover-3"],
    coaching: { commentary: "Everyone chases the waggle. The throw goes back to the field they left." },
  }),

  play({
    id: "wt-tackle-eligible",
    name: "Tackle Eligible",
    aliases: ["Heavy Trick", "Report Eligible"],
    philosophy: "wing-t",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "unbalanced-heavy-right",
    personnelId: "13",
    protection: "max-protect",
    concept: "eligible",
    primary: "V",
    reads: [{ order: 1, type: "progression", key: "SS", progression: ["V", "X"] }],
    assignments: {
      QB: pass("5step", "RB"),
      V: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      X: route("post", { depth: 16 }, { priorityOrder: 2 }),
      H: route("go", { depth: 12 }, { priorityOrder: 3 }),
      Y: block({ block: "pass-set" }),
    },
    tags: ["trick", "eligible", "goal-line", "unbalanced"],
    situations: ["goal-line", "red-zone", "3rd-short", "plus-territory"],
    coaching: {
      keys: "The eligible player has to report to the official before the snap, and nobody covers him the first time.",
    },
  }),

  play({
    id: "wt-jet-pass",
    name: "Jet Pass",
    aliases: ["Fly Pass", "Jet Play Action"],
    philosophy: "wing-t",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "sprint-right",
    concept: "jet-action",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Y", "RB"] }],
    assignments: {
      QB: pass("boot", "A1"),
      A1: motion("jet", route("arrow", { toSide: "L" }), 1000, "L"),
      X: route("post", { depth: 16 }, { priorityOrder: 1 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 2 }),
      RB: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      FB: block({ block: "hinge" }),
    },
    tags: ["play-action", "jet", "motion", "shot"],
    situations: ["1st-down", "plus-territory", "vs-cover-3", "opening-script"],
    coaching: { keys: "Full-speed motion moves the second level sideways. Throw behind it." },
  }),

  play({
    id: "wt-down-option",
    name: "Down Option",
    aliases: ["Wing Option", "Down G Option"],
    philosophy: "wing-t",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "QB", aim: "playside-D" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-D", "stretch"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 120 }),
      FB: block({ block: "arc", target: "EMLOS" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["option", "down-blocking", "perimeter", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: { keys: "Down blocks inside and an option phase outside, which is Wing-T geometry with a modern read on the end." },
  }),

  play({
    id: "wt-shovel-pass",
    name: "Shovel Pass",
    aliases: ["Shovel", "Inside Shovel"],
    philosophy: "wing-t",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    concept: "shovel",
    primary: "A1",
    reads: [{ order: 1, type: "progression", key: "DE", keySide: "playside", progression: ["A1", "Y"] }],
    assignments: {
      QB: pass("sprint"),
      A1: route("shovel", { toSide: "L" }, { priorityOrder: 1 }),
      Y: route("corner", { depth: 10 }, { priorityOrder: 2 }),
      FB: block({ block: "arc" }),
      RB: block({ block: "seal" }),
      X: route("stalk"),
    },
    tags: ["shovel", "trick", "misdirection", "red-zone"],
    situations: ["red-zone", "3rd-short", "goal-line", "plus-territory"],
    coaching: { keys: "The quarterback runs at the edge and flips it back underneath to the wing." },
  }),

  play({
    id: "wt-i-power",
    name: "I Power",
    aliases: ["Wing I Power", "Power Right"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "i-twins-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "downhill"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Z: route("stalk"),
      H: route("stalk"),
      X: route("stalk"),
    },
    tags: ["power", "i-formation", "downhill", "gap-scheme"],
    situations: ["1st-down", "3rd-short", "short-yardage", "four-minute"],
    coaching: { keys: "Same power rules with an I backfield, so the tailback gets downhill with speed." },
  }),

  play({
    id: "wt-criss-cross-pass",
    name: "Criss Cross Pass",
    aliases: ["Double Reverse Pass", "Criss Cross"],
    philosophy: "wing-t",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    concept: "reverse-pass",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Y"] }],
    assignments: {
      QB: pitch("A1"),
      A1: pass("sprint"),
      X: route("go", { depth: 18 }, { priorityOrder: 1 }),
      Y: route("post", { depth: 14 }, { priorityOrder: 2, startDelayMs: 200 }),
      RB: block({ block: "arc" }),
      FB: block({ block: "hinge" }),
    },
    tags: ["trick", "reverse-pass", "shot", "series"],
    situations: ["plus-territory", "opening-script", "must-score", "vs-cover-1"],
    coaching: { commentary: "Once a season, and only after the criss cross run has already scored." },
  }),

  play({
    id: "wt-fullback-counter",
    name: "Fullback Counter",
    aliases: ["FB Counter", "Counter Dive"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "double-wing-right",
    personnelId: "22",
    run: { scheme: "counter", carrier: "FB", aim: "backside-A" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("backside-A", "counter-step"),
      A1: block({ block: "seal" }),
      A2: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      H: block({ block: "down" }),
    },
    tags: ["counter", "fullback", "interior", "misdirection"],
    situations: ["2nd-short", "3rd-short", "short-yardage", "goal-line"],
    coaching: { keys: "One step to the sweep side, then straight back into the gap the flow vacated." },
  }),

  play({
    id: "wt-boot-flood-weak",
    name: "Weak Boot",
    aliases: ["Backside Boot", "Weak Waggle"],
    philosophy: "wing-t",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "sprint-right",
    concept: "boot-flood",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "backside", progression: ["RB", "X", "Y"] }],
    assignments: {
      QB: pass("boot", "FB"),
      RB: route("flat", { toSide: "L" }, { priorityOrder: 1 }),
      X: route("sail", { depth: 12 }, { priorityOrder: 2 }),
      Y: route("over", { depth: 16 }, { priorityOrder: 3, startDelayMs: 250 }),
      A1: block({ block: "hinge" }),
      FB: carry("playside-A", "dive"),
    },
    tags: ["boot", "play-action", "flood", "weak-side"],
    situations: ["1st-down", "3rd-medium", "vs-cover-3", "sideline"],
    coaching: { keys: "Belly action to the strength and a three-level flood away from it." },
  }),
];
