/**
 * Flexbone triple option and Wing-T.
 *
 * Both are SERIES offenses, which is the thing a flat library gets wrong: the
 * sweep pulls defenders wide, the trap punishes them for chasing, and the
 * waggle burns them for crashing. Each play is tagged with its series so the
 * library can present them as a family rather than as twelve unrelated cards.
 *
 * The triple option is stored as two ordered reads on one play — dive then
 * pitch — which is exactly the same mechanism an RPO uses.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, carry, motion, pass, pitch, play, route } from "../kit.ts";

const TACKLE = ["11man"] as const;

export const FLEXBONE: PlaySpec[] = [
  play({
    id: "fb-inside-veer",
    name: "Inside Veer",
    aliases: ["Triple Option", "Veer", "Inside Veer"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["triple-option", "veer", "dive", "pitch", "two-reads", "series"],
    situations: ["1st-down", "short-yardage", "4th-short", "four-minute", "goal-line"],
    coaching: {
      install: "Read the first man outside the playside tackle for the give. Read the next one for the pitch.",
      commentary: "Two defenders blocked with two decisions instead of two blockers. That is the whole offense.",
    },
  }),

  play({
    id: "fb-midline-triple",
    name: "Midline Triple",
    aliases: ["Midline", "Midline Triple"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["triple-option", "midline", "dive", "interior", "series"],
    situations: ["short-yardage", "1st-down", "goal-line", "4th-short"],
    coaching: { install: "The read moves inside to the playside tackle. Answer to a defense widening for the veer." },
  }),

  play({
    id: "fb-midline-double",
    name: "Midline Double",
    aliases: ["Midline Double", "Double Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "midline", "double", "two-way"],
    situations: ["short-yardage", "1st-down", "3rd-short"],
    coaching: { install: "One read, no pitch. Simpler when the pitch key is unreadable." },
  }),

  play({
    id: "fb-outside-veer",
    name: "Outside Veer",
    aliases: ["Load Option", "Outside Veer"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "FB", aim: "playside-C" },
    primary: "FB",
    reads: [
      { order: 1, type: "option-dive", key: "EMLOS", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "FB" } },
    ],
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-C", "stretch"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "outside-veer", "load", "edge"],
    situations: ["1st-down", "plus-territory"],
    coaching: { install: "The dive track moves outside the tackle and the slot loads the support defender." },
  }),

  play({
    id: "fb-rocket-toss",
    name: "Rocket Toss",
    aliases: ["Rocket", "Rocket Toss", "Fast Toss"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "A1", aim: "playside-D" },
    primary: "A1",
    assignments: {
      QB: pitch("A1"),
      A1: motion("jet", carry("playside-D", "stretch"), 1100, "R"),
      FB: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("crack"),
      X: route("stalk"),
    },
    tags: ["toss", "motion", "perimeter", "speed", "series"],
    situations: ["1st-down", "opening-script", "plus-territory"],
    coaching: {
      keys: "Pre-snap motion, immediate pitch. The fastest way a flexbone gets to the edge.",
      commentary: "It exists so the defense cannot sit inside waiting for the veer.",
    },
  }),

  play({
    id: "fb-counter-option",
    name: "Counter Option",
    aliases: ["Counter Option", "Reverse Option"],
    philosophy: "flexbone",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "counter", carrier: "QB", aim: "backside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "backside", ifTake: { pitch: "A2" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("backside-C", "counter-step"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      A2: route("arrow", { toSide: "L" }, { startDelayMs: 200 }),
      A1: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "counter", "misdirection", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: { install: "Veer action one way, option the other. Punishes a defense that has started to flow." },
  }),

  play({
    id: "fb-fb-trap",
    name: "FB Trap",
    aliases: ["Fullback Trap", "Trap"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "trap", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["trap", "fullback", "quick-hitting", "series"],
    situations: ["short-yardage", "1st-down", "3rd-short"],
    coaching: { install: "Answer to a tackle who has learned to crash the dive." },
  }),

  play({
    id: "fb-qb-follow",
    name: "QB Follow",
    aliases: ["Follow", "QB Follow", "Q Iso"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "power", carrier: "QB", aim: "playside-A" },
    primary: "QB",
    assignments: {
      QB: carry("playside-A", "downhill"),
      FB: carry("playside-B", "dive"),
      A1: block({ block: "arc" }),
      A2: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["qb-run", "follow", "short-yardage", "series"],
    situations: ["short-yardage", "goal-line", "4th-short"],
    coaching: { install: "The fullback carries out the dive fake and the quarterback follows him into the same gap." },
  }),

  play({
    id: "fb-veer-pass",
    name: "Veer Pass",
    aliases: ["Play Action Veer", "Veer Pass"],
    philosophy: "flexbone",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    protection: "half-slide",
    concept: "option-play-action",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Z", "A1", "X"] }],
    assignments: {
      QB: pass("boot", "FB"),
      Z: route("post", { depth: 12 }, { priorityOrder: 1 }),
      A1: route("wheel", undefined, { priorityOrder: 2 }),
      X: route("go", undefined, { priorityOrder: 3 }),
      A2: route("flat", { toSide: "L" }, { startDelayMs: 300 }),
    },
    tags: ["play-action", "option-action", "shot", "post-wheel"],
    situations: ["1st-down", "plus-territory", "vs-cover-1", "opening-script"],
    coaching: {
      keys: "Two throws all game, and this is one of them. The safeties have been in the run fit for three quarters.",
    },
  }),

  play({
    id: "fb-toss-sweep",
    name: "Toss Sweep",
    aliases: ["Sweep", "Toss Sweep"],
    philosophy: "flexbone",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "outside-zone", carrier: "A1", aim: "playside-D" },
    primary: "A1",
    assignments: {
      QB: pitch("A1"),
      A1: carry("playside-D", "stretch"),
      FB: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["toss", "sweep", "perimeter"],
    situations: ["1st-down", "plus-territory"],
    coaching: { install: "Straight pitch to the slot without motion. Slower than Rocket, better angles." },
  }),

  play({
    id: "fb-halfback-pass",
    name: "Halfback Pass",
    aliases: ["Trick", "HB Pass", "Throwback"],
    philosophy: "flexbone",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    concept: "halfback-pass",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["X", "Z"] }],
    assignments: {
      QB: pitch("A1"),
      A1: pass("sprint"),
      X: route("go", undefined, { priorityOrder: 1 }),
      Z: route("post", { depth: 14 }, { priorityOrder: 2 }),
      FB: block({ block: "arc" }),
      A2: block({ block: "hinge" }),
    },
    tags: ["trick", "halfback-pass", "shot", "sweep-action"],
    situations: ["plus-territory", "1st-down", "opening-script", "vs-cover-1"],
    coaching: { commentary: "Once a game, off the look that has already gained forty yards on the ground." },
  }),

  play({
    id: "fb-veer-reverse",
    name: "Veer Reverse",
    aliases: ["Reverse", "Slot Reverse"],
    philosophy: "flexbone",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "counter", carrier: "A2", aim: "backside-D" },
    primary: "A2",
    assignments: {
      QB: pass("1step", "A1"),
      A1: route("arrow", { toSide: "R" }),
      A2: carry("backside-D", "stretch"),
      FB: carry("playside-B", "dive"),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["trick", "reverse", "misdirection", "series"],
    situations: ["1st-down", "plus-territory", "opening-script"],
    coaching: { commentary: "Three fakes before the ball ever goes anywhere. It works because the first two are real plays." },
  }),
];

export const WING_T: PlaySpec[] = [
  play({
    id: "wt-buck-sweep",
    name: "Buck Sweep",
    aliases: ["Sweep", "Buck Sweep", "Buck"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "A1", aim: "playside-C" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "A1"),
      A1: carry("playside-C", "stretch"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["buck-series", "sweep", "both-guards-pull", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory", "opening-script"],
    coaching: {
      install: "Both guards pull. The wingback takes it wide behind them and the fullback fakes the trap.",
      commentary: "Everything else in the Buck series is a lie told about this play.",
    },
  }),

  play({
    id: "wt-fb-trap",
    name: "Buck Trap",
    aliases: ["FB Trap", "Buck Trap", "Trap"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "trap", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "dive"),
      A1: route("arrow", { toSide: "R" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["buck-series", "trap", "quick-hitting", "series"],
    situations: ["short-yardage", "1st-down", "3rd-short"],
    coaching: { install: "Identical backfield action to the sweep. The fullback keeps it and runs through the trap." },
  }),

  play({
    id: "wt-waggle",
    name: "Waggle",
    aliases: ["Buck Waggle", "Boot", "Waggle"],
    philosophy: "wing-t",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "half-slide",
    concept: "boot-flood",
    primary: "A1",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "backside", progression: ["A1", "Y", "X"] }],
    assignments: {
      QB: pass("boot", "FB"),
      A1: route("flat", { toSide: "L" }, { priorityOrder: 1 }),
      Y: route("drag", { toSide: "L", depthAdj: 6 }, { priorityOrder: 2 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      RB: block({ block: "hinge" }),
    },
    tags: ["buck-series", "waggle", "boot", "flood", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-cover-3"],
    coaching: {
      keys: "Three levels away from the sweep flow. The linebackers have already left.",
      commentary: "The third play of the series, and the one that scores.",
    },
  }),

  play({
    id: "wt-down",
    name: "Down",
    aliases: ["Off Tackle", "Down", "Belly"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "downhill"),
      FB: block({ block: "climb", target: "PSLB" }),
      A1: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["down-series", "off-tackle", "series"],
    situations: ["1st-down", "short-yardage", "red-zone"],
    coaching: { install: "Down blocks inside with the wing sealing the edge." },
  }),

  play({
    id: "wt-belly",
    name: "Belly",
    aliases: ["Belly", "Belly Option"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-B", "downhill"),
      A1: block({ block: "arc" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "base" }),
      X: route("stalk"),
    },
    tags: ["down-series", "belly", "fullback", "series"],
    situations: ["short-yardage", "1st-down", "four-minute"],
    coaching: { install: "Fullback downhill off the belly fake. The complement to Down." },
  }),

  play({
    id: "wt-belly-pass",
    name: "Belly Pass",
    aliases: ["Belly Pass", "Down Pass"],
    philosophy: "wing-t",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "big-on-big",
    concept: "pa-post",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Y", "A1"] }],
    assignments: {
      QB: pass("5step", "FB"),
      X: route("post", { depth: 12 }, { priorityOrder: 1 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 2 }),
      A1: route("flat", { toSide: "R" }, { startDelayMs: 260, priorityOrder: 3 }),
      RB: block({ block: "hinge" }),
    },
    tags: ["down-series", "play-action", "post-corner", "series"],
    situations: ["1st-down", "plus-territory", "vs-cover-1"],
    coaching: { keys: "Belly fake, then a post-corner combination on a safety who is already downhill." },
  }),

  play({
    id: "wt-jet-sweep",
    name: "Jet Sweep",
    aliases: ["Jet", "Fly", "Jet Sweep"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "outside-zone", carrier: "A1", aim: "playside-D" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "A1"),
      A1: motion("jet", carry("playside-D", "stretch"), 1200, "L"),
      FB: block({ block: "arc" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "reach" }),
      X: route("crack"),
    },
    tags: ["jet-series", "jet", "motion", "perimeter", "series"],
    situations: ["1st-down", "opening-script", "plus-territory"],
    coaching: { keys: "Full speed at the snap. The motion is the play." },
  }),

  play({
    id: "wt-jet-trap",
    name: "Jet Trap",
    aliases: ["Jet Counter", "Jet Trap"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "trap", carrier: "FB", aim: "backside-B" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      A1: motion("jet", route("arrow", { toSide: "L" }), 1200, "L"),
      FB: carry("backside-B", "dive"),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["jet-series", "trap", "misdirection", "series"],
    situations: ["1st-down", "short-yardage", "3rd-short"],
    coaching: { install: "Jet motion pulls the front sideways, the fullback traps back against it." },
  }),

  play({
    id: "wt-counter-criss-cross",
    name: "Counter Criss-Cross",
    aliases: ["Criss Cross", "Double Reverse"],
    philosophy: "wing-t",
    family: "trick",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "counter", carrier: "A1", aim: "backside-D" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "stretch"),
      A1: motion("across", carry("backside-D", "stretch"), 900, "L"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      X: route("crack"),
    },
    tags: ["trick", "criss-cross", "reverse", "misdirection"],
    situations: ["1st-down", "plus-territory", "opening-script"],
    coaching: { commentary: "Only works after Buck Sweep has gained ground twice." },
  }),

  play({
    id: "wt-tackle-trap",
    name: "Tackle Trap",
    aliases: ["Tackle Trap", "T Trap"],
    philosophy: "wing-t",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "counter", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "counter-step"),
      FB: block({ block: "climb", target: "PSLB" }),
      A1: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["trap", "tackle-pull", "counter"],
    situations: ["1st-down", "short-yardage"],
    coaching: { install: "The tackle pulls and traps, which nobody scouts for." },
  }),

  play({
    id: "wt-rollout",
    name: "Rollout Pass",
    aliases: ["Roll", "Sprint Out", "Rollout"],
    philosophy: "wing-t",
    family: "pass",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    protection: "half-slide",
    concept: "sprint-flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["A1", "Y", "X"] }],
    assignments: {
      QB: pass("sprint"),
      A1: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("sail", undefined, { priorityOrder: 2 }),
      X: route("post", { depth: 14 }, { priorityOrder: 3 }),
      FB: block({ block: "arc" }),
      RB: block({ block: "hinge" }),
    },
    tags: ["sprint-out", "flood", "three-level", "run-pass"],
    situations: ["3rd-medium", "sideline", "red-zone", "vs-cover-3"],
    coaching: { keys: "Half the field, three levels, and the quarterback can always run it." },
  }),
];
