/**
 * Power and gap scheme.
 *
 * The defining trait is pulling linemen and down-and-kickout blocks creating
 * angles, rather than the covered/uncovered rules zone runs on. Every play here
 * names a scheme and a carrier; the entire line is derived from that, so not
 * one blocking arrow in this file is drawn by hand.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, carry, motion, pass, play, route } from "../kit.ts";

const TACKLE = ["11man"] as const;

export const POWER_GAP: PlaySpec[] = [
  play({
    id: "gap-power-right",
    name: "Power Right",
    aliases: ["Power O", "34 Power", "Power"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "i-pro-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "downhill", "playside-A"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
      Z: route("stalk"),
    },
    tags: ["gap", "downhill", "double-team", "backside-pull", "power"],
    situations: ["short-yardage", "goal-line", "1st-down", "4th-short", "red-zone"],
    coaching: {
      install: "Down, down, back. The fullback kicks the end, the backside guard wraps to the playside backer.",
      commentary: "If the end squeezes, the fullback logs him and the back bounces.",
    },
  }),

  play({
    id: "gap-counter-gt",
    name: "Counter GT",
    aliases: ["Counter", "Counter Trey", "GT Counter"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "counter", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "counter-step", "playside-B"),
      Y: block({ block: "down" }),
      H: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "counter", "two-pullers", "misdirection"],
    situations: ["1st-down", "2nd-short", "short-yardage", "plus-territory"],
    coaching: {
      install: "Guard kicks, tackle wraps. The back's first step goes away from the play and sells it.",
      commentary: "Counter punishes a defense that has learned to chase Power.",
    },
  }),

  play({
    id: "gap-counter-gh",
    name: "Counter GH",
    aliases: ["Y-Counter", "Counter GH", "Gun Counter"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "counter", carrier: "RB", aim: "backside-C" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("backside-C", "counter-step"),
      H: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "counter", "spread", "h-back", "misdirection"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-zone"],
    coaching: { install: "The modern spread version: guard and H-back pull instead of guard and tackle." },
  }),

  play({
    id: "gap-trap",
    name: "Trap",
    aliases: ["Fold Trap", "Influence Trap", "Guard Trap"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "i-pro-right",
    personnelId: "21",
    run: { scheme: "trap", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "dive"),
      FB: block({ block: "climb", target: "PSLB" }),
      Y: block({ block: "climb", target: "second-level" }),
      X: route("stalk"),
      Z: route("stalk"),
    },
    tags: ["gap", "trap", "influence", "quick-hitting"],
    situations: ["short-yardage", "1st-down", "3rd-short", "backed-up"],
    coaching: {
      install: "Let the three-technique come. The backside guard traps him and the back runs off his tail.",
      commentary: "A penetrating tackle is a gift to a trap team.",
    },
  }),

  play({
    id: "gap-iso",
    name: "Iso",
    aliases: ["Isolation", "Lead", "Dive Lead"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "i-pro-right",
    personnelId: "21",
    run: { scheme: "duo", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "downhill"),
      FB: block({ block: "climb", target: "PSLB" }),
      Y: block({ block: "base" }),
      X: route("stalk"),
      Z: route("stalk"),
    },
    tags: ["gap", "iso", "lead", "downhill", "simple"],
    situations: ["short-yardage", "goal-line", "1st-down", "4th-short", "four-minute"],
    coaching: { install: "The fullback isolates the linebacker in the hole. The back reads that one block and goes." },
  }),

  play({
    id: "gap-toss-right",
    name: "Toss Right",
    aliases: ["Quick Toss", "Pitch Sweep", "Toss"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "strong-i-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-D", "stretch"),
      FB: block({ block: "arc" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["gap", "toss", "perimeter", "edge", "speed"],
    situations: ["1st-down", "2nd-short", "plus-territory", "opening-script"],
    coaching: { keys: "Get the ball outside before the edge sets. If the corner squats, crack him and run past." },
  }),

  play({
    id: "gap-buck-sweep",
    name: "Buck Sweep",
    aliases: ["Sweep", "Buck", "Wing-T Sweep"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "A1", aim: "playside-C" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "A1"),
      A1: carry("playside-C", "stretch"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["gap", "sweep", "both-guards-pull", "wing-t", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: {
      install: "Both guards pull. The wingback takes it wide behind them.",
      commentary: "The play the rest of the Buck series exists to set up.",
    },
  }),

  play({
    id: "gap-duo",
    name: "Duo",
    aliases: ["Duo", "Power Without a Puller"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "duo", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "downhill", "playside-B"),
      Y: block({ block: "base" }),
      H: block({ block: "base" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "duo", "double-team", "vertical-displacement"],
    situations: ["short-yardage", "1st-down", "goal-line", "four-minute"],
    coaching: {
      install: "Two double teams, nobody pulls. The back reads the linebacker off the second level.",
      commentary: "Power's angles without Power's timing risk.",
    },
  }),

  play({
    id: "gap-wham",
    name: "Wham",
    aliases: ["Wham", "H-Wham", "Cross Block"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "trap", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "dive"),
      H: block({ block: "trap", target: "playside-A" }),
      Y: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "wham", "h-back", "trap", "quick-hitting"],
    situations: ["short-yardage", "1st-down", "3rd-short"],
    coaching: { install: "The H-back crosses the formation and whams the three-technique nobody blocked." },
  }),

  play({
    id: "gap-dart",
    name: "Dart",
    aliases: ["Dart", "Tackle Wrap"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "counter", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-B", "downhill"),
      Y: block({ block: "down" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "dart", "tackle-pull", "spread"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: { install: "The backside tackle pulls and leads through the hole. Cheaper than Power out of an empty backfield." },
  }),

  play({
    id: "gap-g-lead",
    name: "G Lead",
    aliases: ["Down", "Off Tackle", "G Down"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "strong-i-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "downhill"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "off-tackle", "down-block", "puller"],
    situations: ["1st-down", "short-yardage", "red-zone"],
    coaching: { install: "Down block everything inside, pull the playside guard around the kickout." },
  }),

  play({
    id: "gap-jet-sweep",
    name: "Jet Sweep",
    aliases: ["Jet", "Fly Sweep", "Speed Sweep"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "H", aim: "playside-D" },
    primary: "H",
    assignments: {
      QB: pass("gun-quick", "H"),
      H: motion("jet", carry("playside-D", "stretch"), 1200, "L"),
      RB: block({ block: "arc" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["gap", "jet", "motion", "perimeter", "tempo"],
    situations: ["1st-down", "opening-script", "plus-territory", "vs-zone"],
    coaching: {
      keys: "The motion has to be full speed at the snap or the timing is gone.",
      commentary: "Even when it gains three yards it moves the defense sideways, which is what the rest of the run game wants.",
    },
  }),

  play({
    id: "gap-power-read",
    name: "Power Read",
    aliases: ["Q Power", "Inverted Veer", "Power Read"],
    philosophy: "power-gap",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    reads: [
      {
        order: 1,
        type: "zone-read",
        key: "EMLOS",
        keySide: "playside",
        ifTake: { keep: "QB" },
        ifNot: { give: "RB" },
      },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      H: block({ block: "climb", target: "PSLB" }),
      Y: block({ block: "down" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "option", "read", "qb-run", "power"],
    situations: ["1st-down", "3rd-short", "red-zone", "short-yardage"],
    coaching: {
      keys: "Read the end man on the line. He chases the sweep, the quarterback keeps it inside behind the pull.",
      commentary: "The back and the quarterback swap the give and keep roles compared to a normal zone read.",
    },
  }),
];
