/**
 * Power and gap scheme.
 *
 * The defining trait is pulling linemen and down-and-kickout blocks creating
 * angles, rather than the covered/uncovered rules zone runs on. Every play here
 * names a scheme and a carrier; the entire line is derived from that, so not
 * one blocking arrow in this file is drawn by hand.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, carry, motion, pass, pitch, play, route } from "../kit.ts";

const TACKLE = ["11man"] as const;

export const POWER_GAP: PlaySpec[] = [
  play({
    id: "gap-power-right",
    name: "Power Right",
    aliases: ["Power O", "34 Power", "Power"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "i-pro-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "downhill", "playside-A"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
      Z: route("stalk"),
    },
    tags: ["gap", "downhill", "double-team", "backside-pull", "power"],
    situations: ["short-yardage", "goal-line", "1st-down", "4th-short", "red-zone"],
    coaching: {
      install: "Down, down, back. The fullback kicks the end, the backside guard wraps to the playside backer.",
      commentary: "If the end squeezes, the fullback logs him and the back bounces.",
    },
  }),

  play({
    id: "gap-counter-gt",
    name: "Counter GT",
    aliases: ["Counter", "Counter Trey", "GT Counter"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "counter", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "counter-step", "playside-B"),
      Y: block({ block: "down" }),
      H: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "counter", "two-pullers", "misdirection"],
    situations: ["1st-down", "2nd-short", "short-yardage", "plus-territory"],
    coaching: {
      install: "Guard kicks, tackle wraps. The back's first step goes away from the play and sells it.",
      commentary: "Counter punishes a defense that has learned to chase Power.",
    },
  }),

  play({
    id: "gap-counter-gh",
    name: "Counter GH",
    aliases: ["Y-Counter", "Counter GH", "Gun Counter"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "counter", carrier: "RB", aim: "backside-C" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("backside-C", "counter-step"),
      H: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "counter", "spread", "h-back", "misdirection"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-zone"],
    coaching: { install: "The modern spread version: guard and H-back pull instead of guard and tackle." },
  }),

  play({
    id: "gap-trap",
    name: "Trap",
    aliases: ["Fold Trap", "Influence Trap", "Guard Trap"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "i-pro-right",
    personnelId: "21",
    run: { scheme: "trap", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "dive"),
      FB: block({ block: "climb", target: "PSLB" }),
      Y: block({ block: "climb", target: "second-level" }),
      X: route("stalk"),
      Z: route("stalk"),
    },
    tags: ["gap", "trap", "influence", "quick-hitting"],
    situations: ["short-yardage", "1st-down", "3rd-short", "backed-up"],
    coaching: {
      install: "Let the three-technique come. The backside guard traps him and the back runs off his tail.",
      commentary: "A penetrating tackle is a gift to a trap team.",
    },
  }),

  play({
    id: "gap-iso",
    name: "Iso",
    aliases: ["Isolation", "Lead", "Dive Lead"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "i-pro-right",
    personnelId: "21",
    run: { scheme: "duo", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "downhill"),
      FB: block({ block: "climb", target: "PSLB" }),
      Y: block({ block: "base" }),
      X: route("stalk"),
      Z: route("stalk"),
    },
    tags: ["gap", "iso", "lead", "downhill", "simple"],
    situations: ["short-yardage", "goal-line", "1st-down", "4th-short", "four-minute"],
    coaching: { install: "The fullback isolates the linebacker in the hole. The back reads that one block and goes." },
  }),

  play({
    id: "gap-toss-right",
    name: "Toss Right",
    aliases: ["Quick Toss", "Pitch Sweep", "Toss"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "strong-i-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-D", "stretch"),
      FB: block({ block: "arc" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["gap", "toss", "perimeter", "edge", "speed"],
    situations: ["1st-down", "2nd-short", "plus-territory", "opening-script"],
    coaching: { keys: "Get the ball outside before the edge sets. If the corner squats, crack him and run past." },
  }),

  play({
    id: "gap-buck-sweep",
    name: "Buck Sweep",
    aliases: ["Sweep", "Buck", "Wing-T Sweep"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "wing-t-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "A1", aim: "playside-C" },
    primary: "A1",
    assignments: {
      QB: pass("1step", "A1"),
      A1: carry("playside-C", "stretch"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      RB: block({ block: "seal" }),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["gap", "sweep", "both-guards-pull", "wing-t", "series"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: {
      install: "Both guards pull. The wingback takes it wide behind them.",
      commentary: "The play the rest of the Buck series exists to set up.",
    },
  }),

  play({
    id: "gap-duo",
    name: "Duo",
    aliases: ["Duo", "Power Without a Puller"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "duo", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "downhill", "playside-B"),
      Y: block({ block: "base" }),
      H: block({ block: "base" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "duo", "double-team", "vertical-displacement"],
    situations: ["short-yardage", "1st-down", "goal-line", "four-minute"],
    coaching: {
      install: "Two double teams, nobody pulls. The back reads the linebacker off the second level.",
      commentary: "Power's angles without Power's timing risk.",
    },
  }),

  play({
    id: "gap-wham",
    name: "Wham",
    aliases: ["Wham", "H-Wham", "Cross Block"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "trap", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "dive"),
      H: block({ block: "trap", target: "playside-A" }),
      Y: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "wham", "h-back", "trap", "quick-hitting"],
    situations: ["short-yardage", "1st-down", "3rd-short"],
    coaching: { install: "The H-back crosses the formation and whams the three-technique nobody blocked." },
  }),

  play({
    id: "gap-dart",
    name: "Dart",
    aliases: ["Dart", "Tackle Wrap"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "counter", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-B", "downhill"),
      Y: block({ block: "down" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "dart", "tackle-pull", "spread"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: { install: "The backside tackle pulls and leads through the hole. Cheaper than Power out of an empty backfield." },
  }),

  play({
    id: "gap-g-lead",
    name: "G Lead",
    aliases: ["Down", "Off Tackle", "G Down"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "strong-i-right",
    personnelId: "21",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "downhill"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "off-tackle", "down-block", "puller"],
    situations: ["1st-down", "short-yardage", "red-zone"],
    coaching: { install: "Down block everything inside, pull the playside guard around the kickout." },
  }),

  play({
    id: "gap-jet-sweep",
    name: "Jet Sweep",
    aliases: ["Jet", "Fly Sweep", "Speed Sweep"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "H", aim: "playside-D" },
    primary: "H",
    assignments: {
      QB: pass("gun-quick", "H"),
      H: motion("jet", carry("playside-D", "stretch"), 1200, "L"),
      RB: block({ block: "arc" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["gap", "jet", "motion", "perimeter", "tempo"],
    situations: ["1st-down", "opening-script", "plus-territory", "vs-zone"],
    coaching: {
      keys: "The motion has to be full speed at the snap or the timing is gone.",
      commentary: "Even when it gains three yards it moves the defense sideways, which is what the rest of the run game wants.",
    },
  }),

  play({
    id: "gap-power-read",
    name: "Power Read",
    aliases: ["Q Power", "Inverted Veer", "Power Read"],
    philosophy: "power-gap",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    reads: [
      {
        order: 1,
        type: "zone-read",
        key: "EMLOS",
        keySide: "playside",
        ifTake: { keep: "QB" },
        ifNot: { give: "RB" },
      },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      H: block({ block: "climb", target: "PSLB" }),
      Y: block({ block: "down" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "option", "read", "qb-run", "power"],
    situations: ["1st-down", "3rd-short", "red-zone", "short-yardage"],
    coaching: {
      keys: "Read the end man on the line. He chases the sweep, the quarterback keeps it inside behind the pull.",
      commentary: "The back and the quarterback swap the give and keep roles compared to a normal zone read.",
    },
  }),
  play({
    id: "gap-counter-bash",
    name: "Counter Bash",
    aliases: ["Bash", "Counter Bash", "Back Away"],
    philosophy: "power-gap",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "counter", carrier: "QB", aim: "playside-B" },
    primary: "QB",
    reads: [
      { order: 1, type: "zone-read", key: "EMLOS", keySide: "backside", ifTake: { give: "RB" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-B", "downhill"),
      RB: carry("backside-D", "stretch"),
      H: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "counter", "bash", "qb-run", "read"],
    situations: ["short-yardage", "3rd-short", "red-zone", "goal-line"],
    coaching: {
      install: "Back away, quarterback downhill behind the counter blocks.",
      keys: "Read the backside end. If he chases the sweep the quarterback has a gap with two pullers in it.",
    },
  }),

  play({
    id: "gap-pin-pull-sweep",
    name: "Pin & Pull Sweep",
    aliases: ["Pin Pull", "Perimeter Sweep"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-tight-doubles",
    personnelId: "11",
    run: { scheme: "pin-pull", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Y: block({ block: "down" }),
      H: block({ block: "crack" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "pin-pull", "perimeter", "condensed", "edge"],
    situations: ["1st-down", "plus-territory", "vs-zone"],
    coaching: {
      install: "Covered linemen pin down, uncovered linemen pull around. Nasty splits shorten the run to the edge.",
    },
  }),

  play({
    id: "gap-fold-iso",
    name: "Fold Iso",
    aliases: ["Fold", "Guard Fold"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "weak-i-right",
    personnelId: "21",
    run: { scheme: "fold", carrier: "RB", aim: "backside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("backside-A", "downhill"),
      FB: block({ block: "climb", target: "BSLB" }),
      Y: block({ block: "base" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "fold", "weak", "downhill"],
    situations: ["short-yardage", "1st-down", "four-minute"],
    coaching: { install: "The guard folds around the centre's down block. A different angle on the same gap." },
  }),

  play({
    id: "gap-power-boot",
    name: "Power Boot",
    aliases: ["Power Pass", "Keeper"],
    philosophy: "power-gap",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "pistol-strong-right",
    personnelId: "21",
    protection: "sprint-right",
    concept: "boot-flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "backside", progression: ["FB", "Y", "X"] }],
    assignments: {
      QB: pass("boot", "RB"),
      FB: route("flat", { toSide: "L" }, { priorityOrder: 1 }),
      Y: route("over", { toSide: "L" }, { priorityOrder: 2 }),
      X: route("post", { depth: 14 }, { priorityOrder: 3 }),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 4 }),
    },
    tags: ["play-action", "boot", "power-action", "flood"],
    situations: ["1st-down", "plus-territory", "vs-cover-3", "red-zone"],
    coaching: { keys: "Power action pulls the linebackers, and the quarterback comes out the back door." },
  }),

  play({
    id: "gap-crack-toss",
    name: "Crack Toss",
    aliases: ["Crack Sweep", "Toss Crack"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trey-right",
    personnelId: "11",
    run: { scheme: "power", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pitch("RB"),
      RB: carry("playside-D", "stretch"),
      Z: route("crack"),
      H: route("crack"),
      Y: block({ block: "arc" }),
      X: route("stalk"),
    },
    tags: ["gap", "toss", "crack", "perimeter", "trey"],
    situations: ["1st-down", "opening-script", "plus-territory"],
    coaching: {
      keys: "The receivers crack inside and the pullers take the corner. Numbers on the edge decide it.",
    },
  }),

  play({
    id: "gap-lead-draw",
    name: "Lead Draw",
    aliases: ["Draw", "Iso Draw"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "big-on-big",
    run: { scheme: "duo", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Z: route("go"),
      X: route("go"),
      Y: route("seam"),
      H: route("seam"),
    },
    tags: ["draw", "gap", "pass-look", "vs-zone"],
    situations: ["2nd-long", "3rd-long", "backed-up"],
    coaching: {
      keys: "Show them a drop, then run at the rush lanes they just vacated.",
      commentary: "Best called on a down where the defence has already decided you are throwing.",
    },
  }),

  play({
    id: "gap-qb-power",
    name: "QB Power",
    aliases: ["Q Power", "Quarterback Power"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "power", carrier: "QB", aim: "playside-B" },
    primary: "QB",
    assignments: {
      QB: carry("playside-B", "downhill"),
      RB: block({ block: "arc" }),
      H: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "down" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "qb-run", "power", "short-yardage", "extra-hat"],
    situations: ["short-yardage", "goal-line", "4th-short", "3rd-short"],
    coaching: {
      keys: "Running the quarterback puts an extra blocker on the play. On the two-yard line that is the whole argument.",
    },
  }),

  play({
    id: "gap-counter-jet",
    name: "Counter Jet",
    aliases: ["Jet Counter", "Fake Jet Counter"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "counter", carrier: "RB", aim: "backside-C" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      H: motion("jet", route("arrow", { toSide: "L" }), 1200, "L"),
      RB: carry("backside-C", "counter-step"),
      Y: block({ block: "kickout", target: "EMLOS" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["gap", "counter", "jet", "motion", "misdirection"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: {
      keys: "Full-speed jet motion one way, counter the other. The front cannot honour both.",
    },
  }),

  play({
    id: "gap-heavy-wham",
    name: "Jumbo Wham",
    aliases: ["Heavy Wham", "Jumbo Iso"],
    philosophy: "power-gap",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "ace-jumbo",
    personnelId: "13",
    run: { scheme: "trap", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "dive"),
      V: block({ block: "trap", target: "playside-A" }),
      Y: block({ block: "down" }),
      H: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["gap", "wham", "heavy", "jumbo", "short-yardage"],
    situations: ["goal-line", "short-yardage", "4th-short", "four-minute"],
    coaching: { install: "Three tight ends, one wham block, one gap. Nothing clever about it." },
  }),
];
