/**
 * Spread and RPO.
 *
 * An RPO carries a run scheme AND a route concept simultaneously, plus a named
 * read key with two outcomes. That is the shape most playbook tools cannot
 * represent — they force you to draw two plays and remember they are one — and
 * it is the reason `PlaySpec` holds `run` and `assignments` and `reads` side by
 * side rather than making them alternatives.
 *
 * Pre-snap RPOs read a count or a leverage before the ball moves; post-snap
 * RPOs read a second-level defender after the mesh. The distinction is stored
 * on the read, not implied by the tags.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, carry, motion, pass, play, route } from "../kit.ts";

const SPREAD = ["11man"] as const;

export const SPREAD_RPO: PlaySpec[] = [
  play({
    id: "rpo-iz-bubble",
    name: "Inside Zone / Bubble",
    aliases: ["IZ Bubble", "Zone Bubble", "Bubble RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-pre", key: "apex", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "stretch"),
      H: route("bubble", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("stalk"),
      Z: route("stalk"),
      X: route("slant"),
    },
    tags: ["rpo", "bubble", "pre-snap", "numbers", "conflict"],
    situations: ["1st-down", "2nd-short", "vs-zone", "opening-script"],
    coaching: {
      keys: "Count the box before the snap. Six defenders on six blockers means hand it off; seven means throw it.",
      commentary: "The entry-level RPO, and still the one that gets the most yards for the least risk.",
    },
  }),

  play({
    id: "rpo-iz-glance",
    name: "Inside Zone / Glance",
    aliases: ["IZ Glance", "Glance RPO", "Skinny Post RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-doubles-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "SS", keySide: "backside", ifTake: { give: "RB" }, ifNot: { throw: "X" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      X: route("glance", undefined, { priorityOrder: 1 }),
      Z: route("stalk"),
      Y: route("stalk"),
      H: route("stalk"),
    },
    tags: ["rpo", "glance", "post-snap", "backside", "safety-read"],
    situations: ["1st-down", "2nd-short", "vs-cover-3", "vs-cover-1", "plus-territory"],
    coaching: {
      keys: "Read the overhang or the down safety. If he fills, the glance is behind him over the linebacker's head.",
    },
  }),

  play({
    id: "rpo-iz-slant",
    name: "Inside Zone / Slant",
    aliases: ["IZ Slant", "Slant RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-twins-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "OLB", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: route("slant", undefined, { priorityOrder: 1 }),
      Z: route("stalk"),
      X: route("stalk"),
      Y: route("stalk"),
    },
    tags: ["rpo", "slant", "post-snap", "linebacker-conflict"],
    situations: ["1st-down", "2nd-short", "3rd-short", "vs-man"],
    coaching: { keys: "Punishes a linebacker who triggers downhill on run action. The window is exactly where he left." },
  }),

  play({
    id: "rpo-oz-stick",
    name: "Outside Zone / Stick",
    aliases: ["OZ Stick", "Stick RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "flat-defender", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "Y" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-C", "stretch"),
      Y: route("stick", { depth: 6 }, { priorityOrder: 1 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["rpo", "stick", "post-snap", "perimeter"],
    situations: ["1st-down", "3rd-short", "vs-zone"],
    coaching: { keys: "Stretch action holds the edge. If the flat defender chases the run, the stick is uncovered." },
  }),

  play({
    id: "rpo-power-pop",
    name: "Power / Pop Pass",
    aliases: ["Power Pop", "Pop RPO", "Y-Pop"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-doubles-right",
    personnelId: "11",
    run: { scheme: "power", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "MIKE", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "Y" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-B", "downhill"),
      Y: route("seam", { depth: 10 }, { priorityOrder: 1 }),
      H: route("stalk"),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["rpo", "pop", "power", "seam", "vacated-window"],
    situations: ["1st-down", "3rd-short", "red-zone", "goal-line"],
    coaching: { keys: "Gap-scheme action pulls the linebackers hard. The tight end pops into the space they left." },
  }),

  play({
    id: "rpo-counter-bubble",
    name: "Counter / Bubble",
    aliases: ["Counter Bubble", "GH Bubble"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "counter", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-pre", key: "apex", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-C", "counter-step"),
      H: route("bubble", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("stalk"),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["rpo", "counter", "bubble", "misdirection"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: { keys: "Gap scheme with a perimeter answer. Same pre-snap count, harder run behind it." },
  }),

  play({
    id: "rpo-zone-read-now",
    name: "Zone Read / Now",
    aliases: ["Read Now", "Triple Option Spread"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "zone-read", key: "DE", keySide: "backside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
      { order: 2, type: "rpo-pre", key: "CB", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "Z" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Z: route("hitch", { depth: 5 }, { priorityOrder: 1 }),
      X: route("hitch", { depth: 5 }, { priorityOrder: 2 }),
      Y: route("stalk"),
      H: route("stalk"),
    },
    tags: ["rpo", "zone-read", "now-screen", "triple", "two-reads"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: {
      keys: "Two reads on one snap: the corner's cushion before the ball moves, the end after it.",
      commentary: "A genuine three-way option out of the gun, and the whole point of storing two reads on one play.",
    },
  }),

  play({
    id: "rpo-stick-draw",
    name: "Stick Draw",
    aliases: ["Stick Draw", "Draw RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "screen-release",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "Y",
    reads: [
      { order: 1, type: "rpo-post", key: "MIKE", ifTake: { give: "RB" }, ifNot: { throw: "Y" } },
    ],
    assignments: {
      QB: pass("gun-quick"),
      RB: carry("playside-A", "dive"),
      Y: route("stick", { depth: 6 }, { priorityOrder: 1 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("go"),
      X: route("slant"),
    },
    tags: ["rpo", "draw", "stick", "inverted", "pass-first"],
    situations: ["3rd-medium", "2nd-long", "vs-zone"],
    coaching: { keys: "The read is inverted: it looks like a pass first and the run is the alternative." },
  }),

  play({
    id: "rpo-jet-sweep",
    name: "Jet Sweep RPO",
    aliases: ["Jet RPO", "Fly RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-doubles-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "H", aim: "playside-D" },
    primary: "H",
    reads: [
      { order: 1, type: "rpo-pre", key: "OLB", keySide: "playside", ifTake: { throw: "Z" }, ifNot: { give: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "H"),
      H: route("bubble", { toSide: "R" }, { priorityOrder: 1 }),
      RB: block({ block: "arc" }),
      Z: route("slant", undefined, { priorityOrder: 2 }),
      X: route("go"),
      Y: route("stalk"),
    },
    tags: ["rpo", "jet", "motion", "perimeter", "tempo"],
    situations: ["1st-down", "opening-script", "vs-zone"],
    coaching: { keys: "Horizontal stress before the snap and vertical stress after it." },
  }),

  play({
    id: "spread-qb-draw",
    name: "QB Draw",
    aliases: ["Draw", "QB Draw", "Q Draw"],
    philosophy: "spread-rpo",
    family: "run",
    variantScope: [...SPREAD],
    formationId: "gun-empty",
    personnelId: "10",
    protection: "big-on-big",
    run: { scheme: "inside-zone", carrier: "QB", aim: "playside-A" },
    primary: "QB",
    assignments: {
      QB: carry("playside-A", "downhill"),
      X: route("go"),
      Z: route("go"),
      Y: route("seam"),
      H: route("seam"),
      F: route("go"),
    },
    tags: ["draw", "qb-run", "empty", "spread-them-out"],
    situations: ["3rd-medium", "3rd-long", "2nd-long", "vs-zone"],
    coaching: { keys: "Five verticals clear the box out. Everything after that is one man to beat." },
  }),

  play({
    id: "spread-hitch-rpo",
    name: "Hitch RPO",
    aliases: ["Now Hitch", "Hitch RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-twins-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-pre", key: "CB", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "Z" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Z: route("hitch", { depth: 5 }, { priorityOrder: 1 }),
      H: route("stalk"),
      X: route("hitch", { depth: 5 }, { priorityOrder: 2 }),
      Y: route("stalk"),
    },
    tags: ["rpo", "hitch", "pre-snap", "cushion"],
    situations: ["1st-down", "2nd-short", "backed-up", "vs-zone"],
    coaching: { keys: "If the corner is more than seven yards off, take the free five." },
  }),

  play({
    id: "spread-y-cross-peek",
    name: "Y-Cross Peek",
    aliases: ["Peek", "Cross Peek"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-C" },
    primary: "Y",
    reads: [
      { order: 1, type: "rpo-post", key: "FS", ifTake: { give: "RB" }, ifNot: { throw: "Y" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-C", "stretch"),
      Y: route("drag", { toSide: "L", depthAdj: 8 }, { priorityOrder: 1 }),
      Z: route("go"),
      H: route("stalk"),
      X: route("post", { depth: 12 }, { priorityOrder: 2 }),
    },
    tags: ["rpo", "peek", "cross", "shot", "run-first"],
    situations: ["1st-down", "plus-territory", "vs-cover-3"],
    coaching: { keys: "Run call with a downfield peek. If the middle of the field opens, take it; otherwise hand it off." },
  }),
  play({
    id: "rpo-iz-pop",
    name: "Inside Zone / Pop",
    aliases: ["Pop RPO", "IZ Pop", "Seam Pop"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "MIKE", ifTake: { give: "RB" }, ifNot: { throw: "Y" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Y: route("pop", undefined, { priorityOrder: 1 }),
      H: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["rpo", "pop", "seam", "post-snap", "vacated-window"],
    situations: ["1st-down", "3rd-short", "red-zone", "goal-line"],
    coaching: { keys: "The tight end pops into the window the linebacker leaves when he fills the A gap." },
  }),

  play({
    id: "rpo-quads-now",
    name: "Quads / Now",
    aliases: ["Quads Now", "Numbers RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-quads-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "QB", aim: "backside-A" },
    primary: "QB",
    reads: [
      { order: 1, type: "rpo-pre", key: "apex", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { throw: "F" } },
    ],
    assignments: {
      QB: carry("backside-A", "downhill"),
      Z: route("stalk"),
      H: route("stalk"),
      Y: route("stalk"),
      F: route("bubble", { toSide: "R" }, { priorityOrder: 1 }),
      X: route("slant", undefined, { priorityOrder: 2 }),
    },
    tags: ["rpo", "quads", "numbers", "pre-snap", "leverage"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: {
      keys: "Four to one side. Count them; if they do not match it you never have to hand it off.",
    },
  }),

  play({
    id: "rpo-split-glance",
    name: "Split Zone / Glance",
    aliases: ["Slice Glance", "Split Glance"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "SS", keySide: "backside", ifTake: { give: "RB" }, ifNot: { throw: "X" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: block({ block: "kickout", target: "EMLOS" }),
      X: route("glance", undefined, { priorityOrder: 1 }),
      Z: route("stalk"),
      Y: route("stalk"),
    },
    tags: ["rpo", "glance", "split-zone", "post-snap", "backside"],
    situations: ["1st-down", "2nd-short", "vs-cover-3", "vs-cover-1"],
    coaching: { keys: "Split-zone action holds the backside. The glance runs behind the safety who filled." },
  }),

  play({
    id: "rpo-pin-pull-bubble",
    name: "Pin & Pull / Bubble",
    aliases: ["Perimeter RPO", "Pin Pull Bubble"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trey-right",
    personnelId: "11",
    run: { scheme: "pin-pull", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-pre", key: "apex", keySide: "backside", ifTake: { give: "RB" }, ifNot: { throw: "X" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Z: route("stalk"),
      H: route("stalk"),
      Y: block({ block: "down" }),
      X: route("hitch", { depth: 5 }, { priorityOrder: 1 }),
    },
    tags: ["rpo", "pin-pull", "perimeter", "backside-throw"],
    situations: ["1st-down", "plus-territory", "vs-zone"],
    coaching: { keys: "The run goes one way; if the backside overhang chases it, throw behind him." },
  }),

  play({
    id: "rpo-counter-glance",
    name: "Counter / Glance",
    aliases: ["Counter RPO", "GH Glance"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "pistol-trips-right",
    personnelId: "11",
    run: { scheme: "counter", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "SS", keySide: "backside", ifTake: { give: "RB" }, ifNot: { throw: "X" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-C", "counter-step"),
      X: route("glance", undefined, { priorityOrder: 1 }),
      Z: route("stalk"),
      H: route("stalk"),
      Y: route("stalk"),
    },
    tags: ["rpo", "counter", "glance", "misdirection", "pistol"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: { keys: "Gap-scheme run action moves the second level further than zone does, so the window is bigger." },
  }),

  play({
    id: "rpo-snag-peek",
    name: "Zone / Snag Peek",
    aliases: ["Snag RPO", "Triangle Peek"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "flat-defender", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "Y" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Y: route("spot", { depth: 6 }, { priorityOrder: 1 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["rpo", "snag", "spot", "triangle", "post-snap"],
    situations: ["3rd-short", "1st-down", "vs-zone"],
    coaching: { keys: "A two-man triangle on the flat defender, attached to a run. He is wrong three ways." },
  }),

  play({
    id: "spread-qb-counter",
    name: "QB Counter",
    aliases: ["Q Counter", "GT Q"],
    philosophy: "spread-rpo",
    family: "run",
    variantScope: [...SPREAD],
    formationId: "gun-empty-trey",
    personnelId: "11",
    run: { scheme: "counter", carrier: "QB", aim: "playside-C" },
    primary: "QB",
    assignments: {
      QB: carry("playside-C", "counter-step"),
      Z: route("stalk"),
      X: route("stalk"),
      Y: route("stalk"),
      H: route("stalk"),
      F: route("stalk"),
    },
    tags: ["qb-run", "counter", "empty", "surprise"],
    situations: ["3rd-short", "4th-short", "goal-line", "short-yardage"],
    coaching: {
      keys: "Empty says pass. Two pullers say otherwise.",
      commentary: "Nobody has a spy on the quarterback out of an empty set on third and two.",
    },
  }),

  play({
    id: "spread-jet-rpo-glance",
    name: "Jet / Glance",
    aliases: ["Jet Glance", "Fly RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-stack-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "H", aim: "playside-D" },
    primary: "H",
    reads: [
      { order: 1, type: "rpo-post", key: "SS", keySide: "backside", ifTake: { give: "H" }, ifNot: { throw: "X" } },
    ],
    assignments: {
      QB: pass("gun-quick", "H"),
      H: motion("jet", carry("playside-D", "stretch"), 1200, "R"),
      RB: block({ block: "arc" }),
      X: route("glance", undefined, { priorityOrder: 1 }),
      Z: route("stalk"),
      Y: route("stalk"),
    },
    tags: ["rpo", "jet", "glance", "motion", "tempo"],
    situations: ["1st-down", "opening-script", "plus-territory"],
    coaching: { keys: "Jet motion moves the whole second level sideways. The glance runs into what they left." },
  }),

  play({
    id: "rpo-nub-glance",
    name: "Nub Zone / Glance",
    aliases: ["Nub Glance", "Boundary Glance"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-nub-trips",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "SS", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: route("glance", undefined, { priorityOrder: 1 }),
      Z: route("stalk"),
      X: route("stalk"),
      Y: block({ block: "down" }),
    },
    tags: ["rpo", "glance", "nub", "post-snap"],
    situations: ["1st-down", "2nd-short", "vs-cover-3", "vs-cover-1"],
    coaching: { keys: "Run to the tight end, throw to the trips. The safety cannot be in both places." },
  }),

  play({
    id: "rpo-quads-bubble",
    name: "Quads / Bubble",
    aliases: ["Quads Bubble", "Four Strong Now"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-empty-quads",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "QB", aim: "backside-A" },
    primary: "QB",
    reads: [
      { order: 1, type: "rpo-pre", key: "apex", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { throw: "F" } },
    ],
    assignments: {
      QB: carry("backside-A", "downhill"),
      F: route("bubble", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("stalk"),
      H: route("stalk"),
      Z: route("stalk"),
      X: route("slant", { depth: 6 }, { priorityOrder: 2 }),
    },
    tags: ["rpo", "quads", "bubble", "count", "pre-snap"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: { keys: "Count the defenders over the four receivers. Three means throw it." },
  }),

  play({
    id: "rpo-power-glance",
    name: "Power / Glance",
    aliases: ["Power RPO", "Gap Glance"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trey-right",
    personnelId: "11",
    run: { scheme: "power", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "SS", keySide: "backside", ifTake: { give: "RB" }, ifNot: { throw: "X" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-C", "downhill"),
      X: route("glance", undefined, { priorityOrder: 1 }),
      Y: block({ block: "down" }),
      Z: route("stalk"),
      H: route("stalk"),
    },
    tags: ["rpo", "power", "glance", "gap-scheme"],
    situations: ["1st-down", "2nd-short", "red-zone"],
    coaching: { keys: "A pulling guard moves the second level further than any zone step does." },
  }),

  play({
    id: "rpo-oz-bubble",
    name: "Outside Zone / Bubble",
    aliases: ["Stretch Bubble", "OZ Now"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-twins-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-pre", key: "apex", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      H: route("bubble", { toSide: "R" }, { priorityOrder: 1 }),
      Z: route("stalk"),
      Y: block({ block: "reach" }),
      X: route("stalk"),
    },
    tags: ["rpo", "outside-zone", "bubble", "perimeter"],
    situations: ["1st-down", "plus-territory", "vs-zone"],
    coaching: { keys: "Both answers attack the edge, so the defense has to defend the same grass twice." },
  }),

  play({
    id: "rpo-draw-slant",
    name: "Draw / Slant",
    aliases: ["Draw RPO", "Delay Slant"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "M", ifTake: { give: "RB" }, ifNot: { throw: "H" } },
    ],
    assignments: {
      QB: pass("gun-3", "RB"),
      RB: carry("playside-B", "downhill"),
      H: route("slant", { depth: 6 }, { priorityOrder: 1 }),
      Z: route("go", { depth: 14 }, { priorityOrder: 2 }),
      X: route("hitch", { depth: 6 }, { priorityOrder: 3 }),
      Y: route("stalk"),
    },
    tags: ["rpo", "draw", "slant", "second-level-read"],
    situations: ["2nd-long", "3rd-medium", "vs-zone", "blitz-beater"],
    coaching: { keys: "Read the middle linebacker's depth. If he drops, hand it off." },
  }),

  play({
    id: "rpo-y-off-arrow",
    name: "Zone / Arrow",
    aliases: ["Arrow RPO", "Flare RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-pre", key: "apex", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "Y" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Y: route("arrow", { toSide: "R" }, { priorityOrder: 1 }),
      H: route("stalk"),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["rpo", "arrow", "flare", "perimeter", "quick"],
    situations: ["1st-down", "2nd-short", "vs-zone", "goal-line"],
    coaching: { keys: "The arrow puts a body in the flat immediately, so the overhang has to choose before the mesh finishes." },
  }),

  play({
    id: "rpo-stacked-slant",
    name: "Zone / Stack Slant",
    aliases: ["Stack Slant RPO", "Free Release"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-stack-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "flat-defender", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: route("slant", { depth: 6 }, { priorityOrder: 1 }),
      Z: route("stalk"),
      Y: route("stalk"),
      X: route("stalk"),
    },
    tags: ["rpo", "slant", "stack", "free-release"],
    situations: ["1st-down", "3rd-short", "vs-man", "red-zone"],
    coaching: { keys: "A stacked receiver cannot be pressed, so the slant is on time every snap." },
  }),

  play({
    id: "rpo-shovel-peek",
    name: "Shovel Peek",
    aliases: ["Shovel RPO", "Peek Shovel"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "power", carrier: "H", aim: "playside-B" },
    primary: "H",
    reads: [
      { order: 1, type: "rpo-post", key: "DE", keySide: "playside", ifTake: { throw: "Z" }, ifNot: { give: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "H"),
      H: route("shovel", { toSide: "L" }, { priorityOrder: 1 }),
      Z: route("fade", { depth: 10 }, { priorityOrder: 2 }),
      Y: block({ block: "down" }),
      RB: block({ block: "arc" }),
      X: route("stalk"),
    },
    tags: ["rpo", "shovel", "peek", "red-zone"],
    situations: ["red-zone", "3rd-short", "goal-line", "plus-territory"],
    coaching: { keys: "The shovel is the run. The fade is what you take when the edge crashes to stop it." },
  }),

  play({
    id: "spread-qb-iso",
    name: "QB Iso",
    aliases: ["Q Iso", "Quarterback Lead"],
    philosophy: "spread-rpo",
    family: "run",
    variantScope: [...SPREAD],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "duo", carrier: "QB", aim: "playside-A" },
    primary: "QB",
    assignments: {
      QB: carry("playside-A", "downhill"),
      RB: block({ block: "base", target: "PSLB" }),
      Y: block({ block: "down" }),
      Z: route("stalk"),
      H: route("stalk"),
      X: route("stalk"),
    },
    tags: ["qb-run", "iso", "short-yardage", "downhill"],
    situations: ["3rd-short", "4th-short", "goal-line", "short-yardage"],
    coaching: { commentary: "The oldest short-yardage math there is: add the quarterback to the run game and the box is even again." },
  }),

  play({
    id: "spread-mesh-rpo",
    name: "Mesh / Zone",
    aliases: ["Mesh RPO", "Zone Mesh"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "H",
    reads: [
      { order: 1, type: "rpo-post", key: "M", ifTake: { give: "RB" }, ifNot: { throw: "H" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: route("shallow", { toSide: "L", meshWith: "Y", meshDepthYd: 4, lane: "over" }, { priorityOrder: 1 }),
      Y: route("shallow", { toSide: "R", meshWith: "H", meshDepthYd: 4, lane: "under" }, { priorityOrder: 2 }),
      Z: route("go", { depth: 14 }, { priorityOrder: 3 }),
      X: route("go", { depth: 14 }, { priorityOrder: 4 }),
    },
    tags: ["rpo", "mesh", "crossers", "second-level-read"],
    situations: ["2nd-long", "3rd-medium", "vs-man", "vs-zone"],
    coaching: { keys: "Full zone mesh with two crossers behind it. If the linebackers step up, throw over them." },
  }),

  play({
    id: "spread-tempo-now",
    name: "Tempo Now",
    aliases: ["Fast Now", "Sugar Huddle Now"],
    philosophy: "spread-rpo",
    family: "pass",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "now",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "$", progression: ["Y", "H", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Y: route("bubble", { toSide: "R" }, { priorityOrder: 1 }),
      H: route("stalk"),
      Z: route("stalk"),
      X: route("slant", { depth: 6 }, { priorityOrder: 2 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["tempo", "now", "perimeter", "quick"],
    situations: ["1st-down", "opening-script", "two-minute", "vs-zone"],
    coaching: {
      keys: "Snap it before the defense is set. The play is easy; the speed of getting to the line is the point.",
    },
  }),

  play({
    id: "spread-four-verts-tempo",
    name: "Verts Tempo",
    aliases: ["Fast Verts", "Tempo Four Verticals"],
    philosophy: "spread-rpo",
    family: "pass",
    variantScope: [...SPREAD],
    formationId: "gun-empty-quads",
    personnelId: "10",
    protection: "big-on-big",
    concept: "four-verticals",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Y", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", { depth: 18 }, { priorityOrder: 3 }),
      H: route("seam", { depth: 16 }, { priorityOrder: 1 }),
      Y: route("seam", { depth: 16 }, { priorityOrder: 2 }),
      F: route("flat", { toSide: "R" }, { priorityOrder: 5 }),
      X: route("go", { depth: 18 }, { priorityOrder: 4 }),
    },
    tags: ["four-verts", "tempo", "empty", "shot"],
    situations: ["2nd-long", "must-score", "two-minute", "vs-cover-3"],
    coaching: { keys: "Four vertical routes against a defense that has not had time to substitute." },
  }),

  play({
    id: "rpo-bash-bubble",
    name: "Bash / Bubble",
    aliases: ["Bash Bubble", "Inverted RPO"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "backside-D" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-pre", key: "apex", keySide: "playside", ifTake: { give: "RB" }, ifNot: { throw: "Y" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("backside-D", "stretch"),
      Y: route("bubble", { toSide: "R" }, { priorityOrder: 1 }),
      Z: route("stalk"),
      H: route("stalk"),
      X: route("crack"),
    },
    tags: ["rpo", "bash", "bubble", "two-way-go"],
    situations: ["1st-down", "2nd-short", "vs-zone", "plus-territory"],
    coaching: { keys: "The run goes to the single-receiver side and the throw goes to the three-receiver side." },
  }),

  play({
    id: "rpo-diamond-triple",
    name: "Diamond Triple",
    aliases: ["Diamond Option", "Three Back Triple"],
    philosophy: "spread-rpo",
    family: "option",
    variantScope: [...SPREAD],
    formationId: "pistol-diamond",
    personnelId: "21",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
      { order: 2, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "A1" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "downhill"),
      A1: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      A2: block({ block: "arc" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["option", "triple", "diamond", "three-back"],
    situations: ["1st-down", "short-yardage", "four-minute", "goal-line"],
    coaching: { commentary: "Triple option out of a pistol set, which puts the same read on the defense from a modern look." },
  }),

  play({
    id: "spread-screen-swing-flood",
    name: "Swing Flood",
    aliases: ["Swing Screen", "Now Swing"],
    philosophy: "spread-rpo",
    family: "screen",
    variantScope: [...SPREAD],
    formationId: "gun-doubles-right",
    personnelId: "10",
    protection: "screen-release",
    concept: "swing-screen",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "W", progression: ["RB", "H", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      RB: route("swing", { toSide: "R" }, { priorityOrder: 1 }),
      H: route("crack"),
      Z: route("stalk"),
      Y: route("stalk"),
      X: route("go", { depth: 16 }, { priorityOrder: 2 }),
    },
    tags: ["screen", "swing", "perimeter", "rush-beater"],
    situations: ["1st-down", "2nd-long", "blitz-beater", "vs-cover-0"],
    coaching: { keys: "The back is in space with two blockers before the rush has covered five yards." },
  }),

  play({
    id: "rpo-glance-tempo-nub",
    name: "Tempo Glance",
    aliases: ["Fast Glance", "No Huddle Glance"],
    philosophy: "spread-rpo",
    family: "rpo",
    variantScope: [...SPREAD],
    formationId: "pistol-trips-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    reads: [
      { order: 1, type: "rpo-post", key: "SS", keySide: "backside", ifTake: { give: "RB" }, ifNot: { throw: "X" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-B", "downhill"),
      X: route("glance", undefined, { priorityOrder: 1 }),
      Z: route("stalk"),
      H: route("stalk"),
      Y: route("stalk"),
    },
    tags: ["rpo", "glance", "tempo", "post-snap"],
    situations: ["1st-down", "opening-script", "two-minute", "vs-cover-3"],
    coaching: { keys: "One call, run and pass attached, snapped fast enough that the call never gets checked." },
  }),
];
