/**
 * Pro style and West Coast.
 *
 * Concepts here are named rather than numbered, which is the Erhardt-Perkins
 * habit: "Sail" means the same three-level stretch regardless of who is running
 * it or what formation it comes from. That maps cleanly onto a compositional
 * library, because the concept IS the assignment set.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, motion, opt, pass, play, route } from "../kit.ts";

const PRO = ["11man", "7man"] as const;

export const WEST_COAST: PlaySpec[] = [
  play({
    id: "wc-sail",
    name: "Sail",
    aliases: ["Flood", "Three Level", "Sail"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["Z", "Y", "H"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", undefined, { priorityOrder: 1 }),
      Y: route("sail", undefined, { priorityOrder: 2 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["flood", "three-level", "sail", "sideline", "zone-beater"],
    situations: ["3rd-medium", "3rd-long", "sideline", "vs-cover-3", "vs-cover-4", "two-minute"],
    coaching: {
      keys: "Deep, intermediate, and flat on one side. Whoever the corner and the flat defender cannot both cover is open.",
      commentary: "Three receivers at three depths against two defenders. One of them comes open every time.",
    },
  }),

  play({
    id: "wc-levels",
    name: "Levels",
    aliases: ["Levels", "In-In"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "levels",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "X", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("drag", { toSide: "R", depthAdj: -1 }, { priorityOrder: 1 }),
      X: route("dig", { depth: 12 }, { priorityOrder: 2 }),
      Z: route("go"),
      Y: route("seam"),
      RB: route("checkdown", undefined, { startDelayMs: 280, priorityOrder: 3 }),
    },
    tags: ["levels", "high-low", "inbreaking", "zone-beater"],
    situations: ["3rd-medium", "1st-down", "vs-zone", "vs-cover-2"],
    coaching: { keys: "Two in-breaking routes at different depths. Read the underneath defender's depth and throw off him." },
  }),

  play({
    id: "wc-spacing",
    name: "Spacing",
    aliases: ["Spacing", "Spot", "Quick Spacing"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "spacing",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["H", "Y", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("hitch", { depth: 6 }, { priorityOrder: 3 }),
      Y: route("stick", { depth: 6 }, { priorityOrder: 2 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      X: route("hitch", { depth: 6 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 240 }),
    },
    tags: ["spacing", "quick-game", "horizontal", "zone-beater", "rhythm"],
    situations: ["3rd-short", "1st-down", "two-minute", "backed-up", "vs-zone"],
    coaching: { keys: "Three receivers in one horizontal band. Throw to the open grass between them." },
  }),

  play({
    id: "wc-smash",
    name: "Smash",
    aliases: ["Smash", "Hi-Lo Corner"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "smash",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["Y", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("hitch", { depth: 6 }, { priorityOrder: 2 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 1 }),
      X: route("dig", { depth: 14 }, { priorityOrder: 3 }),
      H: route("seam"),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["smash", "high-low", "corner", "red-zone"],
    situations: ["red-zone", "3rd-medium", "vs-cover-2", "goal-line", "sideline"],
    coaching: { keys: "High-low the corner. If he sinks, throw the hitch; if he squats, throw over him." },
  }),

  play({
    id: "wc-curl-flat",
    name: "Curl Flat",
    aliases: ["Curl-Flat", "Hook Flat"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "curl-flat",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Z", "H", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("curl", { depth: 12 }, { priorityOrder: 1 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      X: route("curl", { depth: 12 }, { priorityOrder: 3 }),
      Y: route("checkdown"),
      RB: route("swing", { toSide: "L" }, { startDelayMs: 260 }),
    },
    tags: ["curl-flat", "two-man", "zone-beater", "west-coast-staple"],
    situations: ["3rd-medium", "1st-down", "vs-cover-3", "vs-zone"],
    coaching: { keys: "The oldest two-man game in the book. The flat defender cannot have both." },
  }),

  play({
    id: "wc-dagger",
    name: "Dagger",
    aliases: ["Dagger", "Seam Dig"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "dagger",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Y: route("seam", undefined, { priorityOrder: 2 }),
      X: route("dig", { depth: 15 }, { priorityOrder: 1 }),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      H: route("shallow", { toSide: "R" }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 320 }),
    },
    tags: ["dagger", "clearout", "dig", "vertical-stretch"],
    situations: ["3rd-long", "2nd-long", "vs-cover-2", "vs-cover-4", "plus-territory"],
    coaching: {
      keys: "The seam clears the safety out of the dig's window. The dig is the throw.",
    },
  }),

  play({
    id: "wc-drive",
    name: "Drive",
    aliases: ["Drive", "Shallow Dig"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "drive",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("shallow", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("drag", { toSide: "L", depthAdj: 5 }, { priorityOrder: 2 }),
      X: route("go"),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      RB: route("texas", undefined, { startDelayMs: 240, priorityOrder: 4 }),
    },
    tags: ["drive", "shallow", "crosser", "man-beater"],
    situations: ["3rd-medium", "vs-man", "vs-cover-1", "blitz-beater"],
    coaching: { keys: "Shallow underneath, basic cross behind it. Against man the shallow wins on the rub." },
  }),

  play({
    id: "wc-y-stick",
    name: "Y-Stick",
    aliases: ["Stick", "Y Stick Flat"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "pistol-ace-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "stick",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "RB", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      Y: route("stick", { depth: 6 }, { priorityOrder: 1 }),
      RB: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      X: route("slant", undefined, { priorityOrder: 3 }),
      Z: route("go"),
      H: route("hitch", { depth: 5 }),
    },
    tags: ["stick", "quick-game", "three-step", "zone-beater"],
    situations: ["3rd-short", "1st-down", "red-zone", "vs-zone"],
    coaching: { keys: "Same read as the Air Raid version, run out of a pro personnel group." },
  }),

  play({
    id: "wc-slant-flat",
    name: "Slant Flat",
    aliases: ["Slant-Arrow", "Slant Flat"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "slant-flat",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Z", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("slant", undefined, { priorityOrder: 1 }),
      H: route("arrow", { toSide: "R" }, { priorityOrder: 2 }),
      X: route("slant", undefined, { priorityOrder: 3 }),
      Y: route("hitch", { depth: 5 }),
      RB: route("checkdown", undefined, { startDelayMs: 240 }),
    },
    tags: ["slant", "flat", "quick-game", "blitz-beater", "rub"],
    situations: ["3rd-short", "backed-up", "blitz-beater", "vs-man", "two-minute"],
    coaching: { keys: "Fastest answer to pressure in the book. Ball is out on the third step." },
  }),

  play({
    id: "wc-four-verts",
    name: "Four Verticals",
    aliases: ["Verts", "Four Verts", "Seams"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-empty",
    personnelId: "10",
    protection: "big-on-big",
    concept: "four-verticals",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Y", "Z", "F"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("go"),
      Z: route("go"),
      H: route("seam", { landmark: "hash" }, { priorityOrder: 1 }),
      Y: route("seam", { landmark: "hash" }, { priorityOrder: 2 }),
      F: route("checkdown", undefined, { startDelayMs: 260, priorityOrder: 3 }),
    },
    tags: ["verticals", "empty", "seam", "shot"],
    situations: ["2nd-long", "3rd-long", "two-minute", "vs-cover-3", "must-score"],
    coaching: { keys: "Five eligibles, no protection help. The ball has to come out on time or not at all." },
  }),

  play({
    id: "wc-mesh",
    name: "Mesh",
    aliases: ["Mesh", "Cross Mesh"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "mesh",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("shallow", { toSide: "L", meshWith: "Y", meshDepthYd: 6, lane: "over" }, { priorityOrder: 1 }),
      Y: route("shallow", { toSide: "R", meshWith: "H", meshDepthYd: 6, lane: "under" }, { priorityOrder: 2 }),
      Z: route("corner", { depth: 12 }, { priorityOrder: 3 }),
      X: route("go"),
      RB: route("swing", { toSide: "L" }, { startDelayMs: 250, priorityOrder: 4 }),
    },
    tags: ["mesh", "rub", "man-beater", "crossers"],
    situations: ["3rd-medium", "red-zone", "vs-man", "blitz-beater"],
    coaching: { keys: "Six-yard mesh out of pro personnel. Sit against zone, keep running against man." },
  }),

  play({
    id: "wc-pa-post",
    name: "Play Action Post",
    aliases: ["PA Post", "Play Pass Post"],
    philosophy: "pro-west-coast",
    family: "play-action",
    variantScope: ["11man"],
    formationId: "i-pro-right",
    personnelId: "21",
    protection: "big-on-big",
    concept: "pa-post",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Z", "FB"] }],
    assignments: {
      QB: pass("7step", "RB"),
      X: route("post", { depth: 12 }, { priorityOrder: 1 }),
      Z: route("comeback", { depth: 15 }, { priorityOrder: 2 }),
      Y: route("drag", { toSide: "L", depthAdj: 4 }, { priorityOrder: 3 }),
      FB: route("flat", { toSide: "R" }, { startDelayMs: 350, priorityOrder: 4 }),
    },
    tags: ["play-action", "post", "shot", "run-action", "single-high"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-cover-3", "vs-cover-1"],
    coaching: {
      keys: "Sell the run with the line and the back. The post is only there if the safety bites.",
      commentary: "Play action works on first and second down, when the defense still has to respect the run.",
    },
  }),

  play({
    id: "wc-rb-screen",
    name: "Slip Screen",
    aliases: ["RB Screen", "Slip Screen", "Middle Screen"],
    philosophy: "pro-west-coast",
    family: "screen",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "screen-release",
    concept: "rb-screen",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "DE", progression: ["RB"] }],
    assignments: {
      QB: pass("gun-3"),
      RB: route("screen", { toSide: "R" }, { startDelayMs: 500, priorityOrder: 1 }),
      X: route("go"),
      Z: route("go"),
      Y: route("wall", { toSide: "R" }),
      H: route("wall", { toSide: "R" }),
    },
    tags: ["screen", "delayed", "wall", "pressure-answer"],
    situations: ["2nd-long", "3rd-long", "blitz-beater", "backed-up"],
    coaching: { keys: "Invite the rush, let it go by, and put the ball behind it. Patience is the whole play." },
  }),

  play({
    id: "wc-shallow-cross",
    name: "Shallow Cross",
    aliases: ["Shallow", "Cross"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "shallow-cross",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "X", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("shallow", { toSide: "L" }, { priorityOrder: 1 }),
      X: route("dig", { depth: 12 }, { priorityOrder: 2 }),
      Y: route("curl", { depth: 10 }, { priorityOrder: 3 }),
      Z: route("go"),
      RB: route("checkdown", undefined, { startDelayMs: 280, priorityOrder: 4 }),
    },
    tags: ["shallow", "crosser", "dig", "man-beater", "high-low"],
    situations: ["3rd-medium", "3rd-long", "vs-man", "vs-cover-1"],
    coaching: { keys: "Shallow first against man, dig first against zone. Same play, two answers." },
  }),
  play({
    id: "wc-flood-boot",
    name: "Naked Boot",
    aliases: ["Naked", "Boot Flood", "Waggle"],
    philosophy: "pro-west-coast",
    family: "play-action",
    variantScope: ["11man"],
    formationId: "singleback-twins-right",
    personnelId: "11",
    protection: "sprint-right",
    concept: "boot-flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "H", "X"] }],
    assignments: {
      QB: pass("boot", "RB"),
      Y: route("flat", { toSide: "L" }, { priorityOrder: 1 }),
      H: route("over", { toSide: "L" }, { priorityOrder: 2 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      Z: route("post", { depth: 14 }),
      RB: route("stalk", { toSide: "R" }),
    },
    tags: ["boot", "naked", "flood", "run-action", "three-level"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-cover-3", "opening-script"],
    coaching: {
      keys: "Everything flows right and the quarterback comes out left alone. Take the flat, then the crosser.",
      commentary: "It only works if the run game has earned the linebackers' attention.",
    },
  }),

  play({
    id: "wc-levels-over",
    name: "Levels Over",
    aliases: ["Over", "Deep Over"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-tight-doubles",
    personnelId: "11",
    protection: "half-slide",
    concept: "levels",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("under", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("over", { toSide: "L" }, { priorityOrder: 2 }),
      X: route("go"),
      Z: route("go"),
      RB: route("angle", undefined, { startDelayMs: 260, priorityOrder: 3 }),
    },
    tags: ["levels", "over", "under", "crossers", "man-beater", "condensed"],
    situations: ["3rd-medium", "3rd-long", "vs-man", "vs-cover-1"],
    coaching: {
      keys: "Two crossers at two depths going opposite ways. Condensed splits give them room to run.",
    },
  }),

  play({
    id: "wc-snag",
    name: "Snag",
    aliases: ["Snag", "Spot Triangle"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-trey-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "snag",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("corner", { depth: 12 }, { priorityOrder: 2 }),
      H: route("spot", { depth: 6 }, { priorityOrder: 1 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      X: route("slant"),
      RB: route("checkdown", undefined, { startDelayMs: 260 }),
    },
    tags: ["snag", "triangle", "spot", "zone-beater", "quick-game"],
    situations: ["3rd-short", "3rd-medium", "red-zone", "vs-zone"],
    coaching: {
      keys: "A triangle on the flat defender: corner over the top, spot underneath, flat outside.",
    },
  }),

  play({
    id: "wc-post-corner",
    name: "Post Corner",
    aliases: ["Post-Corner", "Double Move Shot"],
    philosophy: "pro-west-coast",
    family: "play-action",
    variantScope: ["11man"],
    formationId: "split-backs-pro",
    personnelId: "21",
    protection: "max-protect",
    concept: "post-corner",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "Y", "FB"] }],
    assignments: {
      QB: pass("7step", "RB"),
      Z: route("post-corner", { depth: 12 }, { priorityOrder: 1 }),
      Y: route("seam", undefined, { priorityOrder: 2 }),
      X: route("comeback", { depth: 15 }, { priorityOrder: 3 }),
      FB: route("flat", { toSide: "L" }, { startDelayMs: 340, priorityOrder: 4 }),
    },
    tags: ["post-corner", "double-move", "shot", "max-protect", "play-action"],
    situations: ["1st-down", "plus-territory", "vs-cover-1", "vs-man"],
    coaching: {
      keys: "Stem at the post hard enough to turn the corner's hips, then break back outside.",
    },
  }),

  play({
    id: "wc-stick-nod",
    name: "Stick Nod",
    aliases: ["Stick-Nod", "Y Stick Nod"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "pistol-trips-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "stick",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "H", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      Y: route("seam", { depth: 14 }, { priorityOrder: 1 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("go", undefined, { priorityOrder: 3 }),
      X: route("dig", { depth: 12 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 280 }),
    },
    tags: ["stick-nod", "double-move", "seam", "shot"],
    situations: ["3rd-short", "plus-territory", "vs-zone", "red-zone"],
    coaching: {
      keys: "Sell the stick, then climb. A linebacker who has been driving on the stick all game is beaten.",
      commentary: "The complement to Stick, and it only exists because Stick gets called so often.",
    },
  }),

  play({
    id: "wc-hoss",
    name: "Hoss",
    aliases: ["Hoss", "Hitch Seam"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "hoss",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "Y", "Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("hitch", { depth: 6 }, { priorityOrder: 3 }),
      X: route("hitch", { depth: 6 }, { priorityOrder: 4 }),
      H: route("seam", undefined, { priorityOrder: 1 }),
      Y: route("seam", undefined, { priorityOrder: 2 }),
      RB: route("checkdown", undefined, { startDelayMs: 260 }),
    },
    tags: ["hoss", "hitch", "seam", "blitz-beater", "two-minute"],
    situations: ["two-minute", "3rd-medium", "blitz-beater", "vs-cover-2"],
    coaching: {
      keys: "Hitches outside, seams inside. Against pressure it is the fastest answer that still gains ten.",
    },
  }),

  play({
    id: "wc-scissors-cross",
    name: "Deep Cross",
    aliases: ["Cross", "Deep Cross", "Drive Over"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-y-off-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "deep-cross",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Y", "X", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Y: route("over", { toSide: "L" }, { priorityOrder: 1 }),
      X: route("post", { depth: 14 }, { priorityOrder: 2 }),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      H: route("under", { toSide: "R" }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["deep-cross", "over", "man-beater", "h-back"],
    situations: ["2nd-long", "3rd-long", "vs-man", "plus-territory"],
    coaching: { keys: "The over route works against the grain at seventeen. Nobody runs with it in zone." },
  }),

  play({
    id: "wc-fade-flat",
    name: "Fade Flat",
    aliases: ["Fade-Out", "Red Zone Fade"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-tight-doubles",
    personnelId: "11",
    protection: "big-on-big",
    concept: "fade-flat",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["Z", "Y", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("fade", undefined, { priorityOrder: 1 }),
      Y: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      X: route("fade", undefined, { priorityOrder: 3 }),
      H: route("spot", { depth: 4 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 240 }),
    },
    tags: ["fade", "red-zone", "goal-line", "back-shoulder", "condensed"],
    situations: ["red-zone", "goal-line", "vs-man", "vs-cover-1"],
    coaching: {
      keys: "Nasty splits give the fade room to work. Throw it where only he can reach it.",
    },
  }),

  play({
    id: "wc-texas-angle",
    name: "Texas",
    aliases: ["Angle", "Texas Route", "Back Angle"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "texas",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["RB", "Y", "Z"] }],
    assignments: {
      QB: pass("gun-3"),
      RB: route("angle", undefined, { priorityOrder: 1 }),
      Y: route("seam", undefined, { priorityOrder: 2 }),
      Z: route("dig", { depth: 12 }, { priorityOrder: 3 }),
      X: route("go"),
      H: route("shallow", { toSide: "R" }, { priorityOrder: 4 }),
    },
    tags: ["texas", "angle", "back", "man-beater", "blitz-beater"],
    situations: ["3rd-medium", "vs-man", "blitz-beater", "2nd-long"],
    coaching: {
      keys: "The back sells outside then cuts under. A linebacker covering him in space loses every time.",
    },
  }),

  play({
    id: "wc-tunnel-screen",
    name: "Tunnel Screen",
    aliases: ["Tunnel", "WR Tunnel"],
    philosophy: "pro-west-coast",
    family: "screen",
    variantScope: [...PRO],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "screen-release",
    concept: "tunnel-screen",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["H"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: route("pivot", { toSide: "L", depth: 1 }, { startDelayMs: 200, priorityOrder: 1 }),
      Z: route("wall", { toSide: "R" }),
      X: route("go"),
      Y: route("wall", { toSide: "R" }),
      RB: route("checkdown", undefined, { startDelayMs: 260 }),
    },
    tags: ["screen", "tunnel", "wall", "perimeter"],
    situations: ["2nd-long", "3rd-long", "blitz-beater", "backed-up"],
    coaching: { keys: "The slot works back inside behind two blockers while the outside clears." },
  }),

  play({
    id: "wc-pa-boot-flood",
    name: "PA Boot Flood",
    aliases: ["Waggle", "Naked Flood", "Boot Right"],
    philosophy: "pro-west-coast",
    family: "play-action",
    variantScope: [...PRO],
    formationId: "i-twins-right",
    personnelId: "21",
    protection: "sprint-right",
    concept: "boot-flood",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["FB", "H", "X"] }],
    assignments: {
      QB: pass("boot", "RB"),
      FB: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      H: route("sail", { depth: 12 }, { priorityOrder: 2 }),
      X: route("over", { depth: 16 }, { priorityOrder: 3, startDelayMs: 200 }),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 4 }),
    },
    tags: ["play-action", "boot", "flood", "three-level"],
    situations: ["1st-down", "2nd-short", "vs-cover-3", "opening-script"],
    coaching: { keys: "Full run fake, then move the pocket away from the pressure and read the flat defender." },
  }),

  play({
    id: "wc-pa-crossers",
    name: "PA Crossers",
    aliases: ["Play Pass Cross", "Deep Cross"],
    philosophy: "pro-west-coast",
    family: "play-action",
    variantScope: [...PRO],
    formationId: "singleback-twins-right",
    personnelId: "11",
    protection: "max-protect",
    concept: "crossers",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "H", "Z"] }],
    assignments: {
      QB: pass("5step", "RB"),
      X: route("over", { depth: 16 }, { priorityOrder: 1 }),
      H: route("shallow", { toSide: "L" }, { priorityOrder: 2 }),
      Z: route("post", { depth: 18 }, { priorityOrder: 3 }),
      Y: route("checkdown", { toSide: "L" }, { priorityOrder: 4 }),
    },
    tags: ["play-action", "crossers", "man-beater", "chunk"],
    situations: ["1st-down", "2nd-short", "vs-man", "plus-territory"],
    coaching: { keys: "Two crossers at different depths off run action. Man coverage has to run through traffic to stay with them." },
  }),

  play({
    id: "wc-y-option",
    name: "Y Option",
    aliases: ["Option Route", "Choice Y"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-y-off-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "y-option",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["Y", "H", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Y: opt("stick", "leverage", [
        { when: "defender inside", route: "out", mods: { depth: 8 } },
        { when: "defender outside", route: "dig", mods: { depth: 8 } },
        { when: "defender deep", route: "hitch", mods: { depth: 7 } },
      ], { depth: 8 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("go", { depth: 16 }, { priorityOrder: 3 }),
      X: route("dig", { depth: 12 }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["option-route", "y-option", "leverage", "third-down"],
    situations: ["3rd-medium", "3rd-short", "vs-man", "vs-zone"],
    coaching: { keys: "The tight end breaks away from leverage at eight yards and the quarterback throws off the same picture." },
  }),

  play({
    id: "wc-double-slant-flat",
    name: "Double Slant Flat",
    aliases: ["Slant Flat", "Quick Double"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "split-backs-pro",
    personnelId: "21",
    protection: "half-slide",
    concept: "slant-flat",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Z", "RB", "Y"] }],
    assignments: {
      QB: pass("3step"),
      Z: route("slant", { depth: 6 }, { priorityOrder: 1 }),
      RB: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Y: route("seam", { depth: 12 }, { priorityOrder: 3 }),
      X: route("slant", { depth: 6 }, { priorityOrder: 4 }),
      FB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["slant-flat", "quick", "rhythm", "beginner-friendly"],
    situations: ["1st-down", "3rd-short", "blitz-beater", "vs-zone"],
    coaching: { keys: "Three-step drop, ball out on time. The flat route and the slant put the same defender in a bind." },
  }),

  play({
    id: "wc-halfback-option",
    name: "Halfback Option",
    aliases: ["Back Option", "Angle Choice"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "split-backs-pro",
    personnelId: "21",
    protection: "half-slide",
    concept: "angle",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "W", progression: ["RB", "Y", "Z"] }],
    assignments: {
      QB: pass("5step"),
      RB: route("angle", { depth: 5 }, { priorityOrder: 1 }),
      FB: route("flat", { toSide: "L" }, { priorityOrder: 2 }),
      Y: route("dig", { depth: 12 }, { priorityOrder: 3 }),
      Z: route("go", { depth: 16 }, { priorityOrder: 4 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 5 }),
    },
    tags: ["angle", "back-route", "man-beater", "third-down"],
    situations: ["3rd-medium", "vs-man", "2nd-long", "red-zone"],
    coaching: { keys: "Sell the flat, then break back inside. A linebacker in man coverage cannot change direction with a back." },
  }),

  play({
    id: "wc-y-sail-unit",
    name: "Y Sail",
    aliases: ["Sail Right", "Y Corner Flood"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-nub-trips",
    personnelId: "11",
    protection: "half-slide",
    concept: "sail",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "backside", progression: ["X", "H", "Z", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("flat", { toSide: "L" }, { priorityOrder: 1 }),
      H: route("sail", { depth: 12 }, { priorityOrder: 2 }),
      Z: route("go", { depth: 18 }, { priorityOrder: 3 }),
      Y: route("checkdown", { toSide: "R" }, { priorityOrder: 4 }),
      RB: route("swing", { toSide: "R" }, { priorityOrder: 5 }),
    },
    tags: ["sail", "flood", "three-level", "trips"],
    situations: ["3rd-medium", "2nd-long", "vs-zone", "sideline"],
    coaching: { keys: "Three routes at three depths on one side. The flat defender picks one and the quarterback takes another." },
  }),

  play({
    id: "wc-jet-quick",
    name: "Jet Quick",
    aliases: ["Motion Quick", "Fly Now"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "singleback-twins-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "quick",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "$", progression: ["H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: motion("jet", route("bubble", { toSide: "L" }, { priorityOrder: 1 }), 1100, "L"),
      Z: route("slant", { depth: 6 }, { priorityOrder: 2 }),
      X: route("hitch", { depth: 6 }, { priorityOrder: 3 }),
      Y: route("stalk"),
      RB: route("checkdown", { toSide: "R" }, { priorityOrder: 4 }),
    },
    tags: ["motion", "quick", "perimeter", "leverage"],
    situations: ["1st-down", "2nd-short", "opening-script", "vs-zone"],
    coaching: { keys: "Motion changes the count on the perimeter after the defence has already declared." },
  }),

  play({
    id: "wc-pa-shot-post",
    name: "PA Shot",
    aliases: ["Play Action Post", "Deep Shot"],
    philosophy: "pro-west-coast",
    family: "play-action",
    variantScope: [...PRO],
    formationId: "i-twins-right",
    personnelId: "21",
    protection: "max-protect",
    concept: "post-shot",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Z", "H"] }],
    assignments: {
      QB: pass("7step", "RB"),
      X: route("post", { depth: 20 }, { priorityOrder: 1 }),
      Z: route("go", { depth: 18 }, { priorityOrder: 2 }),
      H: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      FB: route("checkdown", { toSide: "L" }, { priorityOrder: 4 }),
    },
    tags: ["play-action", "shot", "max-protect", "single-high-beater"],
    situations: ["1st-down", "plus-territory", "vs-cover-3", "opening-script"],
    coaching: {
      commentary: "Two backs stay in and block, which buys the extra beat a twenty-yard post needs.",
    },
  }),

  play({
    id: "wc-fb-delay",
    name: "Fullback Delay",
    aliases: ["Delay", "FB Leak"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "i-pro-right",
    personnelId: "21",
    protection: "half-slide",
    concept: "delay",
    primary: "FB",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["FB", "Y", "Z"] }],
    assignments: {
      QB: pass("5step"),
      FB: route("checkdown", { toSide: "R" }, { priorityOrder: 1, startDelayMs: 500 }),
      Y: route("seam", { depth: 14 }, { priorityOrder: 2 }),
      Z: route("dig", { depth: 12 }, { priorityOrder: 3 }),
      X: route("go", { depth: 18 }, { priorityOrder: 4 }),
      RB: route("flat", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["delay", "fullback", "zone-beater", "answer"],
    situations: ["3rd-medium", "2nd-long", "blitz-beater", "vs-zone"],
    coaching: { keys: "Show protection for a beat, then release into the space the linebackers vacated." },
  }),

  play({
    id: "wc-bench",
    name: "Bench",
    aliases: ["Bench Concept", "Out and Corner"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "bench",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "CB", progression: ["Z", "H", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 1 }),
      H: route("out", { depth: 8 }, { priorityOrder: 2 }),
      X: route("go", { depth: 18 }, { priorityOrder: 3 }),
      Y: route("dig", { depth: 12 }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["bench", "sideline", "high-low", "clock"],
    situations: ["two-minute", "3rd-medium", "sideline", "vs-cover-3"],
    coaching: { keys: "Two out-breaking routes on the same corner at eight and fourteen." },
  }),

  play({
    id: "wc-slot-screen",
    name: "Slot Screen",
    aliases: ["Now Screen", "Quick Screen"],
    philosophy: "pro-west-coast",
    family: "screen",
    variantScope: [...PRO],
    formationId: "gun-trey-right",
    personnelId: "11",
    protection: "screen-release",
    concept: "slot-screen",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "$", progression: ["H"] }],
    assignments: {
      QB: pass("gun-quick"),
      H: route("screen", { toSide: "R" }, { priorityOrder: 1, startDelayMs: 200 }),
      Z: route("crack"),
      Y: route("stalk"),
      X: route("go", { depth: 16 }, { priorityOrder: 2 }),
      RB: route("swing", { toSide: "L" }, { priorityOrder: 3 }),
    },
    tags: ["screen", "slot", "perimeter", "rush-beater"],
    situations: ["1st-down", "2nd-long", "blitz-beater", "vs-zone"],
    coaching: { keys: "Two blockers in front of one slot receiver in space is a good trade on any down." },
  }),

  play({
    id: "wc-red-zone-spot",
    name: "Red Zone Spot",
    aliases: ["Snag", "Spot Concept"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-bunch-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "snag",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "H", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Y: route("spot", { depth: 6 }, { priorityOrder: 1 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      Z: route("corner", { depth: 9 }, { priorityOrder: 3 }),
      X: route("fade", { depth: 8 }, { priorityOrder: 4 }),
      RB: route("checkdown", { toSide: "L" }, { priorityOrder: 5 }),
    },
    tags: ["snag", "spot", "red-zone", "triangle", "bunch"],
    situations: ["red-zone", "3rd-short", "goal-line", "vs-zone"],
    coaching: { keys: "A three-man triangle out of a bunch, with the fade backside if they load the bunch." },
  }),

  play({
    id: "wc-double-post-shot",
    name: "Double Post",
    aliases: ["Post Post", "Deep Choice"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-tight-doubles",
    personnelId: "12",
    protection: "max-protect",
    concept: "double-post",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["Z", "X", "Y"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("post", { depth: 18 }, { priorityOrder: 1 }),
      X: route("post", { depth: 14 }, { priorityOrder: 2 }),
      Y: route("seam", { depth: 12 }, { priorityOrder: 3 }),
      H: route("checkdown", { toSide: "R" }, { priorityOrder: 4 }),
      RB: block({ block: "pass-set" }),
    },
    tags: ["double-post", "shot", "max-protect", "two-tight"],
    situations: ["1st-down", "plus-territory", "vs-cover-1", "must-score"],
    coaching: { keys: "The inside post occupies the free safety and the outside post runs past where he was." },
  }),

  play({
    id: "wc-two-minute-drive",
    name: "Two Minute Drive",
    aliases: ["Hurry Up Drive", "Sideline Drive"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-empty-quads",
    personnelId: "10",
    protection: "big-on-big",
    concept: "drive",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["F", "H", "Z", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      F: route("shallow", { toSide: "L" }, { priorityOrder: 1 }),
      H: route("dig", { depth: 12 }, { priorityOrder: 2 }),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      Y: route("out", { depth: 8 }, { priorityOrder: 4 }),
      X: route("go", { depth: 18 }, { priorityOrder: 5 }),
    },
    tags: ["drive", "empty", "clock", "two-minute", "sideline"],
    situations: ["two-minute", "must-score", "2nd-long", "sideline"],
    coaching: {
      keys: "Empty means no protection help, so the ball has to come out. Two of the five routes finish out of bounds.",
    },
  }),
];
