/**
 * Pro style and West Coast.
 *
 * Concepts here are named rather than numbered, which is the Erhardt-Perkins
 * habit: "Sail" means the same three-level stretch regardless of who is running
 * it or what formation it comes from. That maps cleanly onto a compositional
 * library, because the concept IS the assignment set.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { pass, play, route } from "../kit.ts";

const PRO = ["11man", "7man"] as const;

export const WEST_COAST: PlaySpec[] = [
  play({
    id: "wc-sail",
    name: "Sail",
    aliases: ["Flood", "Three Level", "Sail"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["Z", "Y", "H"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("go", undefined, { priorityOrder: 1 }),
      Y: route("sail", undefined, { priorityOrder: 2 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 3 }),
      X: route("comeback", { depth: 14 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["flood", "three-level", "sail", "sideline", "zone-beater"],
    situations: ["3rd-medium", "3rd-long", "sideline", "vs-cover-3", "vs-cover-4", "two-minute"],
    coaching: {
      keys: "Deep, intermediate, and flat on one side. Whoever the corner and the flat defender cannot both cover is open.",
      commentary: "Three receivers at three depths against two defenders. One of them comes open every time.",
    },
  }),

  play({
    id: "wc-levels",
    name: "Levels",
    aliases: ["Levels", "In-In"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "levels",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "X", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("drag", { toSide: "R", depthAdj: -1 }, { priorityOrder: 1 }),
      X: route("dig", { depth: 12 }, { priorityOrder: 2 }),
      Z: route("go"),
      Y: route("seam"),
      RB: route("checkdown", undefined, { startDelayMs: 280, priorityOrder: 3 }),
    },
    tags: ["levels", "high-low", "inbreaking", "zone-beater"],
    situations: ["3rd-medium", "1st-down", "vs-zone", "vs-cover-2"],
    coaching: { keys: "Two in-breaking routes at different depths. Read the underneath defender's depth and throw off him." },
  }),

  play({
    id: "wc-spacing",
    name: "Spacing",
    aliases: ["Spacing", "Spot", "Quick Spacing"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "spacing",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["H", "Y", "Z"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("hitch", { depth: 6 }, { priorityOrder: 3 }),
      Y: route("stick", { depth: 6 }, { priorityOrder: 2 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      X: route("hitch", { depth: 6 }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 240 }),
    },
    tags: ["spacing", "quick-game", "horizontal", "zone-beater", "rhythm"],
    situations: ["3rd-short", "1st-down", "two-minute", "backed-up", "vs-zone"],
    coaching: { keys: "Three receivers in one horizontal band. Throw to the open grass between them." },
  }),

  play({
    id: "wc-smash",
    name: "Smash",
    aliases: ["Smash", "Hi-Lo Corner"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "smash",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "CB", keySide: "playside", progression: ["Y", "Z", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("hitch", { depth: 6 }, { priorityOrder: 2 }),
      Y: route("corner", { depth: 12 }, { priorityOrder: 1 }),
      X: route("dig", { depth: 14 }, { priorityOrder: 3 }),
      H: route("seam"),
      RB: route("checkdown", undefined, { startDelayMs: 300 }),
    },
    tags: ["smash", "high-low", "corner", "red-zone"],
    situations: ["red-zone", "3rd-medium", "vs-cover-2", "goal-line", "sideline"],
    coaching: { keys: "High-low the corner. If he sinks, throw the hitch; if he squats, throw over him." },
  }),

  play({
    id: "wc-curl-flat",
    name: "Curl Flat",
    aliases: ["Curl-Flat", "Hook Flat"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "curl-flat",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Z", "H", "X"] }],
    assignments: {
      QB: pass("gun-3"),
      Z: route("curl", { depth: 12 }, { priorityOrder: 1 }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      X: route("curl", { depth: 12 }, { priorityOrder: 3 }),
      Y: route("checkdown"),
      RB: route("swing", { toSide: "L" }, { startDelayMs: 260 }),
    },
    tags: ["curl-flat", "two-man", "zone-beater", "west-coast-staple"],
    situations: ["3rd-medium", "1st-down", "vs-cover-3", "vs-zone"],
    coaching: { keys: "The oldest two-man game in the book. The flat defender cannot have both." },
  }),

  play({
    id: "wc-dagger",
    name: "Dagger",
    aliases: ["Dagger", "Seam Dig"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "dagger",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      Y: route("seam", undefined, { priorityOrder: 2 }),
      X: route("dig", { depth: 15 }, { priorityOrder: 1 }),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      H: route("shallow", { toSide: "R" }, { priorityOrder: 4 }),
      RB: route("checkdown", undefined, { startDelayMs: 320 }),
    },
    tags: ["dagger", "clearout", "dig", "vertical-stretch"],
    situations: ["3rd-long", "2nd-long", "vs-cover-2", "vs-cover-4", "plus-territory"],
    coaching: {
      keys: "The seam clears the safety out of the dig's window. The dig is the throw.",
    },
  }),

  play({
    id: "wc-drive",
    name: "Drive",
    aliases: ["Drive", "Shallow Dig"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "drive",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("shallow", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("drag", { toSide: "L", depthAdj: 5 }, { priorityOrder: 2 }),
      X: route("go"),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      RB: route("texas", undefined, { startDelayMs: 240, priorityOrder: 4 }),
    },
    tags: ["drive", "shallow", "crosser", "man-beater"],
    situations: ["3rd-medium", "vs-man", "vs-cover-1", "blitz-beater"],
    coaching: { keys: "Shallow underneath, basic cross behind it. Against man the shallow wins on the rub." },
  }),

  play({
    id: "wc-y-stick",
    name: "Y-Stick",
    aliases: ["Stick", "Y Stick Flat"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "pistol-ace-right",
    personnelId: "11",
    protection: "slide-right",
    concept: "stick",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Y", "RB", "X"] }],
    assignments: {
      QB: pass("gun-quick"),
      Y: route("stick", { depth: 6 }, { priorityOrder: 1 }),
      RB: route("flat", { toSide: "R" }, { priorityOrder: 2 }),
      X: route("slant", undefined, { priorityOrder: 3 }),
      Z: route("go"),
      H: route("hitch", { depth: 5 }),
    },
    tags: ["stick", "quick-game", "three-step", "zone-beater"],
    situations: ["3rd-short", "1st-down", "red-zone", "vs-zone"],
    coaching: { keys: "Same read as the Air Raid version, run out of a pro personnel group." },
  }),

  play({
    id: "wc-slant-flat",
    name: "Slant Flat",
    aliases: ["Slant-Arrow", "Slant Flat"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "big-on-big",
    concept: "slant-flat",
    primary: "Z",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["Z", "H"] }],
    assignments: {
      QB: pass("gun-quick"),
      Z: route("slant", undefined, { priorityOrder: 1 }),
      H: route("arrow", { toSide: "R" }, { priorityOrder: 2 }),
      X: route("slant", undefined, { priorityOrder: 3 }),
      Y: route("hitch", { depth: 5 }),
      RB: route("checkdown", undefined, { startDelayMs: 240 }),
    },
    tags: ["slant", "flat", "quick-game", "blitz-beater", "rub"],
    situations: ["3rd-short", "backed-up", "blitz-beater", "vs-man", "two-minute"],
    coaching: { keys: "Fastest answer to pressure in the book. Ball is out on the third step." },
  }),

  play({
    id: "wc-four-verts",
    name: "Four Verticals",
    aliases: ["Verts", "Four Verts", "Seams"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-empty",
    personnelId: "10",
    protection: "big-on-big",
    concept: "four-verticals",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["H", "Y", "Z", "F"] }],
    assignments: {
      QB: pass("gun-3"),
      X: route("go"),
      Z: route("go"),
      H: route("seam", { landmark: "hash" }, { priorityOrder: 1 }),
      Y: route("seam", { landmark: "hash" }, { priorityOrder: 2 }),
      F: route("checkdown", undefined, { startDelayMs: 260, priorityOrder: 3 }),
    },
    tags: ["verticals", "empty", "seam", "shot"],
    situations: ["2nd-long", "3rd-long", "two-minute", "vs-cover-3", "must-score"],
    coaching: { keys: "Five eligibles, no protection help. The ball has to come out on time or not at all." },
  }),

  play({
    id: "wc-mesh",
    name: "Mesh",
    aliases: ["Mesh", "Cross Mesh"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-twins-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "mesh",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("shallow", { toSide: "L", meshWith: "Y", meshDepthYd: 6, lane: "over" }, { priorityOrder: 1 }),
      Y: route("shallow", { toSide: "R", meshWith: "H", meshDepthYd: 6, lane: "under" }, { priorityOrder: 2 }),
      Z: route("corner", { depth: 12 }, { priorityOrder: 3 }),
      X: route("go"),
      RB: route("swing", { toSide: "L" }, { startDelayMs: 250, priorityOrder: 4 }),
    },
    tags: ["mesh", "rub", "man-beater", "crossers"],
    situations: ["3rd-medium", "red-zone", "vs-man", "blitz-beater"],
    coaching: { keys: "Six-yard mesh out of pro personnel. Sit against zone, keep running against man." },
  }),

  play({
    id: "wc-pa-post",
    name: "Play Action Post",
    aliases: ["PA Post", "Play Pass Post"],
    philosophy: "pro-west-coast",
    family: "play-action",
    variantScope: ["11man"],
    formationId: "i-pro-right",
    personnelId: "21",
    protection: "big-on-big",
    concept: "pa-post",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Z", "FB"] }],
    assignments: {
      QB: pass("7step", "RB"),
      X: route("post", { depth: 12 }, { priorityOrder: 1 }),
      Z: route("comeback", { depth: 15 }, { priorityOrder: 2 }),
      Y: route("drag", { toSide: "L", depthAdj: 4 }, { priorityOrder: 3 }),
      FB: route("flat", { toSide: "R" }, { startDelayMs: 350, priorityOrder: 4 }),
    },
    tags: ["play-action", "post", "shot", "run-action", "single-high"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-cover-3", "vs-cover-1"],
    coaching: {
      keys: "Sell the run with the line and the back. The post is only there if the safety bites.",
      commentary: "Play action works on first and second down, when the defense still has to respect the run.",
    },
  }),

  play({
    id: "wc-rb-screen",
    name: "Slip Screen",
    aliases: ["RB Screen", "Slip Screen", "Middle Screen"],
    philosophy: "pro-west-coast",
    family: "screen",
    variantScope: [...PRO],
    formationId: "gun-doubles-right",
    personnelId: "11",
    protection: "screen-release",
    concept: "rb-screen",
    primary: "RB",
    reads: [{ order: 1, type: "progression", key: "DE", progression: ["RB"] }],
    assignments: {
      QB: pass("gun-3"),
      RB: route("screen", { toSide: "R" }, { startDelayMs: 500, priorityOrder: 1 }),
      X: route("go"),
      Z: route("go"),
      Y: route("wall", { toSide: "R" }),
      H: route("wall", { toSide: "R" }),
    },
    tags: ["screen", "delayed", "wall", "pressure-answer"],
    situations: ["2nd-long", "3rd-long", "blitz-beater", "backed-up"],
    coaching: { keys: "Invite the rush, let it go by, and put the ball behind it. Patience is the whole play." },
  }),

  play({
    id: "wc-shallow-cross",
    name: "Shallow Cross",
    aliases: ["Shallow", "Cross"],
    philosophy: "pro-west-coast",
    family: "pass",
    variantScope: [...PRO],
    formationId: "gun-trips-right",
    personnelId: "11",
    protection: "half-slide",
    concept: "shallow-cross",
    primary: "H",
    reads: [{ order: 1, type: "progression", key: "MIKE", progression: ["H", "X", "Y", "RB"] }],
    assignments: {
      QB: pass("gun-3"),
      H: route("shallow", { toSide: "L" }, { priorityOrder: 1 }),
      X: route("dig", { depth: 12 }, { priorityOrder: 2 }),
      Y: route("curl", { depth: 10 }, { priorityOrder: 3 }),
      Z: route("go"),
      RB: route("checkdown", undefined, { startDelayMs: 280, priorityOrder: 4 }),
    },
    tags: ["shallow", "crosser", "dig", "man-beater", "high-low"],
    situations: ["3rd-medium", "3rd-long", "vs-man", "vs-cover-1"],
    coaching: { keys: "Shallow first against man, dig first against zone. Same play, two answers." },
  }),
];
