/**
 * Zone running.
 *
 * The defining trait is covered/uncovered rules rather than assigned angles:
 * the line blocks an area, and the back reads the first down lineman's helmet
 * and takes it bang, bend, or bounce. Because the scheme resolves through that
 * lookup, inside zone and outside zone differ by one landmark rather than by
 * ten hand-drawn arrows.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, carry, pass, play, route } from "../kit.ts";

const TACKLE = ["11man"] as const;

export const ZONE_RUN: PlaySpec[] = [
  play({
    id: "zone-inside",
    name: "Inside Zone",
    aliases: ["IZ", "Tight Zone", "Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill", "backside-A"),
      Y: block({ block: "climb", target: "PSLB" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "inside-zone", "combo", "bang-bend-bounce"],
    situations: ["1st-down", "2nd-short", "short-yardage", "four-minute", "opening-script"],
    coaching: {
      install: "Covered, block him. Uncovered, combo with your neighbour and climb.",
      keys: "Aiming point is the playside A gap. Press it, then take what the first down lineman gives you.",
      commentary: "The most-run play in football because it is right against every front without being checked.",
    },
  }),

  play({
    id: "zone-outside",
    name: "Outside Zone",
    aliases: ["OZ", "Wide Zone", "Stretch"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "stretch", "playside-B"),
      Y: block({ block: "reach" }),
      H: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "outside-zone", "stretch", "reach", "perimeter"],
    situations: ["1st-down", "2nd-short", "plus-territory", "opening-script"],
    coaching: {
      keys: "Press the edge until the defense runs with you. The cutback opens up behind their pursuit.",
    },
  }),

  play({
    id: "zone-split",
    name: "Split Zone",
    aliases: ["Slice", "H-Back Slice", "Split Flow"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "split-zone", "slice", "h-back", "backside"],
    situations: ["1st-down", "short-yardage", "3rd-short", "red-zone"],
    coaching: {
      install: "The H-back crosses the formation to kick the backside end, which is the one defender zone rules cannot account for.",
    },
  }),

  play({
    id: "zone-mid",
    name: "Mid Zone",
    aliases: ["Mid Zone", "Tight Stretch"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "pistol-ace-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "stretch", "playside-A"),
      Y: block({ block: "reach" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "mid-zone", "landmark", "wide-zone-family"],
    situations: ["1st-down", "2nd-short", "midfield"],
    coaching: { keys: "The landmark sits between inside and outside. The back runs a track and takes what the first down lineman gives him." },
  }),

  play({
    id: "zone-read",
    name: "Zone Read",
    aliases: ["Read Option", "IZ Read"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      {
        order: 1,
        type: "zone-read",
        key: "DE",
        keySide: "backside",
        ifTake: { keep: "QB" },
        ifNot: { give: "RB" },
      },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Y: block({ block: "climb", target: "PSLB" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "read", "option", "qb-run", "numbers"],
    situations: ["1st-down", "3rd-short", "short-yardage", "red-zone"],
    coaching: {
      keys: "Leave the backside end unblocked and read him. He crashes, pull it; he sits, give it.",
      commentary: "Blocking one fewer defender is how a spread offense gets even numbers without an extra tight end.",
    },
  }),

  play({
    id: "zone-pin-pull",
    name: "Pin and Pull",
    aliases: ["Pin & Pull", "Pin Pull Sweep"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Y: block({ block: "down" }),
      H: block({ block: "crack" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "hybrid", "pin-pull", "perimeter", "gap-and-zone"],
    situations: ["1st-down", "plus-territory", "vs-zone"],
    coaching: { install: "Covered linemen pin down, uncovered linemen pull around. A zone play with gap-scheme angles." },
  }),

  play({
    id: "zone-counter",
    name: "Zone Counter",
    aliases: ["Zone Cutback", "Counter Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "pistol-ace-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "backside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("backside-B", "counter-step"),
      Y: block({ block: "reach" }),
      H: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "counter", "cutback", "misdirection"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: { keys: "Zone blocking with counter backfield action. It is the answer to a fast-flowing linebacker." },
  }),

  play({
    id: "zone-stretch-boot",
    name: "Stretch Boot",
    aliases: ["Naked Boot", "Zone Boot", "Bootleg"],
    philosophy: "zone-run",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    protection: "half-slide",
    concept: "boot-flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["H", "Y", "X"] }],
    assignments: {
      QB: pass("boot", "RB"),
      RB: route("stalk", { toSide: "L" }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("drag", { toSide: "R", depthAdj: 8 }, { priorityOrder: 2 }),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      X: route("post", { depth: 12 }, { priorityOrder: 4 }),
    },
    tags: ["play-action", "boot", "flood", "three-level", "run-action"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-cover-3", "opening-script"],
    coaching: {
      keys: "Three levels to the boot side. Take the first one that is open and get the ball out.",
      commentary: "The play the wide zone game is really running toward.",
    },
  }),

  play({
    id: "zone-dive",
    name: "Zone Dive",
    aliases: ["FB Dive", "Zone Dive"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "dive", "option-family", "flexbone", "quick-hitting"],
    situations: ["short-yardage", "1st-down", "4th-short", "four-minute"],
    coaching: { install: "Zone rules on a fullback dive. The option game's answer to a defense that stops the triple." },
  }),

  play({
    id: "zone-inverted-veer",
    name: "Inverted Veer",
    aliases: ["Dash Read", "Inverted Veer"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    reads: [
      { order: 1, type: "zone-read", key: "EMLOS", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Y: block({ block: "down" }),
      H: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "option", "read", "qb-run", "edge"],
    situations: ["3rd-short", "red-zone", "goal-line", "short-yardage"],
    coaching: { keys: "The back runs the sweep track and the quarterback keeps it downhill. Roles inverted from a zone read." },
  }),

  play({
    id: "zone-bluff",
    name: "Zone Bluff",
    aliases: ["Slice Read", "Zone Bluff"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "pistol-ace-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "zone-read", key: "DE", keySide: "backside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Y: block({ block: "arc" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "read", "bluff", "arc", "qb-run"],
    situations: ["1st-down", "3rd-short", "red-zone"],
    coaching: { keys: "The tight end fakes the slice and arcs to the alley instead, which is the read key's tell." },
  }),
];
