/**
 * Zone running.
 *
 * The defining trait is covered/uncovered rules rather than assigned angles:
 * the line blocks an area, and the back reads the first down lineman's helmet
 * and takes it bang, bend, or bounce. Because the scheme resolves through that
 * lookup, inside zone and outside zone differ by one landmark rather than by
 * ten hand-drawn arrows.
 */

import type { PlaySpec } from "../../../../src/lib/playbook/types.ts";
import { block, carry, motion, pass, pitch, play, route } from "../kit.ts";

const TACKLE = ["11man"] as const;

export const ZONE_RUN: PlaySpec[] = [
  play({
    id: "zone-inside",
    name: "Inside Zone",
    aliases: ["IZ", "Tight Zone", "Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill", "backside-A"),
      Y: block({ block: "climb", target: "PSLB" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "inside-zone", "combo", "bang-bend-bounce"],
    situations: ["1st-down", "2nd-short", "short-yardage", "four-minute", "opening-script"],
    coaching: {
      install: "Covered, block him. Uncovered, combo with your neighbour and climb.",
      keys: "Aiming point is the playside A gap. Press it, then take what the first down lineman gives you.",
      commentary: "The most-run play in football because it is right against every front without being checked.",
    },
  }),

  play({
    id: "zone-outside",
    name: "Outside Zone",
    aliases: ["OZ", "Wide Zone", "Stretch"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "stretch", "playside-B"),
      Y: block({ block: "reach" }),
      H: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "outside-zone", "stretch", "reach", "perimeter"],
    situations: ["1st-down", "2nd-short", "plus-territory", "opening-script"],
    coaching: {
      keys: "Press the edge until the defense runs with you. The cutback opens up behind their pursuit.",
    },
  }),

  play({
    id: "zone-split",
    name: "Split Zone",
    aliases: ["Slice", "H-Back Slice", "Split Flow"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "split-zone", "slice", "h-back", "backside"],
    situations: ["1st-down", "short-yardage", "3rd-short", "red-zone"],
    coaching: {
      install: "The H-back crosses the formation to kick the backside end, which is the one defender zone rules cannot account for.",
    },
  }),

  play({
    id: "zone-mid",
    name: "Mid Zone",
    aliases: ["Mid Zone", "Tight Stretch"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "pistol-ace-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "stretch", "playside-A"),
      Y: block({ block: "reach" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "mid-zone", "landmark", "wide-zone-family"],
    situations: ["1st-down", "2nd-short", "midfield"],
    coaching: { keys: "The landmark sits between inside and outside. The back runs a track and takes what the first down lineman gives him." },
  }),

  play({
    id: "zone-read",
    name: "Zone Read",
    aliases: ["Read Option", "IZ Read"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      {
        order: 1,
        type: "zone-read",
        key: "DE",
        keySide: "backside",
        ifTake: { keep: "QB" },
        ifNot: { give: "RB" },
      },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Y: block({ block: "climb", target: "PSLB" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "read", "option", "qb-run", "numbers"],
    situations: ["1st-down", "3rd-short", "short-yardage", "red-zone"],
    coaching: {
      keys: "Leave the backside end unblocked and read him. He crashes, pull it; he sits, give it.",
      commentary: "Blocking one fewer defender is how a spread offense gets even numbers without an extra tight end.",
    },
  }),

  play({
    id: "zone-pin-pull",
    name: "Pin and Pull",
    aliases: ["Pin & Pull", "Pin Pull Sweep"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Y: block({ block: "down" }),
      H: block({ block: "crack" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "hybrid", "pin-pull", "perimeter", "gap-and-zone"],
    situations: ["1st-down", "plus-territory", "vs-zone"],
    coaching: { install: "Covered linemen pin down, uncovered linemen pull around. A zone play with gap-scheme angles." },
  }),

  play({
    id: "zone-counter",
    name: "Zone Counter",
    aliases: ["Zone Cutback", "Counter Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "pistol-ace-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "backside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("backside-B", "counter-step"),
      Y: block({ block: "reach" }),
      H: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "counter", "cutback", "misdirection"],
    situations: ["1st-down", "2nd-short", "vs-zone"],
    coaching: { keys: "Zone blocking with counter backfield action. It is the answer to a fast-flowing linebacker." },
  }),

  play({
    id: "zone-stretch-boot",
    name: "Stretch Boot",
    aliases: ["Naked Boot", "Zone Boot", "Bootleg"],
    philosophy: "zone-run",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "12",
    protection: "half-slide",
    concept: "boot-flood",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "playside", progression: ["H", "Y", "X"] }],
    assignments: {
      QB: pass("boot", "RB"),
      RB: route("stalk", { toSide: "L" }),
      H: route("flat", { toSide: "R" }, { priorityOrder: 1 }),
      Y: route("drag", { toSide: "R", depthAdj: 8 }, { priorityOrder: 2 }),
      Z: route("comeback", { depth: 14 }, { priorityOrder: 3 }),
      X: route("post", { depth: 12 }, { priorityOrder: 4 }),
    },
    tags: ["play-action", "boot", "flood", "three-level", "run-action"],
    situations: ["1st-down", "2nd-short", "plus-territory", "vs-cover-3", "opening-script"],
    coaching: {
      keys: "Three levels to the boot side. Take the first one that is open and get the ball out.",
      commentary: "The play the wide zone game is really running toward.",
    },
  }),

  play({
    id: "zone-dive",
    name: "Zone Dive",
    aliases: ["FB Dive", "Zone Dive"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "flexbone",
    personnelId: "20",
    run: { scheme: "inside-zone", carrier: "FB", aim: "playside-A" },
    primary: "FB",
    assignments: {
      QB: pass("1step", "FB"),
      FB: carry("playside-A", "dive"),
      A1: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "dive", "option-family", "flexbone", "quick-hitting"],
    situations: ["short-yardage", "1st-down", "4th-short", "four-minute"],
    coaching: { install: "Zone rules on a fullback dive. The option game's answer to a defense that stops the triple." },
  }),

  play({
    id: "zone-inverted-veer",
    name: "Inverted Veer",
    aliases: ["Dash Read", "Inverted Veer"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    reads: [
      { order: 1, type: "zone-read", key: "EMLOS", keySide: "playside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Y: block({ block: "down" }),
      H: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "option", "read", "qb-run", "edge"],
    situations: ["3rd-short", "red-zone", "goal-line", "short-yardage"],
    coaching: { keys: "The back runs the sweep track and the quarterback keeps it downhill. Roles inverted from a zone read." },
  }),

  play({
    id: "zone-bluff",
    name: "Zone Bluff",
    aliases: ["Slice Read", "Zone Bluff"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "pistol-ace-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "zone-read", key: "DE", keySide: "backside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Y: block({ block: "arc" }),
      H: block({ block: "stalk" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "read", "bluff", "arc", "qb-run"],
    situations: ["1st-down", "3rd-short", "red-zone"],
    coaching: { keys: "The tight end fakes the slice and arcs to the alley instead, which is the read key's tell." },
  }),
  play({
    id: "zone-wide-pistol",
    name: "Wide Zone Pistol",
    aliases: ["Pistol Stretch", "Wide Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "pistol-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-C" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-C", "stretch", "playside-B"),
      Y: block({ block: "reach" }),
      H: block({ block: "crack" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "wide-zone", "pistol", "stretch", "downhill-track"],
    situations: ["1st-down", "2nd-short", "opening-script"],
    coaching: { keys: "The pistol depth lets the back get downhill on the same track a shotgun back has to drift for." },
  }),

  play({
    id: "zone-duo-heavy",
    name: "Heavy Duo",
    aliases: ["Jumbo Duo", "13 Duo"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "ace-jumbo",
    personnelId: "13",
    run: { scheme: "duo", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "downhill", "playside-B"),
      Y: block({ block: "base" }),
      H: block({ block: "base" }),
      V: block({ block: "base" }),
      X: route("stalk"),
    },
    tags: ["zone", "duo", "double-team", "heavy", "vertical-displacement"],
    situations: ["short-yardage", "goal-line", "four-minute", "1st-down"],
    coaching: { install: "Every lineman is on a double team. The back finds the crease off the second level." },
  }),

  play({
    id: "zone-split-gun",
    name: "Gun Split Zone",
    aliases: ["Split Zone", "Gun Slice"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: block({ block: "kickout", target: "EMLOS" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "split-zone", "slice", "h-back", "gun"],
    situations: ["1st-down", "short-yardage", "3rd-short"],
    coaching: { install: "The H-back slices back across to take the end that zone rules cannot reach." },
  }),

  play({
    id: "zone-outside-crack",
    name: "Outside Zone Crack",
    aliases: ["Crack Stretch", "Zone Crack"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-trey-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Z: route("crack"),
      H: block({ block: "arc" }),
      Y: block({ block: "reach" }),
      X: route("stalk"),
    },
    tags: ["zone", "crack", "perimeter", "trey"],
    situations: ["1st-down", "plus-territory"],
    coaching: { keys: "Crack the overhang and let the tight end arc to the corner." },
  }),

  play({
    id: "zone-read-bubble-arc",
    name: "Zone Read Arc",
    aliases: ["Arc Read", "Zone Arc"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "zone-read", key: "DE", keySide: "backside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: block({ block: "arc" }),
      Y: block({ block: "climb", target: "PSLB" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "read", "arc", "qb-run", "alley"],
    situations: ["1st-down", "3rd-short", "red-zone"],
    coaching: { keys: "The H-back arcs past the read key to the alley player, so a keep has a lead blocker." },
  }),

  play({
    id: "zone-inside-under-center",
    name: "Inside Zone Under Center",
    aliases: ["Tight Zone", "IZ Under"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "split-backs-pro",
    personnelId: "21",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "downhill", "backside-A"),
      FB: block({ block: "climb", target: "PSLB" }),
      Y: block({ block: "base" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "inside-zone", "under-center", "lead", "pro-set"],
    situations: ["1st-down", "short-yardage", "four-minute"],
    coaching: { keys: "Under center the back is already downhill; the fullback takes the first linebacker to show." },
  }),

  play({
    id: "zone-stretch-shot",
    name: "Stretch Shot",
    aliases: ["Wide Zone Shot", "Stretch Post"],
    philosophy: "zone-run",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "singleback-twins-right",
    personnelId: "11",
    protection: "max-protect",
    concept: "pa-post",
    primary: "X",
    reads: [{ order: 1, type: "progression", key: "FS", progression: ["X", "Z", "H"] }],
    assignments: {
      QB: pass("7step", "RB"),
      X: route("post", { depth: 14 }, { priorityOrder: 1 }),
      Z: route("go", undefined, { priorityOrder: 2 }),
      H: route("over", { toSide: "L" }, { priorityOrder: 3 }),
      Y: block({ block: "hinge" }),
    },
    tags: ["play-action", "shot", "wide-zone-action", "post", "max-protect"],
    situations: ["1st-down", "plus-territory", "vs-cover-3", "vs-cover-1"],
    coaching: {
      keys: "Full wide-zone action. If the safety takes one step downhill the post is behind him.",
    },
  }),

  play({
    id: "zone-toss-stretch",
    name: "Toss Stretch",
    aliases: ["Zone Toss", "Outside Toss"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "weak-i-right",
    personnelId: "21",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pitch("RB"),
      RB: carry("playside-D", "stretch"),
      FB: block({ block: "arc" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("crack"),
    },
    tags: ["zone", "toss", "perimeter", "speed"],
    situations: ["1st-down", "plus-territory", "opening-script"],
    coaching: { keys: "Getting the ball outside before the front can run with it is the whole play." },
  }),

  play({
    id: "zone-dive-option",
    name: "Zone Dive Option",
    aliases: ["Speed Option", "Zone Option"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "pistol-strong-right",
    personnelId: "21",
    run: { scheme: "outside-zone", carrier: "QB", aim: "playside-C" },
    primary: "QB",
    reads: [
      { order: 1, type: "option-pitch", key: "OLB", keySide: "playside", ifTake: { pitch: "RB" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-C", "stretch"),
      RB: route("arrow", { toSide: "R" }, { startDelayMs: 150 }),
      FB: block({ block: "arc" }),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone", "option", "speed-option", "pitch", "edge"],
    situations: ["1st-down", "3rd-short", "plus-territory"],
    coaching: { keys: "No dive phase. Attack the edge and make the outside backer wrong." },
  }),

  play({
    id: "zone-diamond-inside",
    name: "Diamond Inside Zone",
    aliases: ["Diamond IZ", "Three Back Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "pistol-diamond",
    personnelId: "21",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-A", "downhill"),
      A1: block({ block: "arc" }),
      A2: block({ block: "seal" }),
      Z: route("stalk"),
      X: route("stalk"),
    },
    tags: ["inside-zone", "diamond", "three-back", "downhill"],
    situations: ["1st-down", "short-yardage", "four-minute"],
    coaching: { keys: "Two extra blockers on the edges mean the zone can stay tight to the box." },
  }),

  play({
    id: "zone-diamond-stretch",
    name: "Diamond Stretch",
    aliases: ["Diamond Wide", "Three Back Stretch"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "pistol-diamond",
    personnelId: "21",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-D", "stretch"),
      A1: block({ block: "arc", target: "EMLOS" }),
      A2: block({ block: "hinge" }),
      Z: route("crack"),
      X: route("stalk"),
    },
    tags: ["outside-zone", "diamond", "perimeter", "stretch"],
    situations: ["1st-down", "plus-territory", "sideline"],
    coaching: { keys: "Press the edge and read the reach block. The cutback is always there if the front over-runs." },
  }),

  play({
    id: "zone-nub-outside",
    name: "Nub Outside Zone",
    aliases: ["Nub Stretch", "Boundary Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-nub-trips",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Y: block({ block: "reach" }),
      Z: route("stalk"),
      H: route("stalk"),
      X: route("stalk"),
    },
    tags: ["outside-zone", "nub", "gun", "spread-to-run"],
    situations: ["1st-down", "2nd-short", "plus-territory"],
    coaching: { keys: "Trips to the field takes two defenders with it. Run at the tight end into the lighter side." },
  }),

  play({
    id: "zone-twins-inside",
    name: "Twins Inside Zone",
    aliases: ["Twins IZ", "Gun Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-twins-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Z: route("stalk"),
      H: route("stalk"),
      Y: block({ block: "down" }),
      X: route("stalk"),
    },
    tags: ["inside-zone", "gun", "base", "beginner-friendly"],
    situations: ["1st-down", "2nd-short", "short-yardage"],
    coaching: {
      install: "The first run install of most seasons. Aiming point is the playside A gap with the read on the first down lineman.",
    },
  }),

  play({
    id: "zone-arc-read",
    name: "Arc Read",
    aliases: ["Arc Zone Read", "Read Arc"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "backside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      H: block({ block: "arc", target: "second-level" }),
      Z: route("stalk"),
      Y: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone-read", "arc", "option", "qb-run"],
    situations: ["1st-down", "2nd-short", "red-zone"],
    coaching: { keys: "The H arcs past the read man to the alley player, so a pull has a blocker in front of it." },
  }),

  play({
    id: "zone-split-flow",
    name: "Split Flow Zone",
    aliases: ["Split Zone", "Slice"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "i-twins-right",
    personnelId: "21",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "downhill"),
      FB: block({ block: "kickout", target: "EMLOS" }),
      Z: route("stalk"),
      H: route("stalk"),
      X: route("stalk"),
    },
    tags: ["split-zone", "slice", "backside", "downhill"],
    situations: ["1st-down", "2nd-short", "short-yardage"],
    coaching: { keys: "The fullback crosses the formation to kick the backside end, which is what makes the cutback legal." },
  }),

  play({
    id: "zone-mid-heavy",
    name: "Heavy Mid Zone",
    aliases: ["Mid Zone Jumbo", "Tight Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "ace-jumbo",
    personnelId: "13",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "downhill"),
      Y: block({ block: "combo", with: "V" }),
      V: block({ block: "climb", target: "PSLB" }),
      H: block({ block: "hinge" }),
      X: route("stalk"),
    },
    tags: ["mid-zone", "heavy", "combo", "four-minute"],
    situations: ["short-yardage", "four-minute", "3rd-short", "goal-line"],
    coaching: { keys: "Two tight ends combo to the linebacker. The back presses the outside hip and cuts off the double team." },
  }),

  play({
    id: "zone-bash-read",
    name: "Bash",
    aliases: ["Back Away", "Inverted Read"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "gun-trips-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "backside-D" },
    primary: "RB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "playside", ifTake: { give: "RB" }, ifNot: { keep: "QB" } },
    ],
    assignments: {
      QB: carry("playside-B", "downhill"),
      RB: carry("backside-D", "stretch"),
      Z: route("stalk"),
      H: route("stalk"),
      Y: route("stalk"),
      X: route("crack"),
    },
    tags: ["bash", "zone-read", "inverted", "qb-run"],
    situations: ["1st-down", "2nd-short", "red-zone", "plus-territory"],
    coaching: { keys: "The back sweeps away from the line's flow and the quarterback keeps it inside if the end chases." },
  }),

  play({
    id: "zone-jet-stretch",
    name: "Jet Stretch",
    aliases: ["Fly Zone", "Motion Stretch"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-stack-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "H", aim: "playside-D" },
    primary: "H",
    assignments: {
      QB: pass("gun-quick", "H"),
      H: motion("jet", carry("playside-D", "stretch"), 1100, "R"),
      RB: block({ block: "arc" }),
      Z: route("crack"),
      Y: block({ block: "reach" }),
      X: route("stalk"),
    },
    tags: ["outside-zone", "jet", "motion", "perimeter", "speed"],
    situations: ["1st-down", "opening-script", "plus-territory"],
    coaching: { keys: "Motion at full speed at the snap. The whole play is the runner beating the edge defender to the corner." },
  }),

  play({
    id: "zone-draw-gun",
    name: "Gun Draw",
    aliases: ["Draw", "Delay Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-doubles-right",
    personnelId: "10",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    assignments: {
      QB: pass("gun-3", "RB"),
      RB: carry("playside-A", "downhill"),
      Z: route("go", { depth: 14 }),
      X: route("go", { depth: 14 }),
      H: route("go", { depth: 12 }),
      Y: route("go", { depth: 12 }),
    },
    tags: ["draw", "delay", "rush-beater", "answer"],
    situations: ["2nd-long", "3rd-long", "blitz-beater", "vs-cover-0"],
    coaching: { keys: "Four vertical routes clear the box. Let the rush come upfield and run underneath it." },
  }),

  play({
    id: "zone-pin-pull-nub",
    name: "Nub Pin & Pull",
    aliases: ["Pin Pull", "Crack Toss Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "gun-y-off-right",
    personnelId: "11",
    run: { scheme: "pin-pull", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-D", "stretch"),
      Y: block({ block: "down" }),
      H: block({ block: "arc", target: "second-level" }),
      Z: route("crack"),
      X: route("stalk"),
    },
    tags: ["pin-pull", "perimeter", "gap-scheme", "edge"],
    situations: ["1st-down", "plus-territory", "sideline"],
    coaching: { keys: "Anyone covered blocks down, anyone uncovered pulls. The rule sorts itself out against any front." },
  }),

  play({
    id: "zone-stretch-nakeds",
    name: "Stretch Naked",
    aliases: ["Naked Boot", "Zone Naked"],
    philosophy: "zone-run",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "singleback-ace",
    personnelId: "11",
    protection: "sprint-right",
    concept: "naked",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "flat-defender", keySide: "backside", progression: ["Y", "Z", "X"] }],
    assignments: {
      QB: pass("boot", "RB"),
      Y: route("flat", { toSide: "L" }, { priorityOrder: 1 }),
      Z: route("over", { depth: 14 }, { priorityOrder: 2, startDelayMs: 200 }),
      X: route("comeback", { depth: 12 }, { priorityOrder: 3 }),
      H: route("go", { depth: 16 }, { priorityOrder: 4 }),
    },
    tags: ["play-action", "naked", "boot", "zone-action"],
    situations: ["1st-down", "2nd-short", "vs-cover-3", "opening-script"],
    coaching: {
      keys: "No protection at all on the backside, so the ball is out on the fifth step regardless of what is open.",
    },
  }),

  play({
    id: "zone-pop-pass",
    name: "Zone Pop",
    aliases: ["Pop Pass", "Y Pop"],
    philosophy: "zone-run",
    family: "play-action",
    variantScope: [...TACKLE],
    formationId: "gun-y-off-right",
    personnelId: "11",
    concept: "pop",
    primary: "Y",
    reads: [{ order: 1, type: "progression", key: "M", progression: ["Y", "Z", "H"] }],
    assignments: {
      QB: pass("gun-quick", "RB"),
      Y: route("pop", undefined, { priorityOrder: 1 }),
      Z: route("go", { depth: 14 }, { priorityOrder: 2 }),
      H: route("bubble", { toSide: "R" }, { priorityOrder: 3 }),
      X: route("slant", { depth: 6 }, { priorityOrder: 4 }),
    },
    tags: ["pop", "play-action", "seam", "red-zone"],
    situations: ["1st-down", "red-zone", "3rd-short", "goal-line"],
    coaching: { keys: "Full zone footwork, then throw into the window the filling linebacker just left." },
  }),

  play({
    id: "zone-crack-toss-heavy",
    name: "Crack Toss",
    aliases: ["Toss Crack", "Perimeter Toss"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "singleback-twins-right",
    personnelId: "11",
    run: { scheme: "outside-zone", carrier: "RB", aim: "playside-D" },
    primary: "RB",
    assignments: {
      QB: pitch("RB"),
      RB: carry("playside-D", "stretch"),
      Z: route("crack"),
      H: route("crack"),
      Y: block({ block: "reach" }),
      X: route("stalk"),
    },
    tags: ["toss", "crack", "perimeter", "speed"],
    situations: ["1st-down", "plus-territory", "sideline"],
    coaching: { keys: "Both receivers crack inside and the toss gets outside of them before the corner can replace." },
  }),

  play({
    id: "zone-inside-unbalanced",
    name: "Unbalanced Zone",
    aliases: ["Tackle Over Zone", "Heavy Zone"],
    philosophy: "zone-run",
    family: "run",
    variantScope: [...TACKLE],
    formationId: "unbalanced-heavy-right",
    personnelId: "13",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-B" },
    primary: "RB",
    assignments: {
      QB: pass("1step", "RB"),
      RB: carry("playside-B", "downhill"),
      Y: block({ block: "combo", with: "V" }),
      V: block({ block: "climb", target: "PSLB" }),
      H: block({ block: "seal" }),
      X: route("stalk"),
    },
    tags: ["inside-zone", "unbalanced", "heavy", "formation-stress"],
    situations: ["short-yardage", "3rd-short", "four-minute", "goal-line"],
    coaching: { commentary: "Most defenses check their alignment to an unbalanced set. Snap it before they finish." },
  }),

  play({
    id: "zone-read-slice",
    name: "Read Slice",
    aliases: ["Slice Read", "Split Read"],
    philosophy: "zone-run",
    family: "option",
    variantScope: [...TACKLE],
    formationId: "pistol-trips-right",
    personnelId: "11",
    run: { scheme: "inside-zone", carrier: "RB", aim: "playside-A" },
    primary: "RB",
    reads: [
      { order: 1, type: "option-dive", key: "DE", keySide: "backside", ifTake: { keep: "QB" }, ifNot: { give: "RB" } },
    ],
    assignments: {
      QB: pass("gun-quick", "RB"),
      RB: carry("playside-A", "downhill"),
      Y: block({ block: "kickout", target: "EMLOS" }),
      Z: route("stalk"),
      H: route("stalk"),
      X: route("stalk"),
    },
    tags: ["zone-read", "slice", "option", "pistol"],
    situations: ["1st-down", "2nd-short", "vs-cover-1"],
    coaching: { keys: "The slice block and the read key are on the same side, so the quarterback reads the next man out." },
  }),
];
