"""build_teams.py — team names, brand colours and logo URLs.

Writes `teams.json` (about 6 KB). The app uses it for three things: logos on the
scenario cards and the scoreboard, the club colours that fill the end zones on
the field, and the full team name so the interface can stop saying "KC" at
people.

Logos are hotlinked from ESPN's CDN rather than mirrored into the repo. That
matches what NFL Prospect Comparables already does for player headshots, keeps
the repo free of trademarked artwork, and costs nothing in bundle size. The
tradeoff is a runtime dependency on ESPN, which `TeamLogo` handles by falling
back to the three-letter abbreviation set in the club's own colour.

Every URL is checked for a 200 and an image content-type before it is written,
following the rule already set out in `headshot-overrides.ts`.

Usage:
    uv run python build_teams.py
    uv run python build_teams.py --no-verify     # skip the network check
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import nflreadpy as nfl
import requests

from publish import publish

HERE = Path(__file__).parent

# nflverse carries historical franchises (OAK, SD, STL) alongside current ones.
# The scenario corpus is already normalised to current codes, so anything not
# referenced by a scenario is surplus — but it is a few hundred bytes and
# keeping it means a corpus rebuild that reaches further back still resolves.
FIELDS = [
    "team_abbr", "team_name", "team_nick", "team_conf", "team_division",
    "team_color", "team_color2", "team_logo_espn", "team_wordmark",
]


def verify(url: str) -> bool:
    try:
        r = requests.head(url, timeout=20, allow_redirects=True)
        return r.status_code == 200 and r.headers.get("content-type", "").startswith("image/")
    except requests.RequestException:
        return False


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-verify", action="store_true")
    ap.add_argument("--out", type=Path, default=HERE / "teams.json")
    args = ap.parse_args()

    df = nfl.load_teams().to_pandas()
    df = df[[c for c in FIELDS if c in df.columns]].drop_duplicates("team_abbr")

    teams: dict[str, dict] = {}
    bad: list[str] = []
    for r in df.itertuples():
        logo = getattr(r, "team_logo_espn", None)
        if logo and not args.no_verify and not verify(logo):
            bad.append(r.team_abbr)
            logo = None
        teams[r.team_abbr] = {
            "name": r.team_name,
            "nick": getattr(r, "team_nick", r.team_name),
            "conf": getattr(r, "team_conf", None),
            "div": getattr(r, "team_division", None),
            # Club colours, used to fill the end zones and accent the scoreboard.
            "color": getattr(r, "team_color", "#1b4f7a"),
            "color2": getattr(r, "team_color2", "#000000"),
            "logo": logo,
            "wordmark": getattr(r, "team_wordmark", None),
        }

    payload = {
        "_note": "Generated by projects/two-minute-drill/build_teams.py — do not hand-edit.",
        "source": "nflreadpy.load_teams(); logos hotlinked from ESPN's CDN",
        "teams": teams,
    }
    blob = json.dumps(payload, separators=(",", ":"), allow_nan=False)
    args.out.write_text(blob)
    publish("teams.json", blob)

    print(f"wrote {len(teams)} teams, {len(blob) / 1024:.1f} KB")
    if bad:
        print(f"  logo URL failed verification for: {', '.join(bad)} (logo set to null)")
    elif not args.no_verify:
        print("  every logo URL returned 200 with an image content-type")

    # A scenario referencing a team we have no entry for would render a blank
    # card, so say so now rather than in the browser.
    sc = HERE / "scenarios.json"
    if sc.exists():
        codes = set()
        for s in json.loads(sc.read_text())["scenarios"]:
            codes |= {s["home"], s["away"], s["start"]["posteam"], s["start"]["defteam"]}
        missing = sorted(codes - set(teams))
        print(f"  scenario teams covered: {len(codes) - len(missing)}/{len(codes)}"
              + (f" — MISSING {missing}" if missing else ""))


if __name__ == "__main__":
    main()
