"""Assert the browser port of the weakening policy matches the Python one.

    uv run python parity_test.py

Why this exists: `calibrate.py` measures the *Python* policy and writes rung
parameters into `ladder.json`. The browser runs a TypeScript port. If the two
ever diverge, nothing crashes and nothing looks wrong — the dial simply stops
meaning what it says, and every Elo label on the page becomes a quiet lie. This
is the cheapest possible guard against that.

Method: drive both implementations with the *same* deterministic uniform stream
over the same candidate lists (real Stockfish MultiPV output from a handful of
positions), and require the chosen moves to match exactly. Both `_sample`
implementations consume exactly one draw per decision and walk the cumulative
weights identically, which is what makes an exact comparison possible.

Run this after touching either file.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import chess
import chess.engine

import openings
from weakening import candidates, choose_from, params_for

HERE = Path(__file__).parent
TS_RUNNER = HERE / "results" / "parity_runner.mjs"
TS_POLICY = HERE.parents[1] / "src" / "app" / "projects" / "chess-coach" / "engine" / "weakening.ts"

# Sampled across the strength curve so both the blunder branch (wide bands, high
# blunder rate) and the near-deterministic top end get exercised.
STRENGTHS = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
TRIALS = 400

RUNNER_SRC = """
// Generated by parity_test.py. Runs the TypeScript policy over fixtures.
import { selectMove } from "%s";

const cases = JSON.parse(process.argv[2]);
const out = cases.map(({ candidates, params, draws }) => {
  let i = 0;
  return selectMove(candidates, params, () => draws[i++]);
});
console.log(JSON.stringify(out));
"""


class Draws:
    """Replays a fixed list of uniforms, so both languages see the same stream."""

    def __init__(self, values: list[float]) -> None:
        self._values = values
        self._i = 0

    def __call__(self) -> float:
        value = self._values[self._i]
        self._i += 1
        return value


def collect_fixtures(engine: chess.engine.SimpleEngine) -> list[dict]:
    """Real MultiPV output from a spread of positions, at each strength."""
    fixtures: list[dict] = []
    # A deterministic uniform stream. Two draws per trial is the maximum the
    # policy can consume (blunder check, then one weighted pick).
    stream = [(i * 0.6180339887498949) % 1.0 for i in range(1, TRIALS * 2 + 1)]

    for opening_index in range(0, len(openings.OPENINGS), 4):
        board = openings.starting_board(opening_index)
        for strength in STRENGTHS:
            params = params_for(strength)
            scored = candidates(engine, board, params)
            if not scored:
                continue
            for trial in range(TRIALS // len(STRENGTHS)):
                offset = (trial * 2) % (len(stream) - 2)
                fixtures.append(
                    {
                        "candidates": [{"move": m.uci(), "cp": cp} for m, cp in scored],
                        "params": params.to_json(),
                        "draws": [stream[offset], stream[offset + 1]],
                        "_scored": scored,
                    }
                )
    return fixtures


def run_typescript(fixtures: list[dict]) -> list[str | None]:
    """Execute the real .ts policy under Node's type-stripping loader."""
    TS_RUNNER.parent.mkdir(parents=True, exist_ok=True)
    TS_RUNNER.write_text(RUNNER_SRC % TS_POLICY.as_posix())

    payload = json.dumps(
        [{k: v for k, v in f.items() if not k.startswith("_")} for f in fixtures]
    )
    result = subprocess.run(
        ["node", "--experimental-strip-types", "--no-warnings", str(TS_RUNNER), payload],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise RuntimeError("TypeScript policy runner failed")
    return json.loads(result.stdout)


def main() -> int:
    engine_path = shutil.which("stockfish")
    if not engine_path:
        print("stockfish not found — `brew install stockfish`", file=sys.stderr)
        return 1

    engine = chess.engine.SimpleEngine.popen_uci(engine_path)
    engine.configure({"Threads": 1, "Hash": 64})
    try:
        fixtures = collect_fixtures(engine)
    finally:
        engine.quit()

    ts_moves = run_typescript(fixtures)

    mismatches = []
    for i, (fixture, ts_move) in enumerate(zip(fixtures, ts_moves)):
        params = params_for(0.0).__class__(**fixture["params"])
        py_move = choose_from(fixture["_scored"], params, Draws(fixture["draws"]))
        py_uci = py_move.uci() if py_move else None
        if py_uci != ts_move:
            mismatches.append((i, py_uci, ts_move, fixture["params"]))

    print(f"compared {len(fixtures)} decisions across {len(STRENGTHS)} strengths")
    if mismatches:
        print(f"\n{len(mismatches)} MISMATCH(ES) — the dial's Elo labels are not trustworthy:\n")
        for i, py, ts, params in mismatches[:10]:
            print(f"  #{i}: python={py!r} typescript={ts!r}  params={params}")
        return 1

    print("PASS — the browser policy matches the calibrated Python policy exactly")
    return 0


if __name__ == "__main__":
    sys.exit(main())
