"""Check the browser's UCI parser against real Stockfish output.

    uv run python uci_parse_test.py

The browser talks to Stockfish WASM over the UCI text protocol. That parsing is
where a realistic bug lives — a missed `multipv` index or a mishandled `score
mate` would silently reorder the candidate list, which feeds straight into move
selection. The transport around it (a Worker and a message listener) is thin.

So: capture genuine `info` lines from the native engine — including mate lines,
which are the easy ones to get wrong — replay them through the exported
TypeScript parser, and compare against what python-chess reports for the same
positions.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import chess
import chess.engine

from weakening import MATE_SCORE, MULTIPV

HERE = Path(__file__).parent
RUNNER = HERE / "results" / "uci_parse_runner.mjs"
UCI_TS = HERE.parents[1] / "src" / "app" / "projects" / "chess-coach" / "engine" / "uci.ts"

# Positions chosen to exercise the awkward cases, not just the happy path.
POSITIONS = [
    # Ordinary opening position: plain `score cp`.
    ("startpos", chess.STARTING_FEN),
    # Back-rank mate in 1 for White: `score mate 1` (positive).
    ("mate-in-1", "6k1/5ppp/8/8/8/8/8/R3K3 w - - 0 1"),
    # Endgame with few legal moves: fewer PVs than MultiPV requests.
    ("sparse", "8/8/8/4k3/8/4K3/4P3/8 w - - 0 1"),
]

# The negative-mate branch is exercised with handcrafted lines rather than a
# position, because a position where the side to move is being force-mated is
# fiddly to construct and adds nothing: the parser reaches the same code with a
# flipped sign. These also pin the mate-distance ordering — a faster mate must
# score higher — which is what keeps the sampler's ranking correct.
SYNTHETIC = [
    ("mate -1 for mover", "info depth 5 multipv 1 score mate -1 pv e1e2", -(MATE_SCORE) + 1),
    ("mate -3 for mover", "info depth 5 multipv 1 score mate -3 pv e1e2", -(MATE_SCORE) + 3),
    ("mate +2 for mover", "info depth 5 multipv 1 score mate 2 pv a1a8", MATE_SCORE - 2),
    ("plain negative cp", "info depth 5 multipv 1 score cp -45 pv e1e2", -45),
    # A `lowerbound`/`upperbound` line still carries a usable score and pv.
    ("bounded score", "info depth 5 multipv 1 score cp 12 lowerbound pv d2d4", 12),
]

RUNNER_SRC = """
// Generated by uci_parse_test.py. Uses the real exported helpers rather than
// reimplementing the sort, so the test exercises the shipped code path.
import { applyInfoLine, rankedMoves } from "%s";

const cases = JSON.parse(process.argv[2]);
const out = cases.map(({ lines }) => {
  const best = new Map();
  for (const line of lines) applyInfoLine(best, line);
  return rankedMoves(best);
});
console.log(JSON.stringify(out));
"""


def capture_lines(engine_path: str, fen: str, depth: int) -> list[str]:
    """Run a raw UCI search and keep every `info` line the engine emits.

    Note this cannot be a one-shot `subprocess.run` with a piped script: the
    engine consumes all of stdin immediately, so a trailing `quit` terminates it
    before the search produces anything. Read until `bestmove`, then quit.
    """
    proc = subprocess.Popen(
        [engine_path],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    assert proc.stdin and proc.stdout
    # These MUST match the options used for the python-chess reference engine.
    # Stockfish is deterministic at a fixed depth only for a fixed Threads and
    # Hash; differing values produce genuinely different searches, which would
    # look like a parser bug.
    for command in (
        "uci",
        "setoption name Threads value 1",
        "setoption name Hash value 64",
        f"setoption name MultiPV value {MULTIPV}",
        f"position fen {fen}",
        f"go depth {depth}",
    ):
        proc.stdin.write(command + "\n")
    proc.stdin.flush()

    lines: list[str] = []
    for line in proc.stdout:
        if line.startswith("info "):
            lines.append(line.rstrip("\n"))
        elif line.startswith("bestmove"):
            break

    proc.stdin.write("quit\n")
    proc.stdin.flush()
    proc.wait(timeout=10)
    return lines


def expected(engine_path: str, fen: str, depth: int) -> list[dict]:
    """What python-chess reports for the same position, as the reference.

    Spawns a *fresh* engine per position on purpose. Reusing one process across
    positions leaves a warm transposition table, which changes the search and
    therefore which moves land in the top-N — that shows up as a parser
    mismatch when the parser is fine. The raw capture is a fresh process each
    time, so this has to be too.
    """
    engine = chess.engine.SimpleEngine.popen_uci(engine_path)
    try:
        engine.configure({"Threads": 1, "Hash": 64})
        board = chess.Board(fen)
        infos = engine.analyse(board, chess.engine.Limit(depth=depth), multipv=MULTIPV)
    finally:
        engine.quit()

    out = []
    for rank, info in enumerate(infos):
        pv, score = info.get("pv"), info.get("score")
        if not pv or score is None:
            continue
        cp = score.pov(board.turn).score(mate_score=MATE_SCORE)
        out.append({"move": pv[0].uci(), "cp": cp, "rank": rank})
    # Same tie-break as `rankedMoves` in uci.ts: score first, engine rank second.
    return sorted(out, key=lambda row: (-row["cp"], row["rank"]))


def main() -> int:
    engine_path = shutil.which("stockfish")
    if not engine_path:
        print("stockfish not found — `brew install stockfish`", file=sys.stderr)
        return 1

    depth = 10
    cases, references = [], []
    for name, fen in POSITIONS:
        cases.append({"name": name, "lines": capture_lines(engine_path, fen, depth)})
        references.append(expected(engine_path, fen, depth))

    # Synthetic single-line cases ride along in the same Node invocation.
    for name, line, _cp in SYNTHETIC:
        cases.append({"name": name, "lines": [line]})

    RUNNER.parent.mkdir(parents=True, exist_ok=True)
    RUNNER.write_text(RUNNER_SRC % UCI_TS.as_posix())
    result = subprocess.run(
        ["node", "--experimental-strip-types", "--no-warnings", str(RUNNER), json.dumps(cases)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        return 1
    parsed = json.loads(result.stdout)

    failures = 0
    for (name, _fen), got, want in zip(POSITIONS, parsed, references):
        got_moves = [row["move"] for row in got]
        want_moves = [row["move"] for row in want]
        # Compare the ordered move list and the top score. Deeper scores can
        # differ by a ply of search noise between the two invocations, but the
        # ranking and the mate/cp handling must agree.
        #
        # `got` must be non-empty: an empty-equals-empty comparison would pass
        # while proving nothing, which is exactly how this test first "passed".
        ok = bool(got) and got_moves == want_moves and got[0]["cp"] == want[0]["cp"]
        status = "ok" if ok else "FAIL"
        print(f"  [{status}] {name}: {len(got_moves)} pv(s), top={got[0] if got else None}")
        if not ok:
            failures += 1
            print(f"        typescript: {got_moves}")
            print(f"        python-chess: {want_moves}")

    for (name, _line, want_cp), got in zip(SYNTHETIC, parsed[len(POSITIONS) :]):
        ok = len(got) == 1 and got[0]["cp"] == want_cp
        print(f"  [{'ok' if ok else 'FAIL'}] {name}: got={got}, want cp={want_cp}")
        if not ok:
            failures += 1

    if failures:
        print(f"\n{failures} case(s) parsed differently — the browser would misrank candidates")
        return 1
    print("\nPASS — the browser's UCI parser matches python-chess and handles mate scores")
    return 0


if __name__ == "__main__":
    sys.exit(main())
