"""teams.py — team names, colors and official marks.

Same approach as projects/two-minute-drill/build_teams.py, and for the same
reasons: logos are HOTLINKED from ESPN's CDN rather than mirrored into the repo.
That keeps trademarked artwork out of the repository, costs nothing in bundle
size, and matches what NFL Prospect Comparables already does for headshots. The
tradeoff is a runtime dependency on ESPN, which the `TeamLogo` component handles
by falling back to the team abbreviation set in the team's own color.

Every URL is checked for a 200 and an image content-type before it is written.

Usage:
    uv run python teams.py [--no-verify]
"""
from __future__ import annotations

import argparse
import json

import nflreadpy as nfl
import requests

from common import HERE, norm_team

PUBLIC = HERE.parent.parent / "public" / "draft-sheet"

FIELDS = ["team_abbr", "team_name", "team_nick", "team_conf", "team_division",
          "team_color", "team_color2", "team_logo_espn", "team_wordmark"]


def verify(url: str) -> bool:
    try:
        r = requests.head(url, timeout=20, allow_redirects=True)
        return r.status_code == 200 and r.headers.get("content-type", "").startswith("image/")
    except requests.RequestException:
        return False


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-verify", action="store_true")
    args = ap.parse_args()

    df = nfl.load_teams().to_pandas()
    df = df[[c for c in FIELDS if c in df.columns]].drop_duplicates("team_abbr")

    # nflverse carries historical franchises (OAK, SD, STL) beside the current
    # ones, and norm_team collapses each pair onto the same team code. Without
    # this the historical row wins and the Raiders render as "Oakland".
    teams, bad = {}, []
    rows = sorted(df.itertuples(), key=lambda r: norm_team(r.team_abbr) != r.team_abbr)
    seen: set[str] = set()
    for r in rows:
        abbr = norm_team(r.team_abbr)
        if not abbr or abbr in seen:
            continue
        seen.add(abbr)
        logo = getattr(r, "team_logo_espn", None)
        if logo and not args.no_verify and not verify(logo):
            bad.append(abbr)
            logo = None
        teams[abbr] = {
            "name": r.team_name,
            "nick": getattr(r, "team_nick", r.team_name),
            "conf": getattr(r, "team_conf", None),
            "div": getattr(r, "team_division", None),
            "color": getattr(r, "team_color", "#1b4f7a"),
            "color2": getattr(r, "team_color2", "#000000"),
            "logo": logo,
            "wordmark": getattr(r, "team_wordmark", None),
        }

    PUBLIC.mkdir(parents=True, exist_ok=True)
    payload = {
        "_note": "Generated by projects/draft-sheet/teams.py — do not hand-edit.",
        "source": "nflreadpy.load_teams(); marks hotlinked from ESPN's CDN",
        "teams": teams,
    }
    blob = json.dumps(payload, separators=(",", ":"))
    (PUBLIC / "teams.json").write_text(blob)
    print(f"  {len(teams)} teams, {len(blob) / 1024:.1f} KB")
    if bad:
        print(f"  logo URL failed verification: {', '.join(bad)}")
    elif not args.no_verify:
        print("  every logo URL returned 200 with an image content-type")


if __name__ == "__main__":
    main()
