/**
 * Shapes of the published artifacts (public/start-sit/*.json) and the
 * viewer's scoring choice. Generated by projects/start-sit/publish.py.
 */

export type StatKey =
  | "pass_yds" | "pass_tds" | "ints" | "rush_yds" | "rush_att" | "rec" | "rec_yds";

export const STAT_KEYS: StatKey[] = [
  "pass_yds", "pass_tds", "ints", "rush_yds", "rush_att", "rec", "rec_yds",
];

/** `book` is a sportsbook consensus; `dfs` is a pick'em line standing in. */
export type Tier = "book" | "dfs";

export interface StatLine {
  /** The market's median. */
  line: number;
  /** Expected value after the market's lean is applied. */
  ev: number;
  /** Typical game-to-game spread at this level, from the 2025 fit. */
  sd: number;
  /** Spread of the per-book expected values; null with fewer than three books. */
  se: number | null;
  books: number;
  tier: Tier;
}

export interface TdLine {
  /** P(at least one touchdown) implied by the published rate. */
  p: number;
  /** The market's vig-inclusive figure before the field was scaled. */
  pRaw?: number;
  /** Expected touchdowns under a Poisson count. */
  lambda: number;
  books: number;
  tier: Tier;
  paired: boolean;
  scaled: number;
}

export type Position = "QB" | "RB" | "WR" | "TE";

export type Coverage = "full" | "partial" | "td-only" | "none" | "bye" | "played";

export interface Injury {
  status: string;
  severity: "out" | "doubtful" | "questionable";
  part: string | null;
  detail: string;
}

export interface Player {
  id: string;
  name: string;
  short: string;
  pos: Position;
  team: string;
  espnId: string | null;
  gsisId: string | null;
  rank: number;
  game: string | null;
  opp: string | null;
  home: boolean | null;
  kickoff: string | null;
  injury: Injury | null;
  coverage: Coverage;
  stats: Partial<Record<StatKey, StatLine>> & { td?: TdLine };
}

export interface Game {
  id: string;
  week: number;
  home: string;
  away: string;
  kickoff: string;
  played: boolean;
  spread: number | null;
  total: number | null;
  homeTotal: number | null;
  awayTotal: number | null;
  lineSource: "nflverse" | "sgo";
  expectedTds: Record<string, number | null>;
}

export interface Meta {
  built: string;
  builtAt: string;
  season: number;
  week: number;
  snapshot: "daily" | "final";
  counts: Record<string, number>;
  books: string[];
  sigma: Record<StatKey, { a: number; b: number; n: number; r2: number; sdMin: number }>;
  sigmaSeason: number;
  tdPerPoint: number;
  sanity: {
    ran: boolean;
    spearman: Record<string, number>;
    maxLeanSd: number;
    fantasyScore?: { n: number; r: number | null; meanGap: number | null };
  };
  attribution: Record<string, string>;
}

export interface Scoring {
  /** Points per reception. */
  rec: 0 | 0.5 | 1;
  /** Points per passing touchdown. */
  passTd: 4 | 6;
}

export const DEFAULT_SCORING: Scoring = { rec: 0.5, passTd: 4 };

export const REC_OPTIONS: { value: Scoring["rec"]; label: string }[] = [
  { value: 0, label: "Standard" },
  { value: 0.5, label: "Half PPR" },
  { value: 1, label: "Full PPR" },
];

export const PASS_TD_OPTIONS: { value: Scoring["passTd"]; label: string }[] = [
  { value: 4, label: "4 pt pass TD" },
  { value: 6, label: "6 pt pass TD" },
];

export const STAT_LABEL: Record<StatKey | "td", string> = {
  pass_yds: "Passing yards",
  pass_tds: "Passing TDs",
  ints: "Interceptions",
  rush_yds: "Rushing yards",
  rush_att: "Carries",
  rec: "Receptions",
  rec_yds: "Receiving yards",
  td: "Anytime TD",
};

/** Display order on a card: what the position is paid for, first. */
export const STAT_ORDER: Record<Position, (StatKey | "td")[]> = {
  QB: ["pass_yds", "pass_tds", "ints", "rush_yds", "td"],
  RB: ["rush_att", "rush_yds", "rec", "rec_yds", "td"],
  WR: ["rec", "rec_yds", "rush_yds", "td"],
  TE: ["rec", "rec_yds", "td"],
};

export const MAX_PICKS = 5;
export const DEFAULT_SLOTS = 2;
